### ISSUE TITLE
A couple compiler errors on XCode 6.3 beta

### ISSUE THREAD

**Issue by mrjjwright** [facebook/componentkit#1]
Thanks so much for ComponentKit!  It's awesome, the example scrolls so smooth!   Of course I switched over to 6.2 but just letting you all know (you probably already do) about these:

 `/Users/jwright/Downloads/ios_examples/componentkit/ComponentTextKit/TextKit/CKTextKitRendererCache.mm:28:12: Out-of-line definition of 'Key' does not match any declaration in 'CK::TextKit::Renderer::Key' `

and

`/Users/jwright/Downloads/ios_examples/componentkit/Examples/WildeGuess/Pods/Headers/Build/ComponentKit/CKTextKitRendererCache.h:69:9: Constructor cannot have a return type`

**Comment by mrjjwright** [comment]
Of course I switched over to 6.2 but just letting you all know, you probably already do.

**Comment by adamjernst** [comment]
Thanks! We're on it.
