### ISSUE TITLE
Question: what is best practise to make a round side button

### ISSUE THREAD

**Issue by smalllixin** [facebook/componentkit#101]
Hi, I am building our new UI with componentkit. Really amazing & fast.
A widget in design is round side button.  
How can I done this with componentkit?
![ckissue](https://cloud.githubusercontent.com/assets/787881/7100451/3468577c-e055-11e4-880e-9180f43de523.jpg)

**Comment by smiLLe** [comment]
```
[CKComponent
        newWithView:{
          [UIView class],
          {
            {CKComponentViewAttribute::LayerAttribute(@selector(setCornerRadius:)), @5.0}
          }
        }
        size:{
          .height = 10,
        }
      ]
```

but i dont know how to set the rounded corners if you dont have an explicit height set. Maybe someone from facebook can help.

**Comment by smalllixin** [comment]
Thank u~ Solved my issue.
