### ISSUE TITLE
CKTextComponent linkTextAttributes?

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/componentkit#105]
Is it possible to change the color of the links? 

Thank you.

**Comment by ocrickard** [comment]
Yep!  All you need to do is change the NSForegroundColorAttributeName value to your color on your attributed string.

**Comment by vishnevskiy** [comment]
I tried that before opening this ticket. Maybe you can tell me what I am doing wrong. He is an example.

https://gist.github.com/vishnevskiy/de9f64d4f9a452956243#file-test-m-L38

**Comment by ocrickard** [comment]
As pointed out by others, I need to document this api!

The styling issue is actually in TextKit itself. This and other reasons are why we use an entity attribute instead to signify links (on my phone so can't get a link right now but you can find it by searching). Use an entity along with component actions to add taps me entities like links.

**Comment by grp** [comment]
I think the best way to describe it is that the "link" attribute and the styling of a link are completely separate. What's tappable is controlled by `CKTextKitEntityAttributeName`, but it's up to you to style the ranges with `CKTextKitEntityAttributeName` however you want the links to appear.
