### ISSUE TITLE
Compiler Warning on Advanced Views usage

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/componentkit#106]
I was following the guide as specified here:
http://componentkit.org/docs/advanced-views.html
And implemented the following code
```
@implementation AndFinallyNewsStoryComponent
+ (instancetype)newWithHeadline:(NSString *)headline
               shortDescription:(NSString *)shortDescription
                          stats:(NSAttributedString *)stats
                       andImage:(UIImage *)image
{
    return [super newWithComponent:
            [CKComponent
             newWithView:{&gradientOverlay}
             size:{.width = 50,.height = 50}]];
}

static GradientOverlay *gradientOverlay(void) {
    return [[GradientOverlay alloc] initWithColor:[UIColor redColor]];
}
```
This produces an unexpected compiler warning in the form of: Incompatible pointer types passing 'GradientOverlay *(*)()' to parameter of type 'UIView *(*)()'

GradientOverlay is currently a subclass of UIView, should this be something else? It's not specified in the docs of any additional changes needed.

**Comment by adamjernst** [comment]
Nope this is simply an error. Mind submitting a pull request to fix it?

**Comment by aaronschubert0** [comment]
Can do. Do you mean this is an error in the docs or code? Just wanting to clarify.

**Comment by adamjernst** [comment]
Error in the docs.

**Comment by aaronschubert0** [comment]
Cool, submitted the PR and have signed the CLA.
