### ISSUE TITLE
Enhancement : Use custom UIEdgeInsets struct to support .all

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/componentkit#115]
More often than not, I find myself wanting the same amount of inset in all directions, like so:
```
    [CKInsetComponent
     newWithInsets:{.top = 10, .bottom = 10, .left = 10, .right = 10}
     component:[CKComponent new]];
```
It would be fantastic to have support for a ".all" property so I can condense this like so:
```
    [CKInsetComponent
     newWithInsets:{.all = 10}
     component:[CKComponent new]];
```

I'm happy to put the work in for this, if a direction is agreed. Would this fit into the current model?

**Comment by smiLLe** [comment]
since newWithInset requires a UIEdgeInset you could make a macro requiring one float param and return a UIEdgeInset.

**Comment by aaronschubert0** [comment]
@smiLLe was hoping to avoid a macro, in favour of something more integrated, almost an extension on the UIEdgeInset struct.

**Comment by smalllixin** [comment]
Although in your case I think UIEdgeInset is good enough. 
 You can do it this way.
```Objective-C
//First define a struct.
struct CKInsetsAll {
    CGFloat all;
};

//Then make a wrapper
+ (CKInsetComponent *)newWithInsets:(CKInsetsAll)insetsAll component:(CKComponent*)component {
    return [CKInsetComponent
            newWithInsets:
            UIEdgeInsetsMake(insetsAll.all, insetsAll.all, insetsAll.all, insetsAll.all)
            component:component];

[xxx newWithInsets:{.all=5} component:yyy];
```

**Comment by adamjernst** [comment]
Yeah—this is best done with a helper function:

```
UIEdgeInsets XXEdgeInsetsAll(CGFloat i) {
  return {i, i, i, i};
}
```

(where XX is your two character prefix of choice)

You could get fancy with a separate type and C++ type conversion rules, but I think that's overkill.

We're not planning to add anything to ComponentKit core for this because we don't want to modify or wrap `UIEdgeInsets`.

**Comment by aaronschubert0** [comment]
Cool sounds good to me, thanks!
