### ISSUE TITLE
What is best practice when pass message from component to the ViewController?

### ISSUE THREAD

**Issue by andyqee** [facebook/componentkit#117]

**Comment by smiLLe** [comment]
use the context object.
you could set the viewController as a weak property in the context.

see @adamjernst answer in #96

**Comment by andyqee** [comment]
I Guess to use context, but I am not very quite sure if it fit the best.<br> But you answer conformed me! Thank you !

**Comment by adamjernst** [comment]
Thanks @smiLLe
