### ISSUE TITLE
Build fail for the Getting start repo.

### ISSUE THREAD

**Issue by kithokit** [facebook/componentkit#12]
I follow the instruction on 
http://componentkit.org/docs/getting-started.html

The wildeguess repo build fail.

ld: library not found for -lPods-ComponentKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How can we solve this out? THanks

**Comment by rpowelll** [comment]
Did you run `pod install` from the project directory?

**Comment by kithokit** [comment]
I did. The podfile.lock 
PODS:
  - ComponentKit (0.9)

DEPENDENCIES:
  - ComponentKit (from `../..`)

EXTERNAL SOURCES:
  ComponentKit:
    :path: ../..

SPEC CHECKSUMS:
  ComponentKit: 78d73c354af113de9cdd4605b825c9ca315da773

COCOAPODS: 0.36.0

and I start the project at the root path of WildeGuess.
```
kit.ho@10:24:01 WildeGuess(master) $ pwd
/Users/kit.ho/SwiftOpenCV/componentkit/Examples/WildeGuess
kit.ho@10:29:53 WildeGuess(master) $ open WildeGuess.xcodeproj/
```

**Comment by benlodotcom** [comment]
You should open the workspace instead of the project.

**Comment by kithokit** [comment]
@benlodotcom Thanks! It works now. I will close the issue
