### ISSUE TITLE
Question - ComponentKit Accessibility Support

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/componentkit#127]
Hi, I've implemented various CKLabel/TextComponents and have then turned on the voice over accessibility inspector expecting the accessibility inspector to recognise each element out of the box. However the accessibility inspector doesn't recognise any component, how can this be fixed?

**Comment by ocrickard** [comment]
I didn't enable it by default in our text components.  I'll put up a diff in one sec to fix/update the behavior.

**Comment by aaronschubert0** [comment]
Awesome, thanks for the quick turnaround!
