### ISSUE TITLE
Add ability to specify a component aspect ratio

### ISSUE THREAD

**Issue by itsthejb** [facebook/componentkit#131]
Hi all,

First of all, the framework is fantastic, many thanks for all the great work.

Currently what *appears* to be a missing feature is the ability to create a dimension related to the *other* axis. For example, a component which has a height that is always 50% of its width, or vice versa, etc. It would certainly be great to avoid hard-coding any component sizes, and only resolve when the root component has one or more fixed dimensions. There is `CKRelativeDimension::resolve(CGFloat autoSize, CGFloat parent)`, but that doesn't appear to be for this task since it's not possible to specify a relationship.

If this is already available, then I'd love to hear about it, and apologies for not being able to find it myself. However, from what I can see, CSS Flex Box doesn't support these relationships either, so this feature may be out of scope; after all, I can see that this could create the possibility of Auto-layout style unsatisfiable constraints.

In any case, would be great to hear some input on this, even if it's a non-issue.

Thanks!

**Comment by grp** [comment]
Is there a design/layout you could share where a setup like you described is needed?

**Comment by itsthejb** [comment]
Hi,

I realise that the simplest way to explain this is just that I would like to be able to specify as aspect ratio for a component's size (and I've changed the issue title reflect this).

In detail, I have a component that uses a horizontal stack layout to tile images of various sizes into rows. For a given row, I can calculate a height `h` that satisfies the layout for any width `w`. If I use auto width I can't use a percentage height for the component since the component should resize vertically. I can use a fixed height, but then I have to assume a fixed width also. I can only achieve a width-independent layout if I can specify that `h = w * c`, so this is essentially specifying an aspect ratio for the component.

**Comment by adamjernst** [comment]
This is a neat idea, and you're right — aspect ratios are indeed a great use for this!

We faced the same problem here and debated how best to handle it. Eventually we settled on `CKRatioLayoutComponent`. This has some notable limitations, but it keeps the core dimension system a lot simpler.

Thoughts on that?

**Comment by itsthejb** [comment]
Great! That's exactly what I want. I was looking in the size classes and didn't think to look for a component class. Many thanks!
