### ISSUE TITLE
CKLabelComponent truncation issue with NSLineBreakByCharWrapping

### ISSUE THREAD

**Issue by DrChrispoper** [facebook/componentkit#135]
@ocrickard 
The issue is similar to #75 
Setting a CKLabelComponent with max of 1 line breaks having
.lineBreakMode = NSLineBreakByCharWrapping

**Comment by ocrickard** [comment]
Uggh, yeah, sorry I've been super busy.  Let's add a failing snapshot test and I'll get to it as soon as I possibly can.

**Comment by adamjernst** [comment]
Waiting for a failing snapshot test case—reopen when ready!
