### ISSUE TITLE
Update state while component is unmount

### ISSUE THREAD

**Issue by myeyesareblind** [facebook/componentkit#136]
My componentController contains some custom logic, which should update controller.component state.
The problem is that component might be unmounted when this happens, and it's not clear when to update.
What would be my best option to update component's state while it's not attached to controller?

**Comment by adamjernst** [comment]
`Controller.component` should be non-nil even when the component is not mounted. It's valid to call `[self.component updateState:^{}]` from the controller even when unmounted.

If the controller's component is nil, it's a bug — submit an issue with repro steps!
