### ISSUE TITLE
Best way to adjust cell size based on layout guides

### ISSUE THREAD

**Issue by cfcommando** [facebook/componentkit#137]
I'm trying to build a collection view where a static title cell (section 0, item 0) takes up the visible area on-screen, adjusted for navigation/tab bars. However, the layout guides are only supposed to be accessed from within `-viewDidLayoutSubviews`. 

Given the moving parts involved, I'm having trouble determining the best way to dictate a component's height from `-viewDidLayoutSubviews` and into the component.

Should I be reloading the index path on layout (and animate the bounds) to adjust it to bounds updates? Can I specify width/height = 100% on a top-level component (a quick test says no and hit an assertion, but I may have done something wrong)?

**Comment by benlodotcom** [comment]
> Should I be reloading the index path on layout (and animate the bounds) to adjust it to bounds updates? 

You could definitely do that if you want to resize your top item this way and pass for you min and max height the bounds of the collectionView.

> Can I specify width/height = 100% on a top-level component

What was the constrained size you were passing in ?

**Comment by cfcommando** [comment]
Alright, I'll try that. I assume it will prefer to reuse the views rather than redraw everything if I have the scope set appropriately? Animations as well?

The constrained size was a flexible height from a size range provider. ((320, 0),(320,∞)). I suppose the ∞ triggered the assert?

Thank you for your help! It is much appreciated.

**Comment by adamjernst** [comment]
It will prefer to reuse the views, *except* that occasionally `UITableView`/`UICollectionView` will decide that it wants to use a different cell and then it's out of our hands (nothing we can do there short of rewrite that class).

**Comment by cfcommando** [comment]
OK, good to know. I'll close this issue and re-open if I hit a massive snafu related to this (probably won't). Thanks again!
