### ISSUE TITLE
Don't reload image using CKNetworkImageComponent

### ISSUE THREAD

**Issue by bubblebytes** [facebook/componentkit#138]
Thank you for the amazing ComponentKit, guys!

I'm using it to create a feature similar to Facebook's newsfeed, with two images loading from network. I'm using `CKNetworkImageComponent`. I have a component loading a profile image on top and another one loading a bigger "article" image. This is the code I use to create the component:
```
static CCComponentsImageDownloader *imageDownloader = [[CCComponentsImageDownloader alloc] initWithPlaceholderPath:@"Placeholder_72"];
imageComponent = [CKNetworkImageComponent
                          newWithURL:[NSURL URLWithString:imagePath]
                          imageDownloader:imageDownloader
                          scenePath:nil
                          size:size
                          options:{.defaultImage = [UIImage imageNamed:placeholderImagePath]}
                          attributes:{
                              {@selector(setContentMode:), @(UIViewContentModeScaleAspectFill)},
                              {@selector(setClipsToBounds:), @YES},
                          }];
```
I want to update the model in some cases (increase the number of likes), and this, of course, will create an entirely new component. The problem is that the `CKNetworkImageComponent` reloads the image from the network. I just want the component to update the number of likes.

I tried to debug ComponentKit reusing `CKNetworkImageComponent`. It seems that the first time I'm updating the model, ComponentKit reuses the component from the profile image to update the bigger image and vice-versa. After I hit like again, ComponentKit reuses the corresponding component and it matches the URL, the `CKNetworkImageSpecifier` etc and it doesn't reload the image.

Also, I noticed that when I scroll just a little bit, hiding part of the post, and I hit like again, the image reloads again.

Do you understand why this is happening? Can I avoid this behaviour and just don't reload the images?

Thank you very much!
Corneliu.

**Comment by adamjernst** [comment]
Are you reusing the same image downloader every time? (Your sample code shows assigning to a static variable, but I think that wouldn't quite be legal — you'd need to use `dispatch_once` to assign to it.) If the image downloader object changes, `CKNetworkImageComponentView` will assume it needs to reload the image.

Ultimately though, the best way to deal with this is by adding an in-memory cache inside the "image downloader" object. That's how we deal with it at Facebook. For example, your cache could have an `NSMapTable` with weakly held `UIImage` objects as the values.

Hope this helps!

**Comment by bubblebytes** [comment]
Thank you, Adam. It helped me by pointing me in this direction. 

It doesn't work, in my case, to keep images weakly in the NSMapTable. They get dealloc-ed before I get a chance to reuse them. I'm not sure if I'm doing something wrong, or if it's a reusability bug. I'm keeping them with a strong reference and I'm managing the in-memory cache in the image downloader.

Thanks again!
