### ISSUE TITLE
Question -- Component with UIScrollView

### ISSUE THREAD

**Issue by mbrgm** [facebook/componentkit#139]
Hi!

I tried this several ways, but I could not find out how to put a bunch of components in a UIScrollview, i.e. I want to have a `ScrollViewComponent +newWithChild`, which can for example contain a CKStackLayoutComponent, so I can scroll when the content grows higher than the screen. Could somebody please point me in the right direction?

**Comment by mbrgm** [comment]
Changed the title to make clear it's a question.

**Comment by mbrgm** [comment]
What I have achieved so far is creating a component with an UIScrollView and set its contentSize using the selector. But I still cannot figure out how to "pre-compute" the size of the components I'd like to add to the view, so I can supply proper values to -setContentSize.

**Comment by aaronschubert0** [comment]
+1 would love to know how to do this too. Something similar to Facebook's suggested apps section on iOS in my case.

**Comment by drkibitz** [comment]
Would also like to know an answer to this question.

**Comment by adamjernst** [comment]
Sorry for the delay @mbrgm, @aaronschubert0, @drkibitz! This is a great question.

The best way to compute the content size and apply it to the scroll view is to override `mountInContext: size:children:supercomponent:`. Within that method, you can enumerate over the children and compute the union of their positions and sizes; that would be the content size.

Call `[super mountInContext:...]`; this will return a `MountContext` that has a `ViewManager` for the `UIScrollView`. You can then apply the content size using something like this:

```
const auto mountResult = [super mountInContext:...];
UIScrollView *sv = (UIScrollView *)mountResult.contextForChildren.viewManager.view;
sv.contentSize = unionOfChildRects;
return mountResult;
```

Let me know if you get stuck anywhere along the way. I'm happy to help.

**Comment by aaronschubert0** [comment]
Hey @adamjernst, thanks for your answer, I've tried out your code example and it works as you have said, I have managed to calculate the size of the children, but now when I try and access the scroll view using:
```
UIScrollView *sv = (UIScrollView *)mountResult.contextForChildren.viewManager.view;
```
I get a `CKRootView` returned and there doesn't seem to be a way to iterate through the views to get to my `UIScrollView` is there round this?

**Comment by aaronschubert0** [comment]
Found a workaround, since my `CKStackLayoutComponent` wasn't the root component that is why the `.view` wasn't a `UIScrollView` so I just created a new subclass that had `CKStackLayoutComponent` as it's root component, and now the above works.

**Comment by avnerbarr** [comment]
I'm also having a problem using this method.

The method ```mountInContext:...``` is called before any of the subviews are added. So I can't calculate the proper size required.

I hacked together a component for testing.

I see that the ```recursiveUnion``` function is called before the subviews are added to the scrollview

```
@interface SSV : UIScrollView

@end

@implementation SSV

-(void)addSubview:(UIView *)view {
    [super addSubview:view];
    NSLog(@"Added subview");
}

@end
@implementation IIOCKScrollComponent

+ (instancetype)newWithComponent:(CKComponent *)component {
    return [super newWithView:{
        [SSV class],
        {
            
        }
    }component:component];
}
- (CK::Component::MountResult)mountInContext:(const CK::Component::MountContext &)context
 size:(const CGSize)size
children:(std::shared_ptr<const std::vector<CKComponentLayoutChild>>)children
supercomponent:(CKComponent *)supercomponent {
    const auto mountResult = [super mountInContext:context size:size children:children supercomponent:supercomponent];
    UIScrollView *sv = (UIScrollView *)mountResult.contextForChildren.viewManager->view;
    CGRect rect = sv.frame;
   // there are no subviews...
    for (UIView *sub in sv.subviews) {
        rect = recursiveUnion(sub,sv,rect); // some views "stick" out of their parents - this is just a temporary hack to get the correct size of the scrollview
    }
    sv.contentSize = rect.size;
    return mountResult;
}

@end
```

**Comment by romainmenke** [comment]
Try this:
https://github.com/romainmenke/CGRectUnionWithSubviews/blob/master/CGRectUnionWithSubviews/CGRectUnionWithSubviews.swift

It will calculate a CGRectUnion of all subviews and their subviews,... It works on all subclasses of UIView and has a getter and setter.
