### ISSUE TITLE
Question - How to animate device orientation changes

### ISSUE THREAD

**Issue by leoschweizer** [facebook/componentkit#140]
First of all - thank you for this awesome project! 

I'm currently using ComponentKit heavily with `UITableViews`. Using autolayout-constraints has the nice side effect that you get a smooth animation while the screen is rotating for free. With ComponentKit, I currently do an update on each cell with the new constrained width after the rotation finished. But this is a very bad user experience, since you can first see the old layout in the new orientation (which doesn't fit of course), and then all of a sudden the layout changes to fit (Basically, I have a left-sticking, a flexible width, and a right-sticking component. I need to animate the width of the flexible component, or the x position of the right-sticking component).

How can I animate this scenario? I'm having trouble to transfer the examples from the animations documentation to this scenario. First of all, I don't have references to the subcomponents, so I can't really access properties of them. And second, when should the animation happen? If I do it in `didRotateFrom...`, it is too late, since the animation would only start after the rotation is finished. But in `willRotateTo...` it would be too early, since then the width which needs to be determined to be passed as constrained width would still be the one of the orientation which is being rotated away from.

So, how can I approach this problem?

**Comment by adamjernst** [comment]
Yep! This is a problem with the current data source implementation, but it will be addressed in the upcoming rewrite that is underway now (pull requests will start to appear shortly).

This is tracked under #15 which sounds unrelated, but is really quite related (we need a way to do synchronous operations like update the size range while also doing asynchronous operations like insertions and deletions). Follow along there :)

**Comment by palcalde** [comment]
@leoschweizer try to update the component in:

- (void)willAnimateRotationToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration 

At that point you have the new size of the rotation applied to the window and controllers, but the UI didn't update yet, so you have a chance perform changes on your components there.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by ocrickard** [comment]
This is a serious issue with ComponentKit, and something that I think we should resolve soon.

**Comment by fabiomassimo** [comment]
I'll close this because there hasn't been any activity for quite a while. 
Please make sure to update to the latest ComponentKit version and check if that solves it. If not, let us know by opening a new issue 👍
