### ISSUE TITLE
Controller.component == nil which is error

### ISSUE THREAD

**Issue by myeyesareblind** [facebook/componentkit#141]
See example https://github.com/myeyesareblind/componentkit
Update, I added failing test: CKComponentControllerTests::testThatComponentControllerExistsAfterUnmounted that demonstrates issue.

**Comment by myeyesareblind** [comment]
There is a problem with `CKComponentLifecycleManager#prepareForUpdateWithModel:`
New `CKComponentLifecycleManager::_state` is the owner of CKComponent, in this method new value is set, so old CKComponent deallocs. If the component is not attached to view, it won't update it's controller and controller will be left with nil component.

**Comment by darknoon** [comment]
When you detach it from the view, isn't it expected that the controller should deallocate, since it's not on screen anymore?

**Comment by adamjernst** [comment]
@darknoon Not really; controllers are supposed to stick around.

**Comment by adamjernst** [comment]
We're deprecating `CKComponentLifecycleManager` so I believe this should no longer happen. If it does, reopen!
