### ISSUE TITLE
Question - Get callback when changeSet has taken affect

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/componentkit#146]
Since enquedChangeSet is async, how would you be able to get notified when the enquedChangeSet has finished, so that I can call subsequent functions?

**Comment by adamjernst** [comment]
This will be a feature of the new "transactional" data source. Follow along here: 

https://github.com/facebook/componentkit/pull/147

**Comment by aaronschubert0** [comment]
Awesome!
