### ISSUE TITLE
Subtle race condition with state vs model updates

### ISSUE THREAD

**Issue by adamjernst** [facebook/componentkit#15]
It's theoretically possible for a race condition to occur if a state update occurs between two model updates. This is so rare we haven't even noticed it when using ComponentKit in Facebook's News Feed, but we should fix it.

My plan is to implement a STM-like system for computing updates to the `CKComponentLifecycleManager`'s state to resolve this issue.

**Comment by kastiglione** [comment]
:gem:

**Comment by adamjernst** [comment]
This also addresses the problem of synchronously updating the size range on rotation.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by ocrickard** [comment]
This should have been resolved by the transactional datasource, right? Let's close this.
