### ISSUE TITLE
Containers choice question

### ISSUE THREAD

**Issue by myeyesareblind** [facebook/componentkit#150]
I am experiencing poor performance when inserting a lot of items initially, the cause if it seems to be in

`CK::ArrayController::Input::Changeset::map(id<NSObject> (CK::ArrayController::IndexPath const&, objc_object<NSObject>, CKArrayControllerChangeType, bool*) block_pointer) const`
and
`CK::ArrayController::Input::Items::insert(CK::ArrayController::IndexPath const&, id<NSObject>)`

As far as I understand, the root is in data containers:
`typedef std::map<NSInteger, id<NSObject>> ItemIndexToObjectMap;`
`typedef std::map<NSInteger, ItemIndexToObjectMap> ItemsBucketizedBySection;`
Is there any way to alter those containers to boost performance? I guess all I need is to change those containers...
My data is sorted, and I don't really want to pay extra performance penalty.
Thank you for sharing this lib, I am learning a lot from it.

**Comment by adamjernst** [comment]
We're rewriting the data source right now, see #147. So I'm going to close this as that entire type will soon be deleted. Can you test with the new data source (when it lands, which will be soon) and see if it helps?
