### ISSUE TITLE
Best Way to show download progress with CNNetworkImageComponent

### ISSUE THREAD

**Issue by andyqee** [facebook/componentkit#151]
I have used the ``` CNNetworkImageComponent ```  for  network image display. <br>
I have implement ```NSObject< CKNetworkImageDownloading> ```<br>
The download protocol 
```
- (id)downloadImageWithURL:(NSURL *)URL
                 scenePath:(id)scenePath
                    caller:(id)caller
             callbackQueue:(dispatch_queue_t)callbackQueue
     downloadProgressBlock:(void (^)(CGFloat progress))downloadProgressBlock
                completion:(void (^)(CGImageRef image, NSError *error))completion;

```
And now I wanna to show the progress view while the image is downloading, but I got to find it passes the nil as the downProgressBlock ```downloadProgressBlock:nil```.  Is there any spacial purpose here?

```
- (void)_startDownloadIfNotInReusePool
{
  if (_inReusePool) {
    return;
  }

  if (_specifier.url == nil) {
    return;
  }

  __weak CKNetworkImageComponentView *weakSelf = self;
  _download = [_specifier.imageDownloader downloadImageWithURL:_specifier.url
                                                     scenePath:_specifier.scenePath
                                                        caller:self
                                                 callbackQueue:dispatch_get_main_queue()
                                         downloadProgressBlock:nil
                                                    completion:^(CGImageRef image, NSError *error)
               {
                 [weakSelf didDownloadImage:image error:error];
               }];
}
```

**Comment by adamjernst** [comment]
Ah right. That's an odd artifact of the API we're bridging to internally at Facebook.

We're not planning to support showing download progress for images in `CKNetworkImageComponent`, but you could certainly fork it, have the forked implementation pass a non-nil progress block, and do whatever you want to do with the progress callbacks.

I'm happy to help if you get stuck at any point with that. And do open source it as a separate pod so others can use it!
