### ISSUE TITLE
Highlighting UICollectionView Cell

### ISSUE THREAD

**Issue by johanrydenstam** [facebook/componentkit#152]
I've got a ```UICollectionViewCell``` with a component. When touching the cell I'd like to highlight it, and I know this can be done by altering the state of the component.

Would it be possible to highlight the component within a ```UICollectionViewCell``` with ```selectItemAtIndexPath:animated:scrollPosition```?

**Comment by benlodotcom** [comment]
Do you want to use UICollectionViewCell highlighting or just reflow your component ?

**Comment by johanrydenstam** [comment]
I wan't to reflow the component. Color it to mimic the selected state of a regular cell

**Comment by benlodotcom** [comment]
From `selectItemAtIndexPath:animated:scrollPosition` you could enqueue a changeset in your datasource with a model that specifies the selected state of your cell.
The way to do it is :
- In `selectItemAtIndexPath:animated:scrollPosition`, from the datasource grab the current model associated to the selected indexPath.
- Enqueue an update changeset for this model.

Note: You cannot use directly the selectedIndexPath to enqueue the udpate changeset, changeset processing is async and so you might already have changes in flight that might make this indexPath invalid, from the prospective of the "datasource input". (http://componentkit.org/docs/datasource-gotchas.html#the-datasource-involves-asynchronous-operations)

Note 2: Right now, the highlighting won't be synchronously done, we are working on a version of the datasource that will allow you to do sync and async changes though. This will be here very soon ! #147 to track it.
