### ISSUE TITLE
Issue with appearance events when a visible indexPath is reloaded

### ISSUE THREAD

**Issue by benlodotcom** [facebook/componentkit#153]
When reloading a cell on screen :
- The collection view first send appearance events for the newly created cell.
- It then send disappearance events for the old cell.

If appearance events are funneled directly from the collection view (`
- collectionView:willDisplayCell:forItemAtIndexPath:`, `
- collectionView:didEndDisplayingCell:forItemAtIndexPath:`) to the corresponding lifecycle manager holding the component tree, then a disappearance event will automatically be sent after the appearance event while the corresponding component is still on screen. This situation should be dealt with in the controller layer.

*TODO*
- Put an example in the sample app that shows how it can be done.
- Maybe add an object that can be used to achieve those tasks and expose the UUID associated to a lifecycle manager.

**Comment by ocrickard** [comment]
@benlodotcom is this fixed?

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by ocrickard** [comment]
Ultimately this will also be resolved by https://github.com/facebook/componentkit/pull/373. Closing this out.
