### ISSUE TITLE
Undesired side effects when using lineSpacing and maximumNumberOfLines with CKLabelComponent/CKTextComponent

### ISSUE THREAD

**Issue by sgtsquiggs** [facebook/componentkit#155]
It seems that setting ```lineSpacing``` causes an extra spacing to be added after the last line of text when using ```maximumNumberOfLines``` and a length of text that would require truncation.

Normally ```lineSpacing``` only affects spacing between lines, and not before the first line or after the last line.

In each test below, I am varying either the ```lineBreakMode``` or ```lineSpacing```. The first three have no ```lineSpacing```, while the last three do.

```TEST SIX``` has the correct zero-padding between text and edge of text container, but this is due to ```maximumNumberOfLines``` being completely ignored when using ```NSLineBreakByCharWrapping```.

![ios simulator screen shot apr 28 2015 4 43 29 pm](https://cloud.githubusercontent.com/assets/3420325/7379843/be754bdc-edc5-11e4-8947-1b1427bbc5e8.png)

In the above image:

```TEST ONE```
```objc
[CKLabelComponent
 newWithLabelAttributes:{
	  .font = [UIFont fontWithName:@"LeituraNews-Roman2" size:12],
	  .color = [UIColor blackColor],
	  .string = @"TEST ONE two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty",
	  .maximumNumberOfLines = 2
 }
 viewAttributes:{}]
```
```TEST TWO```
```objc
[CKLabelComponent
 newWithLabelAttributes:{
	  .font = [UIFont fontWithName:@"LeituraNews-Roman2" size:12],
	  .color = [UIColor blackColor],
	  .string = @"TEST TWO three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty",
	  .lineBreakMode = NSLineBreakByWordWrapping,
	  .maximumNumberOfLines = 2
 }
 viewAttributes:{}]
```
```TEST THREE```
```objc
[CKLabelComponent
 newWithLabelAttributes:{
	  .font = [UIFont fontWithName:@"LeituraNews-Roman2" size:12],
	  .color = [UIColor blackColor],
	  .string = @"TEST THREE four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty",
	  .lineBreakMode = NSLineBreakByCharWrapping,
	  .maximumNumberOfLines = 2
 }
 viewAttributes:{}]
```
```TEST FOUR```
```objc
[CKLabelComponent
 newWithLabelAttributes:{
	  .font = [UIFont fontWithName:@"LeituraNews-Roman2" size:12],
	  .color = [UIColor blackColor],
	  .lineSpacing = 5.0f,
	  .string = @"TEST FOUR five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty",
	  .maximumNumberOfLines = 2
 }
 viewAttributes:{}]
```
```TEST FIVE```
```objc
[CKLabelComponent
 newWithLabelAttributes:{
	  .font = [UIFont fontWithName:@"LeituraNews-Roman2" size:12],
	  .color = [UIColor blackColor],
	  .lineSpacing = 5.0f,
	  .string = @"TEST FIVE six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty",
	  .lineBreakMode = NSLineBreakByWordWrapping,
	  .maximumNumberOfLines = 2
 }
 viewAttributes:{}]
```
```TEST SIX```
```objc
[CKLabelComponent
 newWithLabelAttributes:{
	  .font = [UIFont fontWithName:@"LeituraNews-Roman2" size:12],
	  .color = [UIColor blackColor],
	  .lineSpacing = 5.0f,
	  .string = @"TEST SIX seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty",
	  .lineBreakMode = NSLineBreakByCharWrapping,
	  .maximumNumberOfLines = 2
 }
 viewAttributes:{}]
```

**Comment by ocrickard** [comment]
We use the default TextKit for the rendering of these, we don't do these ourselves.  If you render the same elements using UITextView do you get the same result?

**Comment by ocrickard** [comment]
Yep, looking at the logic in our sizing again, we use vanilla sizes returned by NSLayoutManager.  Suggest opening a radar?

**Comment by ocrickard** [comment]
Really we should discontinue support for NSLineBreakByCharWrapping.  When I wrote this text implementation I didn't realize just how incomplete TextKit's handling of that mode is.

**Comment by sgtsquiggs** [comment]
Text handling in iOS is a never-ending disappointment... I'll file a radar.
