### ISSUE TITLE
Best practices for animating between model changes

### ISSUE THREAD

**Issue by crylico** [facebook/componentkit#165]
Hi there!

I've had success when animating between different component states.  To give an idea of the component I'm working with, I have a component with two children: a button and an image.  When the button's pressed, the image should rotate 180 degrees with a specified animation and also update an external model.

In the button's handler, I use an implementation of Flux to let a program store know of the changes made (the direction of the model has changed).

Once the model's changed, the following happens:

    CKArrayControllerInputItems items;
    items.update([NSIndexPath indexPathForRow:i inSection:0], _models[i]);
    [_dataSource enqueueChangeset:{{}, items} constrainedSize:[_sizeRangeProvider sizeRangeForBoundingSize:self.collectionView.bounds.size]];

This works as expected (the components re-render and their appearance is valid), but there is no animation between components.

I'd appreciate any advice as to better ways to handle this!

Thanks :)

**Comment by crylico** [comment]
Oops, this seems related to #114 - looking forward to hearing about this!

**Comment by dstnbrkr** [comment]
Closing in favor of #114
