### ISSUE TITLE
Best way to react to model changes?

### ISSUE THREAD

**Issue by sgtsquiggs** [facebook/componentkit#168]
I feel like I'm missing an important part of React/ComponentKit.

I have a collection view, each item is representing a model which I am fetching at once and feeding into the datasource. Once a model is updated (via polling), how do I go about redrawing that one item? ```CKCollectionViewDataSource``` keeps the raw data insulated; I would need to loop through indexpaths to find which indexpath a model resides at.

From the docs it seems that I should have one component controller instance per model; how do I update a component from the controller?

**Comment by smiLLe** [comment]
https://github.com/facebook/componentkit/issues/149#issuecomment-95935855
either you are going to update or delete an item you should manage your models in an array, update them there and then enqueue an a change in your datasource

**Comment by adamjernst** [comment]
Yep, @smiLLe  is spot on here.
