### ISSUE TITLE
CKNetworkImageComponent doesn't provide much access to the underlying CKNetworkImageComponentView for customisation

### ISSUE THREAD

**Issue by itsthejb** [facebook/componentkit#172]
Hi all,

The normal `+[CKComponent newWithView:...]` pattern provides nice minor customisation possibilities by allowing a `UIView` subclass to be passed to the initialiser. `CKNetworkImageComponent`, on the other hand, provides no convenient access to the underlying `UIImageView` (which is `CKNetworkImageComponentView`, in fact). This is a little unfortunate since it would be nice to subclass the image view and apply effects such as fades when the `-image` is set.

It doesn't seem like it would take much to permit this: expose the interface for `CKNetworkImageComponentView`, provide a `+newWithView...` style initialiser for `CKNetworkImageComponent` and assert somewhere that the provided view class must be a subclass of `CKNetworkImageComponentView`. Unless there is some other reason why this is inadvisable? If not, I could do a PR if I have enough time...

Thanks!

**Comment by adamjernst** [comment]
Yeah, this is a fine idea; we just want to keep the core simple and avoid leaking implementation details. I'd just fork it and make your own. Consider open sourcing it so others can use it!

**Comment by itsthejb** [comment]
Ok, thanks!
