### ISSUE TITLE
Question -- Handling UIControlEvents

### ISSUE THREAD

**Issue by mbrgm** [facebook/componentkit#174]
How can I handle UIControlEvents? I.e. I want to call a handler every time the user touches down on a view (not a complete tap, but only the UIControlEventTouchDown)?

**Comment by ocrickard** [comment]
You can use a CKComponentActionAttribute with your action.  The action will propagate up the component responder chain and trigger the given method on your component.

**Comment by ocrickard** [comment]
So for example if I wanted to create a generic CKComponent that was backed by a CKButton I could do something like this:

```
          [CKComponent
            newWithView:{
              {[UIButton class]},
              {{CKComponentActionAttribute(myAction, UIControlEventTouchDown)}}
            }
            size:{}];
```

**Comment by mbrgm** [comment]
Thanks for your quick reply and sorry if this is kind of a noob question, but I get the following exception:

```
[UIView addTarget:action:forControlEvents:]: unrecognized selector sent to instance
```

My component looks like
```objc
+ (instancetype)new
{
  return [super newWithComponent:
    [CKInsetComponent
     newWithView:{
       [UIView class],
       {
         {CKComponentActionAttribute(@selector(handleFromSender:event:), UIControlEventTouchDown)}
       }
     }
...
}

- (void)handleFromSender:(CKComponent *)sender event:(UIControlEvents)event
{
  NSLog(@"event received!");
}
```

**Comment by ocrickard** [comment]
Ahh, yep vanilla UIView is not a UIControl, which is why it doesn't understand your selector.  You need to use a UIControl of some type there.

**Comment by mbrgm** [comment]
Great, thank you! :) Turned out it doesn't even have to be a UIControl subclass but can be `[UIControl class]`. I hope this does not have any side effects.
