### ISSUE TITLE
Missing indexPathForComponent: and indexPathForModel:

### ISSUE THREAD

**Issue by MarcoSero** [facebook/componentkit#183]
Unless I'm missing something, I don't think there's anything right now in `CKCollectionViewDataSource` to retrieve the indexPath of a cell given a component (or a model).
There's `-[CKCollectionViewDataSource modelForItemAtIndexPath:]` but nothing like `-[UICollectionView indexPathForCell:]` or `indexPathForModel:`.

My use case is simple: I'm using `CKComponentActionSend` to forward an action up in the responder chain to the view controller. From there, I would like to get the index path of the view associated with that component in my data source.

At the moment my (ugly) solution is navigating the tree up until I find the hosting cell. Something like this:

```objective-c
UIView *view = component.viewContext.view;
while (view && ![view isKindOfClass:UICollectionViewCell.class]) {
  view = view.superview;
}
if (!view) {
  return;
}
NSIndexPath *indexPath = [self.collectionView indexPathForCell:(UICollectionViewCell *)view];
```

Is there a better way?

**Comment by adamjernst** [comment]
Sure, this is a great point. Our data source in the base library is intentionally over-simplified. I'd recommend you fork it and add whatever you need for your own purposes; this is what we do inside Facebook.

(Also, if you can find any way to avoid getting the view controller involved, that's always ideal. There are definitely points where that's not possible, so if you're hitting one of them, help us brainstorm ways to keep the view controller out of it!)
