### ISSUE TITLE
ComponentUtilities Compile Error

### ISSUE THREAD

**Issue by iceNuts** [facebook/componentkit#188]
Hi,

I setup my project with CocoaPod and compile the sample code, it works well however for my own project, I did it in the same way, an error occurs in ComponentUtilities.h file:
```
#import <algorithm>
```
is missing.

Is there anyone could help?

Thanks.

**Comment by adamjernst** [comment]
You need to make the file that's importing it a .mm file, not a .m file.

**Comment by Bayonetta** [comment]
Thanks, I meet this problem as well. I want to import ComponentKit.h in pch file rather than import in every component files, but it looks like I can't do that way.

**Comment by psk239** [comment]
For anyone else who is having problems, I had to actually scrap my entire project and create a brand new one with a fresh Podfile and then Xcode 8.1 was able to find `#import <algorithm>` just fine
