### ISSUE TITLE
Add detailed instructions on how to install CocoaPods & slather plugin to README

### ISSUE THREAD

**Issue by modocache** [facebook/componentkit#199]
Not everyone's familiar with how to use CocoaPods, and certainly not how to install the slather plugin. I think the following should work, but we need to document it in the README:

```
$ gem update cocoapods # we should document which version supports plugins
$ gem install slather
```

Those commands may need to be run with `sudo` (lol rubygems).

**Comment by MarcoSero** [comment]
How about using a `Gemfile`?

**Comment by ocrickard** [comment]
I ran into this myself recently, we should totally add docs.

**Comment by ocrickard** [comment]
We reverted usage of Slather, so we don't need this anymore I think.

**Comment by modocache** [comment]
@MarcoSero A `Gemfile` is probably the way to go! :+1: 

@ocrickard Sounds good. Might want to open an issue if you plan on adding coverage metrics again in the future :8ball:
