### ISSUE TITLE
Wrong bounds animation in 0.12

### ISSUE THREAD

**Issue by MarcoSero** [facebook/componentkit#202]
Did anything change in version `0.12` to animate bounds change between states?

I'm overriding `boundsAnimationFromPreviousComponent:` but the frame from which the animation starts in `0.12` is wrong.

From the diff I can see that a new function `CKComponentBoundsAnimationApply` has been added. It makes me wonder whether there was a regression perhaps?

**Comment by adamjernst** [comment]
Yes, there was some refactoring in 0.12 I believe. Can you give a sample app?

**Comment by MarcoSero** [comment]
I managed to reproduce it in the Example app.
You can checkout my branch https://github.com/MarcoSero/componentkit/tree/show-issue-202

**Comment by adamjernst** [comment]
Yup, we just ran into this issue internally too. :)

**Comment by adamjernst** [comment]
Fix coming…

**Comment by MarcoSero** [comment]
:sparkles:

**Comment by MarcoSero** [comment]
When are you guys planning a new release with this fix in it?
