### ISSUE TITLE
Question: How to add a horizontal UICollectionView to a vertical UICollectionView

### ISSUE THREAD

**Issue by ThanhTurin** [facebook/componentkit#204]
Hi guys, 
When using Facebook News Feed, sometimes i see a cell which has a horizontal scroll view (like suggest pages)
How can i do this in ComponentKit? 
I have tried to use [UICollectionView class] but no result :(. 
Thanks in advance!

**Comment by smiLLe** [comment]
Depending on your content you could use an UIScrollView too. This might be much less coding.

**Comment by ThanhTurin** [comment]
Great! I have solved my problem. Thanks a lot! :+1:

**Comment by smiLLe** [comment]
For people searching for the same issue, how did you solve your problem?

**Comment by ThanhTurin** [comment]
Hix. My solution is not good! 
Follow your guide, i create a scroll view. Then i create a Component with [UIView class], and {@selector(addSubview:), scrollview}. 
But this way give me a big problem. The new sub scrollview doesn't replace the older. Like the follow picture 
![screen shot 2015-05-27 at 11 35 45 pm](https://cloud.githubusercontent.com/assets/11172462/7841825/90242f3a-04c9-11e5-95f2-d461a23e6683.png)

Next i tried to use "Advanced View" (describe on http://componentkit.org/docs/advanced-views.html). But i can't use CKComponentViewAttribute to pass properties to my sub scrollview. I don't know how to use it. Can you help me once again! :)

**Comment by majak** [comment]
Could you directly use `[UIScrollView class]` as a backing view for your component instead of adding it as subview? That way you should be able to directly set any properties you need.

**Comment by smiLLe** [comment]
Maybe it might be a stupid idea but can't you just use a horizontal CKStackLayoutComponent backed by a UIScrollView and a ComponentController where you are gonna set the .contentSize of the ScrollView after you calculated the sum width of it's subviews?

**Comment by grp** [comment]
This comment from @adamjernst  might be helpful:

https://github.com/facebook/componentkit/issues/139#issuecomment-101682623

**Comment by ThanhTurin** [comment]
@majak : Yes i did try it. This is my first idea to solve the problem. It work well, but the created component is immutable. When you scroll over the screen, it reuse the older, not replace! And how do you set properties to your new UIScrollView?

@smiLLe , @grp : My sub scrollview has a fixed size. But i want to create a UIScrollView with some arguments. In [UIImageView class], i can pass data by using {@selector(setImage:),..}. While using UIScrollView, the method addSubView doesn't work. So how can i pass data to new object! And if i can do this, can i interact each subview of UIScrollView by its tag.

**Comment by smiLLe** [comment]
Create a horizontal CKStackLayout backed by a UIScrollView. Then add components (your images) as it's children. Why do you need to -addSubview?

**Comment by aaronschubert0** [comment]
@smiLLe does that work for you or are you theorising?

**Comment by smiLLe** [comment]
Yeah just a theory. Later this day i am going to give it a try

**Comment by ThanhTurin** [comment]
@smiLLe . Sorry for my delay. I have tried your idea, but the horizontal not working. The component has 4 children but it can not be rolled.

**Comment by darknoon** [comment]
I think the way we do this is to make a component that has a collection view, then have that collection view use the CKCollectionViewDataSource as its dataSource. That way, you can scroll to additional cells without needing to know all of them in advance.

@ThanhTurin, I think what's lacking in your code here is to set the contentSize of the scrollView to the size of the children, but the frame to the exterior size. You might need to make a custom component for that, since ordinarily the stack layout will give the size to the parent.

**Comment by tranngoclinh88** [comment]
@ThanhTurin 
How about your horizontal UICollectionView? I'm also have a task related to this issue.
Did you resolved your issue?

**Comment by ThanhTurin** [comment]
@tranngoclinh88 : Sorry for my late response.
I solved this problem by this way: 
1. Create a CKStackLayoutComponent component (i call it contentComponent) and set [UIScrollView class] in block newWithView
2. In method componentTreeWillAppear (in ComponentController), i set contentSize for (UIScrollView *)self.contentComponent.viewContext.view
Hope it will help you :)

**Comment by tranngoclinh88** [comment]
@ThanhTurin :+1:

**Comment by tranngoclinh88** [comment]
Sorry @ThanhTurin .
I still can not know how to using method componentTreeWillAppear
Can you please give more detail or sample source code?

**Comment by ThanhTurin** [comment]
This is a simple horizontal component sample. You can reset contentOffset of your scrollview or anything else in Component Controller.  (https://github.com/facebook/componentkit/files/74049/SimpleHorizontalDemo.zip)

**Comment by tranngoclinh88** [comment]
@ThanhTurin Thank you so much!
