### ISSUE TITLE
Question: How to align 2 text horizontally with specific dimension and doesn't overflow

### ISSUE THREAD

**Issue by lxcid** [facebook/componentkit#205]
I have a scenario where I want to lay out 2 texts, label and value respectively.
label will take up a maximum of 30% of the total width, right aligned.
value will take up a maximum of 70% of the total width, left aligned.
Both label and value have to be fit within the total width.

Something like this:

```
+---------+---------------------+
|   label | value               |
+---------+---------------------+
```

Using solution like #62 doesn't seems to work as expected.
The text overflow (doesn't fit within the total width) and it doesn't center nor stretch as well. It looks broken.

The component is layout in collection view.

I'm on 0.12

**Comment by smiLLe** [comment]
i don't know if this is the easiest/correct way to solve your problem, but it should work 

https://gist.github.com/smiLLe/cba2d970112cde3e9a25

**Comment by lxcid** [comment]
Oh shit. that works! Thanks!

**Comment by lxcid** [comment]
One more question,

I had trouble declaring several of the label/value component as children of a vertical stack layout component. It stop taking the full width again. How would you go about doing that?

**Comment by lxcid** [comment]
Setting min and max height solve the issue. Thanks.
