### ISSUE TITLE
Question - Section Header

### ISSUE THREAD

**Issue by DrChrispoper** [facebook/componentkit#206]
Hi,

I'm trying to add section headers.
I've added my controller as CKSupplementaryViewDataSource in the CKCollectionViewDataSource.
I've conformed with the protocol by adding the "...viewForSupplementaryElementOfKind..."
But it's not being called. 
Am I missing something?

**Comment by DrChrispoper** [comment]
I wasn't setting the size of the header.

**Comment by joprice** [comment]
@DrChrispoper How did you to about this? `referenceSizeForHeaderInSection` expects a height, but this inverts the normal usage of componentkit, where the component computes height based on intrinsic height of the content and padding, margin, etc. Are you hardcoding a height for the component?
