### ISSUE TITLE
Issues with calling CKMountComponentLayout() without CKComponentLifecycleManager

### ISSUE THREAD

**Issue by darknoon** [facebook/componentkit#211]
1. Events do not fall off the components responder chain onto the UIView responder chain at the top because @property `rootComponentMountedView` is not set.

2. Components can never be unmounted because  [component unmount] is private to ComponentKit. What's the best way to manage this?

I'm going to try to tackle these these, but wanted to get them recorded in case I don't get around to it

**Comment by adamjernst** [comment]
Yep, we definitely need to fix both.

**Comment by adamjernst** [comment]
All that's left is to add some sort of `CKUnmountComponentLayout`. @benlodotcom will handle this as part of his transactional data source work I believe.

**Comment by adamjernst** [comment]
Oops.

**Comment by darknoon** [comment]
`CKUnmountComponents()` is available. I think this is mostly addressed.
