### ISSUE TITLE
Allow reversing layout ltr / rtl direction in CKStackLayoutComponent

### ISSUE THREAD

**Issue by darknoon** [facebook/componentkit#215]
Not just the order of items, but should affect spacingBefore / spacingAfter to apply to the left/right of each item.

**Comment by ocrickard** [comment]
I *believe* this would be achieved by moving to css-layout, which is something we're considering.

**Comment by ocrickard** [comment]
@gkassabli I think this belongs on your plate. Can we consider adding an API for reversing layout direction?

**Comment by gkassabli** [comment]
Will add this after moving to Yoga layout

**Comment by gkassabli** [comment]
CKFlexboxComponent supports this

**Comment by ocrickard** [comment]
So cool! Thanks @gkassabli
