### ISSUE TITLE
Missing basic examples (Where to start after getting-started)

### ISSUE THREAD

**Issue by PaulTaykalo** [facebook/componentkit#220]
Now it's really hard to dive in into componentKit, even with all that documentation and how-to's you have now  
Documentation is awesome. It explains almost every aspect of each class, but it's hard to understand where to start from.  
The only live example project has is [Wilde Guesse](http://componentkit.org/docs/getting-started.html).  
It's good example how result project can look like, but it tells nothing about how to get to this state(what decisions were made and why etc.)

Also it will be good to have some example(s) how to use componentKit when you already have project, and want to use componentKit on one of view controller's

**Comment by adamjernst** [comment]
Thanks @PaulTaykalo ! Totally agree. I'll give this some thought.

**Comment by MarcoSero** [comment]
I'm planning to open source a simple app I did where the view layer is entirely built with ComponentKit.
I hope it'll be useful for the community.
I'm also hoping to gather some feedback on best practices etc.

I agree a bit more documentation and examples would be useful, especially around:
- component controllers
- handling actions
- integrating ComponentKit in an already existing app

**Comment by DanielRakh** [comment]
Hey @MarcoSero any updates on that app? Looking to get my hands dirty with CK and contribute a nice tutorial as well once I wrap my head around CK. Any resources would be helpful : )

**Comment by markmark1** [comment]
Marco pls share this would be useful

**Comment by MarcoSero** [comment]
@DanielRakh @markmark1 I will open source it as soon as it'll be in the App Store. Unfortunately it got rejected for some weird reason https://twitter.com/marcosero/status/619565670712393728

**Comment by markmark1** [comment]
wow cool cant wait to see an actually working example of component kit

**Comment by DanielRakh** [comment]
@MarcoSero ha interesting. I'm actually building a HN Reader app too right now. Not using ComponentKit though so curious to see how it compares!

**Comment by MarcoSero** [comment]
@DanielRakh @markmark1 hey guys, now that the app is on the store I decided to open source it https://github.com/MarcoSero/HackerNews

**Comment by namsoila** [comment]
Epic! Thanks for sharing this.

**Comment by alfared** [comment]
Thanks @MarcoSero ! Really helpful example of completely using all features of ComponentKit!

**Comment by richzertuche** [comment]
I think there's still missing some basic examples, or tutorial on how to start from 0. I gave it a try and ended with almost the same as in Wilde Guesse, but not getting it clear yet.

**Comment by ocrickard** [comment]
There are now several open source apps built with component kit, in addition to our existing docs and examples. Closing this out.
