### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by MarcoSero** [facebook/componentkit#221]
It would be nice having Carthage support.
I see @kastiglione started doing some initial work for that but the [PR](https://github.com/facebook/componentkit/pull/43) didn't get merged.

**Comment by dstnbrkr** [comment]
+1 I'm hoping #216 makes Carthage support possible, but will need to investigate a bit more.

**Comment by dstnbrkr** [comment]
Decided against #216 - so @kastiglione, want to try Carthage support once more? Our pod dependency is only for test targets. ComponentKit itself can build w/o any deps.

**Comment by kastiglione** [comment]
I'd be happy to revisit the original pull request. However, I won't have the time this week.

**Comment by gsapienza** [comment]
Any news on this?

**Comment by kastiglione** [comment]
I did not follow up on this. I'm not aware of any other progress on this. @gsapienza if you have any interest in contributing support for Carthage, I'd be happy to answer questions or otherwise support this.

**Comment by conradev** [comment]
This is a dupe of #534

**Comment by eczarny** [comment]
Once the next version of ComponentKit is released we can update the README to reflect the support for Carthage.
