### ISSUE TITLE
Question: how to access properties of components

### ISSUE THREAD

**Issue by stampsrule** [facebook/componentkit#222]
If I have added a UITextField and want to do something with the text the user entered how do access the text?

**Comment by darknoon** [comment]
Ah, yes. It's a bit hard to do editable text at the moment.

As far as I can tell, you need to use a controller on a custom component and then react to mounting by adjusting the first responder, etc. You can make the controller the delegate of the textField etc.

We'd be interested in taking patches here, and I might work on some stuff to make this easier. Do you know what API specifically you'd be interested in?

**Comment by stampsrule** [comment]
Can I email you to discuss this further with you?

**Comment by stampsrule** [comment]
would the controller be a subclass of CKComponentController?
would the custom component be a subclass of CKCompositeComponent?

**Comment by darknoon** [comment]
You could email me (andrewpouliot@fb.com), but I don't check email that much and posting here would probably get more responses from the rest of the team.

Here's a snippet of what I'm doing for the first responder (yeah I have a component controller) https://gist.github.com/darknoon/f7832860f9f9d0f03f11. It's not a composite component, just directly wraps my text field. I have a custom text field class that sends actions to the component in a kind of hacky way. Again, looking to improve this, but maybe that's a start?

**Comment by stampsrule** [comment]
does the file you linked to have a header file?

I am still junior at this but I can see what I can do with what you linked to.

**Comment by darknoon** [comment]
There is more code, but it's wrapped up in the specifics of what I'm doing. You could figure out how to make a general solution.

**Comment by stampsrule** [comment]
When I have finished the textfield component and UISwitch component how do I submit them to component kit?

**Comment by adamjernst** [comment]
@stampsrule We actually try to keep the core really small, so please open source it as a separate cocoapod/repo instead! That way people can pull it in and use them.

**Comment by stampsrule** [comment]
does issue/pull 223 solve this?

**Comment by stampsrule** [comment]
yes it does, please close this

**Comment by darknoon** [comment]
@stampsrule Glad I could help :)
