### ISSUE TITLE
Question: CKLabelComponent don't break line within CKStackLayoutComponent

### ISSUE THREAD

**Issue by buithuyen** [facebook/componentkit#224]
I want to create a view with multi component. I use CKStackLayoutComponent to contains them, but I'm facing problem with label. It don't break line.

How should I do in this case?
<code>

    CKComponent *textComponent = [CKInsetComponent newWithInsets:{
        .top = 12,
        .left = 8,
        .bottom = 8,
        .right = 8
    } component:[CKLabelComponent newWithLabelAttributes:{
        .string = manegePost.content,
        .color = [IAWColor postDetailContentTextColor],
        .font = [IAWFont appFontLightWithSize:13.f],
        .lineBreakMode = NSLineBreakByWordWrapping,
    } viewAttributes:{
        { @selector(setBackgroundColor:), [UIColor clearColor] },
        { @selector(setUserInteractionEnabled:), @YES },
    }]];
    
    CKStackLayoutComponent *stackContent = [CKStackLayoutComponent newWithView:{
        [UIImageView class],
        {
            { @selector(setImage:), backgroundImage }
        }
    } size:{} style:{
        .direction = CKStackLayoutDirectionHorizontal,
    } children:{
        {.component = textComponent},
    }];
</code>

**Comment by adamjernst** [comment]
Use `flexShrink = YES` on the text component. Also make sure that it is constrained by *its* parent; for example, if it was inside a vertical stack you'd want to make sure the vertical stack used `AlignItemsStretch` so that the horizontal stack has a maximum width of the parent.

Reopen if this doesn't work!

**Comment by buithuyen** [comment]
Thanks for your help. It work for me :+1:
