### ISSUE TITLE
What about a Flux demo

### ISSUE THREAD

**Issue by keywind** [facebook/componentkit#226]
ReactJS is working well with the Flux application architecture. As ComponentKit is React inspired, I think the Flux application architecture is also a good style.

**Comment by adamjernst** [comment]
Totally! We use a Flux-like architecture inside Facebook for ComponentKit. It'd be nice to have a demo app demonstrating this. I'll try to put it on our todo list, but PRs would also be super awesome.

**Comment by stampsrule** [comment]
would the demo app just involve moving one of these  https://github.com/facebook/flux/tree/master/examples  to objective-c++ with ComponentKit?

**Comment by ocrickard** [comment]
@ryanrhee you were talking about doing this internally. Let's maybe publish a public RFC on the flux architecture in ComponentKit?

**Comment by ryanrhee** [comment]
@ocrickard sorry I missed this! Yeah, I think that'd be a good start, I'll write something up some time this month or so.

**Comment by ocrickard** [comment]
In the interests of cleaning up old tasks, I'm going through and closing anything that I think is low priority.

This task seems to be something that's been open for a long time that hasn't gotten a lot of traction. I'm closing it, but if anyone wants to take this, then feel free to re-open or open a new issue.
