### ISSUE TITLE
Question: support for UISwitch

### ISSUE THREAD

**Issue by stampsrule** [facebook/componentkit#227]
Hi I am trying to put a UISwitch in my view. I am able to place the "image" but it has no functionality, when you click on the switch it does not change.

**Comment by darknoon** [comment]
Post your code? It's a little hard to intuit exactly what you're doing from that description.

**Comment by stampsrule** [comment]
{
             [CKInsetComponent
              newWithInsets:{.top = 4, .bottom = 4}
              component:
              [CKStackLayoutComponent
               newWithView:{}
               size:{}
               style:{
                   .direction = CKStackLayoutDirectionHorizontal,
               }
               children:{
                   {
                       .component =
                       [CKComponent
                        newWithView:{
                            [UISwitch class],
                            {}
                        }
                        size:{}],
                   }
               }]]

         }

**Comment by adamjernst** [comment]
You'll need to hardcode the size to the size of a `UISwitch`; ComponentKit doesn't know what size to give it.

It is pretty gross to hardcode the size as a constant, so you could consider measuring the size of a switch at startup (by creating a `UISwitch` on the main thread somewhere and calling `sizeThatFits:` on it) and then caching that size, and using it here with `size:CKComponentSize::fromCGSize(...)`
