### ISSUE TITLE
Hard to modify input view parameters before passing to newWithView:

### ISSUE THREAD

**Issue by darknoon** [facebook/componentkit#228]
Currently, this requires annoying and inefficient constructions like making your own `CKViewComponentAttributeValueMap`, then copying in the view attributes you care about.

Something like making `CKComponentViewConfiguration` have value semantics could fix this.

```
+ (instancetype)newWithView:(CKComponentViewConfiguration)view
                      title:(NSString *)title
                       font:(NSFont *)titleFont
                 titleColor:(NSColor *)titleColor
                       size:(CKComponentSize)size;
{

  NSAttributedString *attributedTitle =
  [[NSAttributedString alloc] initWithString:title
                                  attributes:@{NSFontAttributeName : titleFont ?: [NSFont labelFontOfSize:[NSFont labelFontSize]],
                                               NSForegroundColorAttributeName : titleColor ?: [NSColor labelColor]}];

  CKViewComponentAttributeValueMap v{
    {@selector(setBordered:), @NO},
    {@selector(setAttributedTitle:), attributedTitle},
  };

  v.insert(view.attributes()->begin(), view.attributes()->end());

  CKMLabelButtonComponent *c =
  [self
   newWithView:{{[_CKMLabelButton class]},
     std::move(v),
   }
   size:{}];
   if (!c) return nil;

   c->_title = attributedTitle;

  return c;
}
```

**Comment by adamjernst** [comment]
@swolchok is the expert here. I agree it's mildly annoying as is, but with value semantics we don't have an easy way to force you to use move semantics in the case where you build up the attributes in a local variable. That may not be frequent enough to justify forcing you to do so though.

**Comment by darknoon** [comment]
What do you mean by force you to use move semantics? They should be largely transparent to users as the compiler will emit a move if you pass a movable object into another function where it is consumed, and I think it should work with initializer lists as well, but it might be worth checking.

**Comment by adamjernst** [comment]
Yeah, we'd have to check. i'm uncertain.

**Comment by ocrickard** [comment]
In the interests of cleaning up old tasks, I'm going through and closing anything that I think is low priority.

This task seems to be something that's been open for a long time that hasn't gotten a lot of traction. I'm closing it, but if anyone wants to take this, then feel free to re-open or open a new issue.
