### ISSUE TITLE
Customize NSLinkAttributeName in CKTextComponent.

### ISSUE THREAD

**Issue by tranngoclinh88** [facebook/componentkit#230]
I want to remove underline and set the text color of NSLinkAttributeName. How can I do this?

**Comment by ocrickard** [comment]
@tranngoclinh88 did you figure out what you needed here?

**Comment by tranngoclinh88** [comment]
@ocrickard 
Thank you for your support.
I found a similar question (#105) 2 days ago and tried to implement but until now, I can not understand.
Could you please give me an example removing the underline and set color for NSLinkAttributeName?
