### ISSUE TITLE
Truncation attributed string cause crash.

### ISSUE THREAD

**Issue by tranngoclinh88** [facebook/componentkit#238]
I tried to set truncation attributed string for text in it causes crash.
Here is the detail:

![screen shot 2015-06-05 at 11 25 35 am](https://cloud.githubusercontent.com/assets/1511264/8027406/d910c45a-0dc1-11e5-8167-c032b3a16b11.png)

![screen shot 2015-06-08 at 9 34 15 am](https://cloud.githubusercontent.com/assets/1511264/8027407/db1d8ada-0dc1-11e5-8922-02b98f14b978.png)

**Comment by ocrickard** [comment]
Can you please provide the code where you're configuring the truncation attributed string?

**Comment by tranngoclinh88** [comment]
Here is the code that build truncation attributed string.
![screen shot 2015-06-09 at 8 53 33 am](https://cloud.githubusercontent.com/assets/1511264/8049140/2a3d1298-0e85-11e5-9501-d3a9eef054e6.png)

Here is the code that set the truncation attributed string for CKTextComponent.
![screen shot 2015-06-09 at 8 54 05 am](https://cloud.githubusercontent.com/assets/1511264/8049141/2bf81268-0e85-11e5-9fe4-362c9c7698c5.png)

Sometimes it does not crash right after showing the collection view, it crashes while scroll up and down.

**Comment by ocrickard** [comment]
Can you please provide code for [IAWStringBuilder readMoreAttributedString]?

**Comment by ocrickard** [comment]
Can you please provide the stack trace at the crash site?  I'd like to understand where this call is coming from.

**Comment by ocrickard** [comment]
I tested this locally and can't repro the issue.  Can you try and get an isolated repro in a unit test?

**Comment by tranngoclinh88** [comment]
@ocrickard OK. I'll try.

**Comment by ocrickard** [comment]
Also, this may be an edge case with the actual string you're using here.  Can you take a screenshot of what the unit is supposed to look like when it doesn't crash?

**Comment by tranngoclinh88** [comment]
Is that right?
![screen shot 2015-06-09 at 10 08 03 am](https://cloud.githubusercontent.com/assets/1511264/8049890/7b32e6e6-0e8f-11e5-9e1e-65fb5869e47c.png)

**Comment by tranngoclinh88** [comment]
![screen shot 2015-06-09 at 10 10 15 am](https://cloud.githubusercontent.com/assets/1511264/8049922/fa754124-0e8f-11e5-9848-7bbe98e8bb5e.png)

**Comment by ocrickard** [comment]
Able to repro crash locally, will fix asap tomorrow morning.
