### ISSUE TITLE
Improve support for UITableView

### ISSUE THREAD

**Issue by benlodotcom** [facebook/componentkit#24]
It is already possible to use CKComponentDataSource directly to have a UITableView using component and we provided [some sample code]((http://componentkit.org/docs/datasource-dive-deeper.html#example-use-it-in-your-viewcontroller-to-power-a-uitableview) for it. Even though UICollectionView present a lot more advantages than UITableView (perf, animations, real abstraction for the layout ...) my plan to make things better with UITableViews is :

1. Make a sample app out of the sample code.
2. Make a thin layer on top of CKComponentDataSource (similar to CKComponentCollectionViewDataSource) to be used with UITableViews

**Comment by drkibitz** [comment]
:+1:

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mapedd** [comment]
Any update regarding this problem?

**Comment by ocrickard** [comment]
I think this is likely now a non-goal for ComponentKit. I think we should double-down on collection views, and would even like to go so far as suggesting we deprecate any TableView specific logic in the core framework.
