### ISSUE TITLE
new iOS features (compatibility)

### ISSUE THREAD

**Issue by stampsrule** [facebook/componentkit#242]
ipad's new splitview
is ComponentKit compatible with Apple's new splitview? 

should this project be moved over to using UIStackView?

should new feature requests be opened?

**Comment by adamjernst** [comment]
ComponentKit's new TransactionalComponentDataSource is a work in progress, but it will make supporting the splitview easy.

We don't plan to move to `UIStackView`; `CKStackLayoutComponent` is more efficient.

Feel free to open new feature requests!
