### ISSUE TITLE
Data detections for CKTextComponent

### ISSUE THREAD

**Issue by tranngoclinh88** [facebook/componentkit#247]
Maybe CKTextComponent missing data detections like NSTextCheckingTypeLink, NSTextCheckingTypePhoneNumber. Or can I use an other component?

**Comment by ocrickard** [comment]
You can use a NSDataDetector on your string before handing to your text component, and attribute your attributed string with the values.  http://nshipster.com/nsdatadetector/

We don't do this in the infrastructure at the moment, but could in the future via a .dataDetectors field in the rich text attribute struct.
