### ISSUE TITLE
CKButtonComponent and backend calls

### ISSUE THREAD

**Issue by charlesvinette** [facebook/componentkit#250]
Hey everyone.

I am currently working on a collectionView for an app using ComponentKit (which I love) but I must admit I have an issue that I can't seem to work around. All of my cells are Product components, containing a picture of the product, the price  bla bla bla AND a "Following" button. I can't seem to find a way to make it work.

 When I create my component, I send it the "isFollowed" bool value of the backend to show the proper icon, and it works fine. What my issue is, I want to create an action on that button that will "Unfollow" or "Follow". When I press the button, it needs to check the actual value, call the API to unfollow the product on the back end, then set isFollowed to NO so that the icon changes.

 I tried with state, found out that it is not the proper way to do it, now I have a controller. I think I am getting close, but my issue is that I can't seem to find a way to send it the isFollowed actual value. How would I actually do that?

Thanks for your time and have a good day!

**Comment by ocrickard** [comment]
First off, a little code would be helpful in answering your question specifically.

Without that, I would suggest you try providing a component action to your CKButtonComponent:

https://github.com/facebook/componentkit/blob/master/ComponentKit/Components/CKButtonComponent.h#L38

You can check out more docs here:

http://componentkit.org/docs/component-actions.html

This will allow you to have a selector called on your component or controller, which can update your value for isFollowed.

**Comment by charlesvinette** [comment]
Thanks for the help, here is a snippet of code.

The actual component(cut short to make it more readable):https://gist.github.com/charlesvinette/c7fd9776ce2189a4a49c

My issue is that I can't find a way to send the value of isFollowed to my action, so that I can call the back end in my followedButtonTapped action! If I could I would then call the backend, set the item to either follow or unfollow and the component would be recreated with the updated model.

Am I correct?

Thanks!

**Comment by charlesvinette** [comment]
Hi everyone. Even though there is not a lot of action around here, I wanted to come back and give my solution. The main issue I had came from the fact that I wasn't sending my model directly to my component constructor method, but it's properties. So whenever I was changing a property with my CKActionComponent, the actual model wasn't being updated. So the fix was pretty easy: send the model object instead of its properties to the constructor.So that's all, hopefully it can help someone else!
