### ISSUE TITLE
Question best practice: global state

### ISSUE THREAD

**Issue by smiLLe** [facebook/componentkit#262]
Lets say, everytime my application is making a http request i am going to set a global prop BOOL.
Now everytime this BOOL changes, ALL MyButtonComponents should be disabled/enabled.

My options are:
1. MyButtonComponentController which observers the global BOOL state and after it has been changed i am going to set the state of MyButtonComponent to be disabled/enabled.
2. Observer in all ViewController, enqueuing a changeset. But then all my models must have a BOOL prop, too.
3. Oversever in all ViewController, updating the datasource context. 

Am i missing some other options?

**Comment by smiLLe** [comment]
https://facebook.github.io/react/tips/communicate-between-components.html 
guess option 1 is the way to go

**Comment by adamjernst** [comment]
Yep, I think any of these options work. It's up to you.
