### ISSUE TITLE
Question: Deciding which component to display based on the available space

### ISSUE THREAD

**Issue by nickfrey** [facebook/componentkit#264]
I'm facing a situation where I would like to determine which component to display based on the available width (as constrained by a parent component). In my head, this is similar to responsive design behavior on the web. For instance, imagine a change in size class that decreases the available width. I would like display a particular component until is it no longer fits width wise, and then at that specific breakpoint swap it with a different component that's smaller.

More concretely, I have a horizontal stack layout with two components. The rightmost component has a fixed size dependent on the contents of the view and cannot shrink. If the rightmost component is larger than, say, 50% of the horizontal stack, I'd like to substitute that component for a smaller alternative.

Any advice on how I should go about this? Thanks!

**Comment by adamjernst** [comment]
Yes! This is a great question. Unfortunately, ComponentKit is fairly limiting here. Your only option is to render both components always in `+new`, then choose between them in a custom `computeLayoutThatFits:` override.

We use this method for the like/comment bar in the Facebook app.

This is quite wasteful of CPU of course. A way to render components lazily from within `-computeLayoutThatFits:` has been on our todo list for some time now; we just haven't gotten to it.

If you wanted to take a stab at implementing lazy component generation, that would be a welcome pull request. The tricky bit is the "component scope" — you have to be careful that there aren't any race conditions with generating components on different threads during layout.

**Comment by nickfrey** [comment]
Thanks for the quick response! Funnily enough, I was actually considering using the Like Comment Share toolbar as an example where this would be useful. :smile: Will try the `computeLayoutThatFits:` approach for now.
