### ISSUE TITLE
didSelectItemAtIndexPath not called

### ISSUE THREAD

**Issue by dylanslewis** [facebook/componentkit#271]
I've asked my original question here:
https://github.com/facebook/componentkit/issues/149

I have tried to create a super basic component with a view with no userInteractionEnabled, which just has a red background and a size of {100, 100}, meaning it is not a problem of another view blocking the touch.
On the ViewController which creates the component, I have implemented the method:
- (void)dataSource:(CKCollectionViewDataSource *)dataSource didSelectItemAtIndexPath:(NSIndexPath *)indexPath

However, this is never called when I tap on the component. Has anyone else had experience of this?

Thanks

**Comment by smiLLe** [comment]
```
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
{
  [_dataSource modelForItemAtIndexPath:indexPath];
}
```

**Comment by dylanslewis** [comment]
Amazing, it's working now. Strange that the CKCollectionViewDataSource method didn't work (which was recommended in the docs)...
