### ISSUE TITLE
std::hash not defined on CKComponentSize, CKComponentViewConfiguration

### ISSUE THREAD

**Issue by darknoon** [facebook/componentkit#277]
This prevents these being used in memoization. See https://github.com/facebook/componentkit/pull/269.

**Comment by darknoon** [comment]
I was attempting to do something like this:

    + (instancetype)newWithScrollView:(CKComponentViewConfiguration)scrollView
                            tableView:(CKComponentViewConfiguration)tableView
                               models:(NSArray *)modelObjects
                    componentProvider:(Class)componentProvider
                                 size:(CKComponentSize)size;
    {
      CKComponentScope s(self);

      return CKMemoize(CKMakeTupleMemoizationKey(scrollView, tableView, modelObjects, componentProvider, size), ^id{
        CKMSampleTableComponent *c =
        [self newWithView:scrollView
                     size:size];

        if (!c) return nil;

        c->_table = [CKComponent newWithView:tableView size:size];
        c->_cellProviderClass = componentProvider;
        c->_models = [modelObjects copy];
        
        return c;

      });
    }

**Comment by darknoon** [comment]
![screen shot 2015-06-29 at 11 40 58 am](https://cloud.githubusercontent.com/assets/355540/8415451/b99f783a-1e53-11e5-926d-4cd22ff37c04.png)

**Comment by ocrickard** [comment]
In the interests of cleaning up old tasks, I'm going through and closing anything that I think is low priority.

This task seems to be something that's been open for a long time that hasn't gotten a lot of traction. I'm closing it, but if anyone wants to take this, then feel free to re-open or open a new issue.
