### ISSUE TITLE
Supplementary view delegate not getting called

### ISSUE THREAD

**Issue by vishnupriya** [facebook/componentkit#281]
I have added the CKSupplementaryViewDataSource protocol and implemented the following:

     _dataSource = [[CKCollectionViewDataSource alloc] initWithCollectionView:self.collectionView
                                                     supplementaryViewDataSource:[self class]
                                                               componentProvider:[self class]
                                                                         context:nil
                                                       cellConfigurationFunction:nil];

but still the delegate method is not getting called

    - (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView
               viewForSupplementaryElementOfKind:(NSString *)kind
                                     atIndexPath:(NSIndexPath *)indexPath 

Can you please let me know if I am missing something to implement the supplementary header.

**Comment by itsthejb** [comment]
Check you aren't returning 0 for the size. If you are, this method isn't even called.

**Comment by vishnupriya** [comment]
The rows are created and it is only the section header delegate which is not called. The size is not zero.

**Comment by darknoon** [comment]
It looks like you're passing `[self class]` instead of an instance implementing the protocol. If you want to use `[self class]` you need to implement the protocol as a class method instead:

    + (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView
               viewForSupplementaryElementOfKind:(NSString *)kind
                                     atIndexPath:(NSIndexPath *)indexPath 

Or pass an instance.
