### ISSUE TITLE
Add tracking of hit rate for Component and layout memoization

### ISSUE THREAD

**Issue by darknoon** [facebook/componentkit#288]
I've been inserting some hacky logs into the places where I use `CKMemoize()` to get a hit %, but we could easily track this by class  / callsite / whatever. Requires more work for layout, so should just be able to get stats from the CKComponentMemoizer.

**Comment by ocrickard** [comment]
In the interests of cleaning up old tasks, I'm going through and closing anything that I think is low priority.

This task seems to be something that's been open for a long time that hasn't gotten a lot of traction. I'm closing it, but if anyone wants to take this, then feel free to re-open or open a new issue.
