### ISSUE TITLE
How to fire a custom event/action to parent component?

### ISSUE THREAD

**Issue by dolmens** [facebook/componentkit#291]
say i have a child component, which is a wrapper of some UIButtons, then i have an outer component to use it, in the parent, i just don't want to handle the UIButton's tap event, i need some wrapper of it, which is higher level.
how to do?

**Comment by dolmens** [comment]
oops, who can move this issue to labels/questions?

**Comment by darknoon** [comment]
Implement the first action in your component, then you can use CKComponentActionSend to your parent:

    @implementation MyComponent {
        SEL _action;
     }
     
     ....
    
    - (void)tapped:(id)sender
    {
      CKComponentActionSend(_action, self, _item);
    }

If you need more parameters sent along, you can do something like 

    id target = [self targetForAction:_action withSender:self];
    if (target) {
      [target doSomething:self withOther:firstParameter andAnother:secondParameter]...
    }

Assuming that your selector is declared in a protocol visible within `MyComponent`.
