### ISSUE TITLE
Replace CKIntegerArrayHash length parameter

### ISSUE THREAD

**Issue by darknoon** [facebook/componentkit#292]
There's no need for macros with C++ templates

**Comment by eczarny** [comment]
@darknoon can this issue be closed?

**Comment by ocrickard** [comment]
In the interests of cleaning up old tasks, I'm going through and closing anything that I think is low priority.

This task seems to be something that's been open for a long time that hasn't gotten a lot of traction. I'm closing it, but if anyone wants to take this, then feel free to re-open or open a new issue.
