### ISSUE TITLE
How to get state from a component instance?

### ISSUE THREAD

**Issue by wluxion** [facebook/componentkit#294]
I'm trying to implement the case shown in the boundsAnimationFromPreviousComponent example here:
https://github.com/facebook/componentkit/blob/gh-pages/_docs/animation.md

Specifically:
```
 if (previousComponent->_state == ArticleComponentStateCollapsed && _state == ArticleComponentStateExpanded) { ...
```

_state seems to have changed at some point, and none of the examples or docs seem to show how to access state from an instance. (The WildeGuess example only shows updateState.) Might be easy and I'm missing something, but it's non-obvious to a new user.

Thanks!

**Comment by adamjernst** [comment]
Yes, this definitely needs better docs. `_state` here is a misnomer, it's actually just an ivar on the component—not the `CKComponentScope.state` component state itself.

You can add ivars to components and set them in `+new` using this pattern:

```
+ (instancetype)newWithBar:(Bar *)bar
{
  CKFooComponent *c = [super newWith...];
  if (c) {
    c->_state = <something>;
  }
  return c;
}
```

I'll try to update the docs to make this clearer — thanks for the feedback.
