### ISSUE TITLE
Exception in CK::StaticMutex::lock()

### ISSUE THREAD

**Issue by smiLLe** [facebook/componentkit#297]
The exception occurred in my component's 
CKComponentScope scope(self);

![screen shot 2015-07-10 at 15 30 09](https://cloud.githubusercontent.com/assets/655296/8619639/e584a5a6-2718-11e5-9ed4-74daa295cc37.png)

**Comment by ocrickard** [comment]
That exception should have included a string with the exception with the error code from the pthread_mutex_t, any chance you saved it?

**Comment by ocrickard** [comment]
Basically this means that the pthread_mutex_t was unable to lock the mutex.  Common causes are:

1. Locking recursively on a non-recursive mutex.
2. Corruption of the memory in which the mutex is stored.
3. OS-level mutex exhaustion or kernel error (this occurs at a higher rate in iOS 7 than 8).

**Comment by smiLLe** [comment]
@ocrickard unforunately i don't have the exception error code.

The exception occurred right after i started to debug my app, even before the CollectionView displayed any cells . This happened in a very simple ViewController using a CKCVDataSource  and 10 models.
I can't reproduce.

Thank you for your help :)

**Comment by ocrickard** [comment]
If you ever catch it again, make sure to do a 'bt all', and inspect the state of the mutex if you can!
