### ISSUE TITLE
I am stuck with updating the model from inside a UIButton that is hosted by a [CKComponent newWithView]

### ISSUE THREAD

**Issue by MohsenElgendy** [facebook/componentkit#298]
Hey,

I have a UICollectionView that uses ComponentKit, I created the datasource and used CKArrayControllerInputItems without a problem and the componentForModel uses a model that subclasses a CKCompositeComponent and that component hosts other three components instagramAdTopBar, instagramAdImageAndDesc and InstagramAdBottomBar, the last component which the bottom bar has a like button, that button does an animation when you tab on it which required me to subclass the UIButton it self and use [CKComponent newWithView] my problem is that i change the UIButton image to another "Active" image when its tabbed and when i scroll over my collection view the other like buttons gets changed as well in the loop, which is not what i want. 

I think i am not doing it properly, I wanna know how to update the button with the new model state from inside the UIButton.

Sorry for explaining this deeply, I would appreciate it if you provide me a code example. i thought of sending the datasource along with the context but then again how ? because the datasource is not even set yet to be added to the context.

Any help ?

**Comment by ocrickard** [comment]
We really need code to be able to help here.  Please provide the pertinent snippets you're describing in your question.

**Comment by ocrickard** [comment]
Reopen once you provide code and we'll try to help!

**Comment by MohsenElgendy** [comment]
I created a quick example using xCode, Download it from this URL

https://drive.google.com/file/d/0BxJIzXNnPZMpNGxfX0I3bk15Wnc/view?usp=sharing

and try out the example.

Of course by reviewing the codes (which are simple) you will understand what i am trying to do, My problem is: Try liking the first row and scroll down (using iphone 5s) you will also find row 6 and other rows are affected by liking the first row as the value changes to "Unlike" 

Try out the demo and provide me a solution what am i doing wrong ? is there another approach for such a situation ?

Thanks.

**Comment by ocrickard** [comment]
There are many issues with your code, and your description of the problem remains fairly unclear, as you are mixing terminology.  I would urge you to read through our docs and example project again, as there are a number of things that are incorrect.  Here's my best bet for how to resolve your specific problem though:

You pass your data source down to your button view, and then propagate changes upward from your button not via the Component responder chain, but by changing mutable state on NSUserDefaults directly.  This is skipping the most powerful parts of Components, and leaves you with an unwieldy combination of patterns.  We provide the component responder chain specifically to support cases like this, please read this documentation: http://componentkit.org/docs/responder-chain.html . This will allow you to isolate your state mutation to the component itself, and then respond to your changes inside the component, issuing an update to your model object (perhaps via a state change?), and forcing a reflow through your system.

In the future, you will get a faster response if you provide simple snippets of code in-line in your question that clearly states the problem you are running into.  We try to help as much as possible, but bug hunting through your project isn't really our role.
