### ISSUE TITLE
CKTextComponent

### ISSUE THREAD

**Issue by VaruzhKhachatryan** [facebook/componentkit#302]
I have problem with big texts, stack's background view's height is wrong (short).
But in debugMode it is ok
    MyNetworkComponent * parentController = [super newWithComponent:
            [CKStackLayoutComponent newWithView:{
                [BackgroundView class],{
                    {@selector(initWithBackgroundcolor:),[UIColor colorWithRed:237.0/255.0 green:237.0/255.0 blue:237.0/255.0 alpha:1]}
                }
            }
            size:{}
            style:{}
            children:{
                {

![11748614_889791671067552_225847122_n](https://cloud.githubusercontent.com/assets/9693250/8668361/e5ad03fa-2a12-11e5-9a05-e4d47debc385.jpg)
![11749429_889791687734217_2030119714_n](https://cloud.githubusercontent.com/assets/9693250/8668362/e8d7ba84-2a12-11e5-9314-12fba8a3097c.jpg)
![11749773_889791667734219_359381402_n](https://cloud.githubusercontent.com/assets/9693250/8668366/eb8315ee-2a12-11e5-9434-9504a6eae91c.jpg)

**Comment by smiLLe** [comment]
Do you want the text to shrink or the box to grow?

**Comment by VaruzhKhachatryan** [comment]
the box is growing, but backgrwond view isn't growing enough

**Comment by VaruzhKhachatryan** [comment]
I solved it :)

**Comment by grp** [comment]
If it's easy to explain, it might be useful to explain how in case someone else runs into something similar in the future!

**Comment by VaruzhKhachatryan** [comment]
drawing in CKAsyncLayer 's 
+ (void)drawInContext:(CGContextRef)context parameters:(NSObject *)parameters{
}
