### ISSUE TITLE
cktextComponent

### ISSUE THREAD

**Issue by VaruzhKhachatryan** [facebook/componentkit#303]
The last link ("#emotions") isn't tapped

![11751189_889825414397511_65865783_n](https://cloud.githubusercontent.com/assets/9693250/8671503/4ff33598-2a2e-11e5-9634-86a0655624a9.jpg)

**Comment by grp** [comment]
Do you have sample code for how you're creating that component, and what the attributed string is? It's hard to say why without knowing exactly what's going on.

**Comment by VaruzhKhachatryan** [comment]
NSMutableAttributedString *mutableString = [[NSMutableAttributedString
                                                  alloc]
                                                 initWithString:item.title attributes:@{NSFontAttributeName : [UIFont systemFontOfSize:13.5
                                                                                                               ],
                                                                                        NSForegroundColorAttributeName : [UIColor colorWithRed:33/255.0 green:33.0/255.0 blue:33.0/255.0 alpha:1]
                                                                                        }];
    [mutableString linkifyUserNamesAndHashtags:[UIFont boldSystemFontOfSize:13.5] color:nil includeSimpleLinks:YES];

in  linkifyUserNamesAndHashtags method I'm detecting # and @(users) and adding CKTextKitEntityAttributeName

[self addAttribute:CKTextKitEntityAttributeName value:[[CKTextKitEntityAttribute alloc] initWithEntity:url] range:range];

**Comment by VaruzhKhachatryan** [comment]
CKTextComponent *textComponent = [CKTextComponent
                                                 newWithTextAttributes:{
                                                     mutableString
                                                 }
                                                 viewAttributes:{
                                                     CKComponentActionAttribute(@selector(linkTapped:withEvent:),CKUIControlEventTextViewDidTapText)
                                                 }
                                                 accessibilityContext:{}];

**Comment by VaruzhKhachatryan** [comment]
-(void)linkTapped:(CKTextComponent *)sender withEvent:(UIEvent *)event{
    CKTextComponentView *view = (CKTextComponentView*)self->textComponent.viewContext.view;
    CKTextKitRenderer *renderer = view.renderer;
    UITouch *touch = [[event allTouches] anyObject];
    CGPoint point = [touch locationInView:view];
    CKTextKitTextCheckingResult *result = (CKTextKitTextCheckingResult *)[renderer textCheckingResultAtPoint:point];
    NSLog(@"tapped at : %@",result.entityAttribute.entity);
}

**Comment by VaruzhKhachatryan** [comment]
I Have problem when links are under each other

**Comment by ocrickard** [comment]
Looks like this might be a bug.  I'll try to take a look this weekend :/

**Comment by VaruzhKhachatryan** [comment]
Ok thanks

**Comment by ocrickard** [comment]
@VaruzhKhachatryan  would you mind printing out the attributed string that is failing to highlight here?  Specifically, I'd like to see what attributes you've applied.

So, before you hand the attributed string to the CKTextComponent, just log it and paste the result here:

```
// build your attributed string in your component creation
NSLog(@"attributedString:%@", attributedString");
// pass to the text component
```

**Comment by VaruzhKhachatryan** [comment]
attributedString is :#cassone{
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc7371aaa0> font-family: \".HelveticaNeueInterface-MediumP4\"; font-weight: bold; font-style: normal; font-size: 13.50pt";
    "ck_entity" = "<CKTextKitEntityAttribute: 0x7fdc7358a380>";
} di malcesine {
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc70efb2e0> font-family: \".HelveticaNeueInterface-Regular\"; font-weight: normal; font-style: normal; font-size: 13.50pt";
}#Garda{
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc7371aaa0> font-family: \".HelveticaNeueInterface-MediumP4\"; font-weight: bold; font-style: normal; font-size: 13.50pt";
    "ck_entity" = "<CKTextKitEntityAttribute: 0x7fdc7380b220>";
} see {
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc70efb2e0> font-family: \".HelveticaNeueInterface-Regular\"; font-weight: normal; font-style: normal; font-size: 13.50pt";
}#emotions{
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc7371aaa0> font-family: \".HelveticaNeueInterface-MediumP4\"; font-weight: bold; font-style: normal; font-size: 13.50pt";
    "ck_entity" = "<CKTextKitEntityAttribute: 0x7fdc73808e60>";
}  {
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc70efb2e0> font-family: \".HelveticaNeueInterface-Regular\"; font-weight: normal; font-style: normal; font-size: 13.50pt";
}#colorful{
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc7371aaa0> font-family: \".HelveticaNeueInterface-MediumP4\"; font-weight: bold; font-style: normal; font-size: 13.50pt";
    "ck_entity" = "<CKTextKitEntityAttribute: 0x7fdc73803da0>";
}  {
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc70efb2e0> font-family: \".HelveticaNeueInterface-Regular\"; font-weight: normal; font-style: normal; font-size: 13.50pt";
}#photography{
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc7371aaa0> font-family: \".HelveticaNeueInterface-MediumP4\"; font-weight: bold; font-style: normal; font-size: 13.50pt";
    "ck_entity" = "<CKTextKitEntityAttribute: 0x7fdc73802aa0>";
}  #{
    NSColor = "UIDeviceRGBColorSpace 0.129412 0.129412 0.129412 1";
    NSFont = "<UICTFont: 0x7fdc70efb2e0> font-family: \".HelveticaNeueInterface-Regular\"; font-weight: normal; font-style: normal; font-size: 13.50pt";
}

**Comment by VaruzhKhachatryan** [comment]
![image](https://cloud.githubusercontent.com/assets/9693250/8771074/feee1848-2ec4-11e5-9276-d800e1169bd0.jpg)
"#colorful isn't pressed"

**Comment by ocrickard** [comment]
Sorry I haven't gotten around to looking into this yet! I haven't forgotten about you.  Did you find anything else out @VaruzhKhachatryan ?

**Comment by VaruzhKhachatryan** [comment]
No, have you resolved it?

**Comment by gudjao** [comment]
same problem here. hopefully someone has a solution for this.

**Comment by ocrickard** [comment]
Can you guys try again, I think I may have fixed this in https://github.com/facebook/componentkit/pull/431/commits

**Comment by ocrickard** [comment]
Actually wait, I think I can repro locally. Dont' think this is fixed, but now I can repro, should be simple to fix.

**Comment by ocrickard** [comment]
Alright, https://github.com/facebook/componentkit/pull/432 does resolve the issue for me. @VaruzhKhachatryan would you mind patching and confirming if that resolves the issue you're seeing? It does fix the issue I repro'd locally, but I want to make sure it's the same.

**Comment by gudjao** [comment]
@ocrickard great, I did some testing and it seems like #432 solved it.

**Comment by ocrickard** [comment]
Sweet! Let me know if you guys still have any issues. I don't get a ton of time to code anymore, but if you send me an email I'll be more responsive.
