### ISSUE TITLE
Asynchronous behavior of enqueueChangeset: has some limitations

### ISSUE THREAD

**Issue by MarcoSero** [facebook/componentkit#307]
The asynchronous behavior of the library is great, but at the same time makes things a little more difficult to work with.

For example, let's say we want to do some work after we have our new components rendered on screen. After refreshing the collection view with `-[CKCollectionViewDataSource enqueueChangeset:constrainedSize]` there is no way to know when the rendering actually finished.
I'm working around this by adding a simple delay. Actually, it's not even a workaround since it's not guaranteed to work.

What's the "recommended" approach to do something like this?
Would it be possible to have some kind of callback to notify when everything is done?

**Comment by adamjernst** [comment]
The new `CKTransactionalComponentDataSource` provides facilities for this via the `userInfo` dictionaries you can pass in when performing any change; it'll be passed back to you via the listener notifications when the change is completed. It also provides facilities to apply changes synchronously (use sparingly, but it can be handy).

**Comment by adamjernst** [comment]
(The collection view integration with `CKTransactionalComponentDataSource` is in progress I believe... not sure the exact status.)

**Comment by MarcoSero** [comment]
Great :star2: Thanks @adamjernst!

**Comment by ryuheechul** [comment]
@adamjernst can you tell me more about how to make a listener for the userInfo when you want to know when the asynchronous rendering is done?
