### ISSUE TITLE
Question-LayoutComponent's children how to dynamic

### ISSUE THREAD

**Issue by K-cat** [facebook/componentkit#310]
Such as CKStackLayoutComponent,If i have a images array,but this array's count is dynamic,how to add CKImageComponent dynamic depend on array count

**Comment by adamjernst** [comment]
Use `CK::map` over the images array to generate a `std::vector` of `CKStackLayoutComponentChild`.

Or, use `push_back` within a `for` loop to accomplish the same thing.

**Comment by K-cat** [comment]
Thank you
