### ISSUE TITLE
Question -- How to adjust render settings?

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/componentkit#312]
Currently in the app I'm developing after first launch, if the user scrolls fast enough then he/she will see blank space for a short period of time while the components are rendered. Is there anyway how I can fix this so that the components are always rendered before they are reached by the user?

**Comment by adamjernst** [comment]
What kind of blank space do you mean?

Normally the rows aren't even inserted into the collection view until the components have been generated, so you shouldn't see blank space.

**Comment by adamjernst** [comment]
Closing pending more info (a video screen capture?). Looking forward to the follow-up

**Comment by aaronschubert0** [comment]
Hi @adamjernst, hmm maybe I'm doing something strange!
Here's a video screen capture of the effect (Shot on iPhone 6, iOS 8.4): 
![rendering](https://cloud.githubusercontent.com/assets/9281756/8796696/9e09acd4-2f8e-11e5-8630-35668346b06b.gif)

As you can see at the bottom half of the screen there is often the background colour showing through, almost as if it still needs to render before the scroll.

**Comment by smiLLe** [comment]
I've never experienced this even though my views are very complex and i am using custom CV Layouts.
Do you insert or updates your models?

**Comment by aaronschubert0** [comment]
Hey @smiLLe I think I may know what the problem is. I'm initially inserting them with placeholder images and then kicking off a image download thread when this is complete it updates that one model which seems to be causing this behaviour. How are you handling your image loading?

**Comment by smiLLe** [comment]
@aaronschubert0  I am using the CKNetworkImageComponent and never had any problems.  I am not using a placeholder image but a background color. Do you need a image as a placeholder?

**Comment by aaronschubert0** [comment]
@smiLLe Ah that makes sense, does that also support saving the image to disk? Mainly using a placeholder to display while it loads the image & if it fails. Still wondering if that's the actual case, could that be a cause of it @adamjernst ?
