### ISSUE TITLE
[Question] Tap detection text component and UIGestureRecognizer

### ISSUE THREAD

**Issue by buithuyen** [facebook/componentkit#314]
I have text attributes, it looks like:
<img width="357" alt="screen shot 2015-07-20 at 10 29 43 pm" src="https://cloud.githubusercontent.com/assets/5087522/8779717/e0503014-2f2e-11e5-994d-a6cc0a207c7c.png">
I want to detect action when tap HighlightingText and NormalText.
Here's my approach as follow:
```objective-c
// Create text component with Tap Detection
TapDetectionTextComponent* component = [super newWithTextAttributes:attributes
                                                            viewAttributes:{
                                                                { @selector(setBackgroundColor:), [UIColor clearColor] },
                                                                CKComponentActionAttribute(@selector(didTappedComponent:withEvent:), CKUIControlEventTextViewDidTapText),
                                                                CKComponentTapGestureAttribute(@selector(didShowDetail:)),
                                                            } accessibilityContext:{}];

..................

- (void)didTappedComponent:(CKTextComponent*)component withEvent:(UIEvent*)event {
    // Handle when tap user, location...
}

- (void)didShowDetail:(CKComponent*)sender {
   // Handle when tap Normal text
}
```
But in all cases, It always implement `didShowDetail:` method.
What should I do in this case? 
How to setup UIGestureRecognizerDelegate and implement them?

**Comment by ocrickard** [comment]
Hey @buithuyen, thanks for the question.  It would appear you have an unfortunate combination of a tap gesture recognizer interfering with the standard UIControl behavior of CKTextComponentView.  However, you are in luck since you probably don't need the tap gesture with UIControls.  You can directly use something like:

```
CKComponentActionAttribute(@selector(didShowDetail:), UIControlEventTouchUpInside)
```

This should fire your didShowDetail: method when the user touches up on the text view.  Try it and let me know?

**Comment by buithuyen** [comment]
I have just did what you told me. It work fine when I touch normal text. But when I touch hightlight text, it implement both of method `didTappedComponent:withEvent:` and `didShowDetail:`
I have to use `isShowDetail` flag to ignore `didShowDetail:` as follow:
```objective-c
- (void)didTappedComponent:(CKTextComponent*)component withEvent:(UIEvent*)event {
    isShowDetail = YES;
    // Handle when tap user, location...
}

- (void)didShowDetail:(CKComponent*)sender {
    if (isShowDetail) {
        isShowDetail = NO;
        return;
    }
    // Handle when tap Normal text
}
```
It looks not good, but work fine with me. Thanks for your help!
