### ISSUE TITLE
How to remove crossfade animation during update cell?

### ISSUE THREAD

**Issue by topa51** [facebook/componentkit#315]
When I invoke

items.update([NSIndexPath indexPathForItem:index inSection:0], model);
    
    [_dataSource enqueueChangeset:{{}, items}
                  constrainedSize:[_sizeRangeProvider sizeRangeForBoundingSize:self.collectionView.bounds.size]];

My cell update it self state very well. But side effect is crossfade animation.
Is there any easy way to remove this animation and just quick update cell state?

**Comment by smiLLe** [comment]
https://github.com/facebook/componentkit/blob/master/ComponentKit/DataSources/CKCollectionViewDataSource.mm#L176

there might be missing a 
```
[UIView animateWithDuration:0 animations:^{}];
```

**Comment by adamjernst** [comment]
Yep @smiLLe is correct. Patches welcome to fix this!

**Comment by ocrickard** [comment]
Closing this since it's an issue with the legacy data sources. Check if this is still reproing in the transactional datasources, and re-file if so!
