### ISSUE TITLE
Question - How to handle UICollectionView with items of different size

### ISSUE THREAD

**Issue by leoschweizer** [facebook/componentkit#323]
I have a UICollectionView with a flow layout and I want to achieve a kind of section header effect by having components which occupy the full width of the collection view, and items which occupy only a fraction of the width (note: without actually relying on the sectioning mechanism of the UICollectionView itself).

However, I'm having trouble getting it to work. The first problem is that `enqueueChangeset` takes one "global" constrained size range for all items in the changeset. Handling different changesets for full width and part width items is nasty and I quickly gave up on that approach. So the constrained size range I use now is `{0,0}, {INFINITY, INFINITY}` and I want to constrain the component widths in the components themselves.

So I tried adding `.width` and `.maxWidth` to the `size` property of my component's root components, but that doesn't work either. Regardless of what I specify, the components now occupy the width that fits best for their child components (e.g. if there is a label longer than my `maxWidth`, the component will be wider than the `maxWidth`).

I don't really understand why this is not working as expected. So I am left wondering what might be a good approach for this scenario?

**Comment by smiLLe** [comment]
Why don't you just enqueue a changeset for your full width items and a second enqueue for your smaller items with two different constrained sizes?

**Comment by leoschweizer** [comment]
@smiLLe that was actually my initial attempt as it sounds nice in theory. However the code for that is quite ugly (since all of that is happening in a generic data source implementation which handles input array diffing and stuff, you get the idea) and what is even worse, it didn't work at all. I haven't really debugged it but I ended up with crashes and/or empty collection views.

So at least that doesn't seem to work "out of the box" without paying special attention, but I don't even know what to pay attention to.

That's why I was hoping for a cleaner approach - having a `maxSize` on components would be very clean in my opinion, but that seems to be ignored.

**Comment by leoschweizer** [comment]
@smiLLe addendum: I guess the big problem with that approach is that you can get insertions out of order, e.g. the first change set inserts items at 3,5,7 and the second changeset at 0,1,2,4,6 - I think that is what's causing the crashes.

**Comment by smiLLe** [comment]
@leoschweizer you can't insert an item at index 3 without having 0,1,2 set. this should throw an exception if i am right.

**Comment by ocrickard** [comment]
This is not well-supported at the moment. However, this should be solved by my proposal in https://github.com/ocrickard/componentkit/tree/incremental-mount which would allow you to implement a custom component layout for an entire view controller/collection view.
