### ISSUE TITLE
change CKButtonComponent title

### ISSUE THREAD

**Issue by stampsrule** [facebook/componentkit#324]
I have a CKButtonComponent that when a user clicks on brings up an UIAlertControllerStyleActionSheet, when the user selects one of the options (out of 9 choses) I want to change the CKButtonComponent title to represent that choice, I saw in the documentation ```[self updateState:^(NSNumber *oldState){}``` but I don't know if that is what I should be using and if so how it works. Either help with this specific issue would be appreciated, or since I am still Junior links to sources to read to understand how this style of framework works would also be appreciated.

**Comment by adamjernst** [comment]
Use a Component Controller: http://componentkit.org/docs/component-controllers.html

The component controller should receive the action from the `CKButtonComponent` and show the `UIAlertController`. The component controller can be the alert controller's delegate. When the user taps a button, call `[self.component updateState:...]` from the component controller to trigger the appropriate change.
