### ISSUE TITLE
Bug: advanced view of subcomponent gets remounted in random collection view cells

### ISSUE THREAD

**Issue by leoschweizer** [facebook/componentkit#327]
Note: I'm using the 0.12 release, not :head!

I have a component which creates a view according to the "advanced views" section of the docs:

```objc
static UIView *spinningActivityIndicator(void) {
	UIActivityIndicatorView *v = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
	v.tintColor = [UIColor colorWith...];
	[v startAnimating];
	return v;
}

+ (instancetype)newWithCaption:(NSString *)caption {
	
	return [super newWithComponent:[CKStackLayoutComponent
		newWithView:{}
		size:{}
		style:{
			.direction = CKStackLayoutDirectionVertical,
			.alignItems = CKStackLayoutAlignItemsCenter
		}
		children:{
			{
				[CKComponent
					newWithView:{&spinningActivityIndicator}
					size:{
						.width = 30,
						.height = 30
					}
				],
				.spacingBefore = 24
			},
			{
				[CKLabelComponent ...]
			}
		}
	]];
	
}
```

This component is used as cell in a `UICollectionView` and is present in a collection view at most once together with a lot of other items. However, when scrolling through the list, as the component containing the spinner goes off screen, other components appear and have that same spinner as subview, sometimes even in multiple cells at the same time.

My theory is that the cell is reused, but the view is not removed before that appropriately.

However, I have not yet found a 100% reliable way to reproduce this issue.

Let me know if there is anything I can do to clarify the issue, or if I am doing something wrong and this is actually working as intended.

**Comment by leoschweizer** [comment]
Note: I've "fixed" this by using a stateful view component for the spinner instead of the static view configuration. Still no idea why it occurred in the first place though...

**Comment by ocrickard** [comment]
This is similar to another bug we're looking into. Reopening for now. Leo can you give us a little more info on your data source/view controller setup?  Is it possible to provide a zip of the project?

**Comment by leoschweizer** [comment]
Unfortunately, I can't share the project where this bug actually occurs. Maybe I can find the time to build a reproducible example anytime soon...

Here's what I can tell right now:
* I have a UICollectionView with a drill-down navigation structure (so when you click an item in the collection, a detail view controller is pushed to the navigation controller)
* This collection view has two sections; in the first section, the actual list items are displayed, and the second section shows the spinner. Every time the spinner component loads, I trigger a data fetch (endless scrolling pattern).
* The bug actually occurred when drilling down and navigating back to the collection view; more often than not, the spinner would show up in one or more of the visible collection view cells even in cases were it shouldn't even be displayed anywhere in the collection view.
* Also very weird is that sometimes, multiple instances of the spinner view would show up, although at no point there should be more than one spinner displayed in the whole collection view

**Comment by majak** [comment]
Thanks for your response! Could you tell us more about the spinner? How did you set up it's animation?

**Comment by leoschweizer** [comment]
The code from the opening post of this issue is the actual code I used in the project:

```
static UIView *spinningActivityIndicator(void) {
    UIActivityIndicatorView *v = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
    v.tintColor = [UIColor colorWith...];
    [v startAnimating];
    return v;
}
```

**Comment by majak** [comment]
Ha, I forgot about this code you posted before. Great!

**Comment by ocrickard** [comment]
Since there was no resolution here, closing. We don't run into this internally. feel free to open a new issue if you're still hitting it and I promise it will be dealt with more quickly than this one was.
