### ISSUE TITLE
Question - How can I apply a layout margin in a stack component

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#332]
I'm trying to accomplish "stretch" for a component and add a layout margin with right alignment. (comparable to android linear layout)

In android it could be accomplished by

```
    <LinearLayout
        android:layout_width="match_parent"
		android:layout_height="match_parent"
        android:orientation="vertical"
        android:layout_gravity="center_horizontal"
        >
        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="20dp"
            android:textStyle="bold"
            android:fontFamily="sans-serif-light"
            android:text="1234567"
			android:padding="0dp"
            android:textColor="@android:color/black"
            android:background="#ff0000"
            android:gravity="right"
            />
    </LinearLayout>
```

I've tried various combinations but I find that the stack layout ```alignSelf``` only applies to the outer component so I am not able to align the correct component to the right.

Any ideas how I could accomplish this?

**Comment by smiLLe** [comment]
Do you want to align your component to the right, then this might help.
https://github.com/facebook/componentkit/issues/62

{
              [CKComponent new],
              .flexGrow = YES,
             },

**Comment by avnerbarr** [comment]
Actually something that could vertically align a child in a vertical layout (for instance align one child at the bottom in a vertical layout while the other is aligned top)

**Comment by grp** [comment]
I think the reference @smiLLe posted should work, since it's the same idea just in the vertical dimension vs horizontal?

**Comment by adamjernst** [comment]
Reopen if it doesn't work.
