### ISSUE TITLE
Allow CKComponentViewConfiguration to create a CALayer instead of a UIView

### ISSUE THREAD

**Issue by greghe** [facebook/componentkit#34]
It would be great if there were an option for a CKCompositeComponent to construct a CALayer hierarchy instead (or, with a bit more work, in addition to) its UIView hierarchy. CALayers are more lightweight than UIViews and more performant.

**Comment by adamjernst** [comment]
Great suggestion! You could probably accomplish this in an external (non-core) component by overriding mountInContext. Maybe this would be a good third-party component class to live in a separate repo, in the name of keeping the core small?

That said, all pull requests considered :)

**Comment by adamjernst** [comment]
@greghe I'm going to close this for now as I think this would be ideally suited to an separate Cocoapod with a component that makes it easy to instantiate layers. If you want to give it a stab that would be awesome—otherwise, hopefully someone else can soon!
