### ISSUE TITLE
Equivalent remount issue reappearing with CKCollectionViewTransactionalDataSource

### ISSUE THREAD

**Issue by itsthejb** [facebook/componentkit#342]
Hi all,

More investigations in the direction of migrating to the new data source. It appears, unless I'm mistaken, that the new data source suffers from the same issue as https://github.com/facebook/componentkit/issues/114 / https://github.com/facebook/componentkit/pull/256. 

Architecture at this end is, so far, just migrating to the API differences for `CKCollectionViewTransactionalDataSource`, so again it's a change of state to a sub-component of a parent component, triggered by enqueuing a change set with an updated item in the data source. The issue appears to be exactly the same as before:
1. willUmount received for old button component. State set to unmounting.
2. didUmount received for old button component. State set to unmounted.
3. willMount received for new button component. Since in 1 & 2 the previous component is unmounted, the state never becomes `CKComponentControllerStateRemounting`, so we won't enter the component animation stage.

The source of the issue appears to be identical to before: `CKComponentDataSourceAttachController` checks for equality on the target view, and since we always dequeue a new cell `CKCollectionViewTransactionalDataSource`, this will never be the same. I did a [quick experiment](https://github.com/facebook/componentkit/compare/master...eyeem:remount-transactional-data-source) using the same approach as https://github.com/facebook/componentkit/issues/114. However, no joy this time around; in this case `CKMountComponentLayout()` tries to mount _the same_ component, even though a newly generated component is available here as `layout`.

In any case, raising for feedback as usual :smile:

**Comment by ocrickard** [comment]
Let's try to get this fixed in the next tagged release.

**Comment by ocrickard** [comment]
I think we merged a fix again for this, right?

**Comment by itsthejb** [comment]
Hi. Yes, as far as I remember this was handled a while ago.
