### ISSUE TITLE
Allow initial state to be dependent on the model

### ISSUE THREAD

**Issue by leoschweizer** [facebook/componentkit#345]
Very often I encounter situations where I have stateful components (e.g. expand / collapse mechanisms) where I really want the initial state of the component to be dependent on the model which is passed to the component factory method.

Currently, this is not really encouraged, since  (understandably enough) the `initialState` method is static and thus doesn't have access to the model.

Thus, I often end up writing rather ugly code to figure out if the appearance of the component should be derived from the ComponentKit state or from the model (in the initial case).

Maybe I'm missing something obvious and I'm handling things more complicated than necessary. What is the recommended way to deal with these situations?

**Comment by adamjernst** [comment]
Great point. You can use the block-based "initial state creator" syntax to make your initial state dependent on the model. As you say, this is discouraged for the same reasons it's discouraged in React, but there are definitely valid cases for it.

https://github.com/facebook/componentkit/blob/master/ComponentKit/Core/Scope/CKComponentScope.h#L47

**Comment by leoschweizer** [comment]
Exactly what I needed, awesome :+1:
