### ISSUE TITLE
Error with CKCAssertPositiveReal(@"Range min height", min.height);

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#346]
I am getting a crash inside the method:
```CKCAssertPositiveReal(@"Range min height", min.height);```

Before the component is actually visible.

Is there a way to understand what "constraints" are ambiguous in the hierarchy.
(I have a stack layout in a stack layout )

**Comment by adamjernst** [comment]
Sure! In the debugger, run

```
$ po CK::Component::LayoutContext::currentStackDescription()
```

That should dump the component hierarchy leading up to the problem.

**Comment by adamjernst** [comment]
P.S. I'd welcome a pull request that adds a "troubleshooting" page with this tip — it's definitely underdocumented.

**Comment by avnerbarr** [comment]
Sure - Will try to write something substantial enough, worthy of a pull request
