### ISSUE TITLE
Question - How can I align text inside a CKTextComponent

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#349]
I want to align text to the bottom of the component (when the component size is greater than the required size)

I notice that the ```CKTextComponent``` is backed by a ```CKTextComponentView``` (a ```UIControl```)

I've tried adding the necessary properties for content alignment - but can't get the text to align accordingly:

```
CKTextComponent *tC = [CKTextComponent newWithTextAttributes:{
        .attributedString = [[NSAttributedString alloc] initWithString:@"Avner"]
    }viewAttributes:{
        {@selector(setBackgroundColor:),[UIColor redColor]},
        {@selector(setContentVerticalAlignment:),@(UIControlContentVerticalAlignmentBottom)},
        {@selector(setContentHorizontalAlignment:),@(UIControlContentHorizontalAlignmentRight)}

    }accessibilityContext:{
        
    }];

    _sizeRangeProvider = [CKComponentFlexibleSizeRangeProvider providerWithFlexibility:CKComponentSizeRangeFlexibleWidthAndHeight];
    CKComponentHostingView *hv = [[CKComponentHostingView alloc] initWithComponentProvider:[self class] sizeRangeProvider:_sizeRangeProvider context:nil];;
    hv.model = tC;
    hv.frame = CGRectMake(0, 0, 320, 600); // set a big frame

```

The result for various combinations is this:

![screen shot 2015-08-18 at 11 53 07 am](https://cloud.githubusercontent.com/assets/2404795/9326065/bb9a8170-459f-11e5-9dc3-87dde4094d71.png)

**Comment by ocrickard** [comment]
NSAttributedString specifies the alignment of your text via the NSParagraphStyle attribute:

**Comment by ocrickard** [comment]
NSAttributedString specifies the alignment of text via the NSParagraphStyle attribute:

https://developer.apple.com/library/ios/documentation/Cocoa/Reference/ApplicationKit/Classes/NSParagraphStyle_Class/

So you would add a paragraph style with your alignment setting on the attributed string and pass that into the CKTextComponent.

If you don't need the full power of an attributed string (you don't have interactive links or differential styling) then you should consider CKLabelComponent which provides a simpler API for alignment, but only works with NSStrings:

https://github.com/facebook/componentkit/blob/master/ComponentTextKit/CKLabelComponent.h#L41

**Comment by avnerbarr** [comment]
I couldnt find any vertical alignment properties on NSParagraph
Any idea what I am looking for?

**Comment by ocrickard** [comment]
Ahh!  Sorry if I misread.  Vertical alignment is not controllable in CKTextComponent.  You should use a stack layout component to position a text element vertically.
