### ISSUE TITLE
Question - Why is the hosting view component size "wrong"

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#352]
I understand from the documentation that the hosting view doesn't "resize" itself.

That being said I was curious about the sizes of its contained views.

I added a simple component with size={50,50} but I see that the component's view is "full screen"

```
- (void)viewDidLoad {
    [super viewDidLoad];
    _sizeRangeProvider = [CKComponentFlexibleSizeRangeProvider providerWithFlexibility:CKComponentSizeRangeFlexibleWidthAndHeight];
    CKComponentHostingView *hv = [[CKComponentHostingView alloc] initWithComponentProvider:[self class] sizeRangeProvider:_sizeRangeProvider context:nil];
    hv.delegate = self;
    hv.frame = self.view.bounds;
    hv.model = @"sdf";
    [self.view addSubview:hv];

}

+ (CKComponent *)componentForModel:(Model *)model context:(id<NSObject>)context {
    return [CKComponent newWithView:{
        [UIView class],
        {
            {@selector(setBackgroundColor:),[UIColor blueColor]}
        }
    }size:{.width = 50,.height = 50}];
}
```
![screen shot 2015-08-21 at 12 39 30 pm](https://cloud.githubusercontent.com/assets/2404795/9405600/b28f9688-4801-11e5-9362-73f0fff36d49.png)

So I tried adding implementation for the hosting view delegate:

```
- (void)componentHostingViewDidInvalidateSize:(CKComponentHostingView *)hostingView {
    [hostingView sizeToFit];
}
```

But still get a full blue screen

```
po [CKComponentHierarchyDebugHelper componentHierarchyDescription]
For View: <CKComponentRootView: 0x7fa753a0f830; frame = (0 0; 375 667); layer = <CALayer: 0x7fa753a11b90>>
<CKComponent: 0x7fa75387b150>, Position: {0, 0}, Size: {375, 667}
```
hosting view is resized according to ```[size sizeToFit]```

```
(lldb) po 0x7fa753a11c70
<CKComponentHostingView: 0x7fa753a11c70; frame = (0 0; 50 50); layer = <CALayer: 0x7fa753a117b0>>
```

Only when I add "hostingView.clipsToBounds = YES``` do I get the correct behavior.

What is the correct way to do this (especially for complex hierarchy and not this trivial example)?

For example:

I have an outer stack layout which has some children  (1 or more)

the first child (order not important) is another stack layout ("inner stack layout")

the second child is any sort of component (not relevant for this case)

I notice that the ***inner stack*** layout "sizes" to wrap its own children's content (which is expected)

But the outer stack layout takes the full screen (doesn't size to fit its children)

The expected behavior is that the outer layout be the minimal size to contain its children as well.

I'm curious if this a side effect of the first question?

```
+ (CKComponent *)componentForModel:(Model *)model context:(id<NSObject>)context {
    CKStackLayoutComponent *innerStack = [CKStackLayoutComponent newWithView:{
        [UIView class],
        {
            {@selector(setBackgroundColor:),[UIColor blueColor]}
        }
    } size:{} style:{
       .direction = CKStackLayoutDirectionVertical
    }children:{
        {
            .component = [CKLabelComponent newWithLabelAttributes:{
                .string = @"This is a string"
            }viewAttributes:{
                
            }]
        },
        {
            .component = [CKLabelComponent newWithLabelAttributes:{
                .string = @"This is anotherString"
            }viewAttributes:{
                
            }]
        }
        
    }];
    CKStackLayoutComponent *outerStack = [CKStackLayoutComponent newWithView:{
        [UIView class],
        {
            {@selector(setBackgroundColor:),[UIColor yellowColor]}
        }
    }size:{} style:{
        .justifyContent = CKStackLayoutJustifyContentCenter
    } children:{
        {
            .component = innerStack,
            .alignSelf = CKStackLayoutAlignSelfStretch
        }
    }];
    CKInsetComponent *inset = [CKInsetComponent newWithView:{
        [UIView class],
        {
            {@selector(setBackgroundColor:),[UIColor orangeColor]}
        }
    }insets:UIEdgeInsetsMake(20, 20, 20, 20) component:outerStack];
    return inset;
}


Thanks!
```
![screen shot 2015-08-21 at 1 00 52 pm](https://cloud.githubusercontent.com/assets/2404795/9405926/ad7214fc-4804-11e5-9a2d-4c0a7beb75ed.png)

**Comment by smiLLe** [comment]
i've never used CKComponentHostingView  but i think you should call 
[hv sizeThatFits:self.view.bounds]  // => in your case this should return 50,50 Size

**Comment by avnerbarr** [comment]
I understand that the hosting view doesn't resize itself - but the problem is that the views it contains aren't the correct size

**Comment by smalllixin** [comment]
@avnerbarr 
HostingView in 0.13 is rewritten. It also break some of my previous code. 
After some investigations I see a very simple way to fix it. 
But you have to modify one line source code to let it works.  
CKComponentHostingView.mm  line:74 ( in initWithComponentProvider method )
```objective-c
_componentNeedsUpdate = NO;
```
