### ISSUE TITLE
How to implement double tap gesture recognizer?

### ISSUE THREAD

**Issue by gudjao** [facebook/componentkit#356]
Im using this function to make a new gesture attribute, but i dont know how to access its properties. 

{CKComponentGestureAttribute([UITapGestureRecognizer class], nullptr, @selector(didTapImage))}

**Comment by adamjernst** [comment]
Use the `setupFunction` parameter to `CKComponentGestureAttribute` to pass a C function pointer. That C function should set up the tap gesture recognizer by calling `setNumberOfTapsRequired:` on it.

**Comment by gudjao** [comment]
Got it. Thank you.

**Comment by serjiogunit** [comment]
can you provide example for `setupFunction` usage
