### ISSUE TITLE
Lag issues

### ISSUE THREAD

**Issue by gudjao** [facebook/componentkit#359]
Im having lag issues when scrolling in my view collection. it seems the lag is caused by setCornerRadius.

CKComponent *pagePicture = [CKRatioLayoutComponent
                                newWithRatio:1.0
                                size:{ .width = [UIScreen mainScreen].bounds.size.width / 4 }
                                component:
                                [CKImageComponent
                                 newWithView:{
                                     [UIImageView class],
                                     {
                                         {@selector(setImage:), [UIImage imageNamed:@"cattest"]},
                                         {@selector(setClipsToBounds:), @YES},
                                         {@selector(setContentMode:), @(UIViewContentModeScaleAspectFit)},
                                         {CKComponentViewAttribute::LayerAttribute(@selector(setCornerRadius:)), @(([UIScreen mainScreen].bounds.size.width / 4) / 2)},
                                         {CKComponentViewAttribute::LayerAttribute(@selector(setBorderWidth:)), @1.0},
                                         {CKComponentViewAttribute::LayerAttribute(@selector(setBorderColor:)), (id)[UIColor grayColor].CGColor},
                                     }
                                 }
                                 size:{}
                                 ]
                                ];

**Comment by adamjernst** [comment]
Yep, corner radius is famously expensive for scrolling. Avoid it. Use an image mask or something instead if you can.

**Comment by gudjao** [comment]
oh I see. Thank you.
