### ISSUE TITLE
Transactional Data Source uses dispatch_async to apply sync updates

### ISSUE THREAD

**Issue by ocrickard** [facebook/componentkit#360]
The new transactional data source is working pretty well in one of my projects, but I recently tried to use it with a complex stateful view component... and ran into problems pretty quickly.

The stateful view component is a wrapper for a UITextView that allows dynamic sizing of text as you type.  It uses synchronous state updates to resize itself, and this worked with CKCollectionViewDataSource because UITextView appears to block `resignFirstResponder` called on subviews of UICollectionViewCell or UITableViewCell in reloads when they occur within the scope of a keypress.

Now with the transactional datasource, even if I make the update synchronous, it applies "asynchronously" (in time, but still on the main thread) due to this line:

https://github.com/facebook/componentkit/blob/4446a1d3250ced69b66956da053a31baa206b943/ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSource.mm#L138

Ideas?  Any way to block this behavior?  I already have a system for asynchronous state updates so I can maintain my editing position even if this occurs, but the experience is kinda weird because the cursor goes away temporarily.

**Comment by adamjernst** [comment]
Yup, tricky one. Applying them *truly* synchronously caused other problems—the responder chain would go away right after calling `updateState:` which isn't really desirable either.

**Comment by ocrickard** [comment]
Got it. I built a workaround but boy is it ugly...

1. Subclass UICollectionView.
2. Provide a new delegate that notifies before/after it begins a collection view mutation (since the data sources don't provide this message).
3. Create an update monitor single responsibility object that just listens for these messages and updates an _isMutatingCollectionView flag.
4. Pass this update monitor object down to the owner of the stateful view component.
5. In the wrapper for the stateful view component we provide a configuration block to determine if it should restore its editing status on `textViewDidEndEditing:` calls.  In this block we check the update monitor to see if an update is ongoing.
6. If that block returns YES to shouldRestoreEditingOnRemount, we store our first responder status, and our editing position.
7. Weirdly didRemount isn't called in this case, I haven't gotten to the bottom of why it isn't, but we DO get didUpdateComponent callback in the stateful view's component controller.
8. We check if the text view `canBecomeFirstResponder`.  If YES, then we can immediately apply our previous editing state.  If NO, then we actually have to dispatch_async on the main thread to wait a runloop turn before re-applying.  In practice this second case causes some pretty major problems for editing since the autocompletion, capitalization, and spelling state is lost.  In practice this means that you may be expecting it to autocomplete for you, but then it doesn't.  It also inserts random capital letters depending on your keyboard configuration.

Overall this approach does work, but it's a hell of a lot of work and creates a pretty broken experience.  Ultimately the fault is with UICollectionView, so last night I wrote a simpler list view with recyclable cells that always prefers re-using the same view with the same index, and this works very well with the transactional data source, whether sync or async.
