### ISSUE TITLE
Question: CKNetworkImageDownloading delegate

### ISSUE THREAD

**Issue by allurco** [facebook/componentkit#365]
After I added the delegate to my component:

```@interface PostTopComponent : CKCompositeComponent <CKNetworkImageDownloading>```

I don't know how to call it in a CKNetworkImageComponent. Is there any documentation about that?

Thanks

**Comment by adamjernst** [comment]
CKNetworkImageDownloading should be adopted by some other class, not a component.

For example, you might have a singleton instance that conforms to the protocol and implements it by using `NSURLSession`.
