### ISSUE TITLE
When children vector is empty, don't allocate a vector

### ISSUE THREAD

**Issue by darknoon** [facebook/componentkit#367]
Wasteful to do `children(new std::vector<CKComponentLayoutChild>(std::move(ch)), CKOffMainThreadDeleter())` when you're just going to pass {}

**Comment by adamjernst** [comment]
Yup. Good find.

**Comment by darknoon** [comment]
Ok, but why did you close it?

**Comment by ocrickard** [comment]
In the interests of cleaning up old tasks, I'm going through and closing anything that I think is low priority.

This task seems to be something that's been open for a long time that hasn't gotten a lot of traction. I'm closing it, but if anyone wants to take this, then feel free to re-open or open a new issue.
