### ISSUE TITLE
CKStackLayoutComponent specialized children type to avoid push_back

### ISSUE THREAD

**Issue by kastiglione** [facebook/componentkit#368]
Instead of having stack layouts take a `vector<CKStackLayoutComponentChild>`, what if Components introduced a wrapper type that provided overloaded constructors for convenience. The motivating case I have in mind is for [avoiding push_back](http://componentkit.org/docs/avoid-push-back.html).

Consider a stack of: collection, divider, and footer. Perhaps the collection was built using `CK::map`. It would typically be non-`const` so that the divider and footer can be appended using `push_back`. With a new type, there could be a convenience constructor of `vector<vector<CKStackLayoutComponentChild>>`.

```objc++
[CKStackLayoutComponent
  newWithView:{}
  size:{}
  style:{}
  children:{
    collection,
    {divider},
    {footer},
  }];
```

This basically affords an implicit "flatten" or "concatenate" operator.

**Comment by darknoon** [comment]
I think something like this is even more pressing for the view configuration, since you're likely to want to take some in and append your component-specific parts.

**Comment by adamjernst** [comment]
Neat, and definitely something that crops up often. Just two concerns:

# I think this might confuse the `{}` initialization syntax. Adding overloads would make it ambiguous.
# Shouldn't this just be some sort of utility to concatenate vectors? `CK::concat` maybe.

**Comment by kastiglione** [comment]
> \2. Shouldn't this just be some sort of utility to concatenate vectors? CK::concat maybe.

That's the other (and perhaps better) way to do this. I thought it would be nice to have the conversion "for free" (i.e. implicit), but if that going to make for tricky/finicky C++, then ya nah.

I'll give this approach a try in and see how it works for existing code.

**Comment by kastiglione** [comment]
> I think something like this is even more pressing for the view configuration, since you're likely to want to take some in and append your component-specific parts.

@darknoon Do you mean combining a passed in `CKViewComponentAttributeValueMap` value with additional internal/local attributes?

**Comment by kastiglione** [comment]
I putzed around with implementing a generic `CK::concat` yesterday. I hit complexity around the interaction of template type deduction, initializer lists, and vectors. Not sure if what I'm imagining is doable.

**Comment by adamjernst** [comment]
Closing unless we decide it's doable.

**Comment by kastiglione** [comment]
:ok_hand:
