### ISSUE TITLE
Video player in components

### ISSUE THREAD

**Issue by gudjao** [facebook/componentkit#369]
Is there an example on how to implement placing video players in components? I tried subclassing but doesnt work. any tips/guide or example for this. thanks.

**Comment by adamjernst** [comment]
Use a `CKStatefulViewComponent` that wraps a view with an `AVPlayerLayer`. That will allow you to avoid losing the layer when components recycles views.

**Comment by gudjao** [comment]
Hi @adamjernst , quick question. For example, I'm using another library that plays video instead of the native AVPlayer. is this code below right? calling init?

+ (UIView *)newStatefulView:(id)context
 {
    VKVideoPlayer *player = [[VKVideoPlayer alloc] initWithVideoPlayerView:[[VKVideoPlayerView alloc] init]];
    [player loadVideoWithStreamURL:[NSURL URLWithString:@"http://content.viki.com/test_ios/ios_240.m3u8"]];
    player.state = VKVideoPlayerStateContentPaused;
return player.view;
}

**Comment by psk239** [comment]
@gudjao Have you had luck pulling this off? I've been trying to wrap a `CKStatefulViewComponent` with a `AVPlayerLayer` but I can't figure out how to trigger play/pause if the user taps on the `view`
