### ISSUE TITLE
CKCollectionViewTransactionalDataSource sizeRange

### ISSUE THREAD

**Issue by smiLLe** [facebook/componentkit#370]
Hey guys,

the sizeRange in CKCollectionViewTransactionalDataSource must be set during initialization. Compared to CKCollectionViewDataSource i had to set the sizeRange on each -enqueue.. which gave me the option to have different sizes for different cells.
Imagine a layout with a top cell of 100% width and all following cells have a pinterest like layout (width / 2.0).
How am i supposed to do this with the new CKCollectionViewTransactionalDataSource? Am i missing something?

Thanks

**Comment by adamjernst** [comment]
Yes, this was an intentional change.

Pass in a size range as part of the model object for each item, then intersect that with the overall per-data-source size range. (Easy to do if you override `computeLayoutThatFits:`.)

For example:

```
@interface PNItemModel : NSObject
@property (nonatomic, strong, readonly) PNItem *item;
@property (nonatomic, readonly) CKSizeRange sizeRange;
@end
```

**Comment by smiLLe** [comment]
Thanks, that's excatly what i am doing right now :)
