### ISSUE TITLE
Event when UIViewCollection will finish inserting cells.

### ISSUE THREAD

**Issue by topa51** [facebook/componentkit#375]
I neet to know, when UIViewCollection will finish inserting cells.
I found in CKCollectionViewDataSource.mm this sniped of code

#pragma mark - CKComponentDatasourceDelegate

- (void)componentDataSource:(CKComponentDataSource *)componentDataSource
          hasChangesOfTypes:(CKComponentDataSourceChangeType)changeTypes
        changesetApplicator:(ck_changeset_applicator_t)changesetApplicator
{
  [_collectionView performBatchUpdates:^{
    const auto &changeset = changesetApplicator();
    applyChangesetToCollectionView(changeset, _collectionView);
  } completion:nil];
}

The question is, why completion block is nil?
The class is final, so I can't override this method. 
2nd question it is possible to catch the moment when cells in UIViewCollection are insert?

**Comment by adamjernst** [comment]
I'm not sure — it depends on subtle details of integrating with `UICollectionView`. If you can investigate and find out, then report back here, that would be awesome!
