### ISSUE TITLE
Showing keyboard lagging?

### ISSUE THREAD

**Issue by gudjao** [facebook/componentkit#376]
Im placing this in my UICollectionViewController. is this a safe way?

- (void)loadView {
    UICollectionViewFlowLayout *flowLayout = [[UICollectionViewFlowLayout alloc] init];
    flowLayout.scrollDirection = UICollectionViewScrollDirectionVertical;
    flowLayout.minimumLineSpacing = 0.0f;
    
    self.collectionView = [[PGKeyboardCollectionView alloc] initWithFrame:[UIScreen mainScreen].bounds collectionViewLayout:flowLayout];
    self.collectionView.backgroundColor = [UIColor whiteColor];
    [self.collectionView becomeFirstResponder];
    
    ((PGKeyboardCollectionView *)self.collectionView).keyboardBarDelegate = self;
}

**Comment by darknoon** [comment]
What does this have to do with ComponentKit? I don't see any code that references components. If you have bugs with UIKit, use http://bugreport.apple.com
