### ISSUE TITLE
Publish Podspec for 0.13

### ISSUE THREAD

**Issue by leoschweizer** [facebook/componentkit#378]
The readme suggests to use `pod 'ComponentKit', '~> 0.13'` which does not work at all - the last published Podspec is for 0.12.

Please push an update to CocoaPods Specs trunk.

**Comment by modocache** [comment]
I believe the only problem here is that ComponentKit v0.13's podspec isn't pushed to CocoaPods trunk.

@adamjernst, can you pull down master and run `pod trunk push --allow-warnings` (run `pod lib lint` to see the warnings we're ignoring)? Alternatively, could you add @MDSilber and I to the pod owners? `pod trunk info ComponentKit` shows:

```
$ pod trunk info ComponentKit

ComponentKit
    - Versions:
      - 0.10 (2015-04-09 22:09:16 UTC)
      - 0.11 (2015-04-23 16:29:57 UTC)
      - 0.12 (2015-05-14 19:04:34 UTC)
      - 0.9 (2015-03-25 22:10:32 UTC)
    - Owners:
      - Adam Ernst <adamjernst@fb.com>
      - Facebook, Inc. <cocoapods@fb.com>
```

I was hoping that registering `cocoapods@fb.com` as a verified owner would have allowed @MDSilber and I to push somehow, but that doesn't appear to be the case.

**Comment by modocache** [comment]
Here are the warnings: 

```
$ pod lib lint

 -> ComponentKit (0.14)
    - WARN  |  /Users/modocache/GitHub/facebook/componentkit/ComponentKit/Core/CKComponent.mm:213:15: warning: unused variable 'resolvedRange' [-Wunused-variable]
    - WARN  |  /Users/modocache/GitHub/facebook/componentkit/ComponentKit/Utilities/CKComponentAction.mm:22:18: warning: function '_debugResponderChain' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    - WARN  |  /Users/modocache/GitHub/facebook/componentkit/ComponentKit/Core/CKComponentController.mm:37:18: warning: unused function 'componentStateName' [-Wunused-function]
    - WARN  |  /Users/modocache/GitHub/facebook/componentkit/ComponentKit/Core/Scope/CKComponentScopeFrame.mm:78:14: warning: unused variable 'result' [-Wunused-variable]
```

1. `CKComponent.mm:213` uses `resolvedRange`, but only within an assert. Should we add a `#pragma unused` to prevent this warning?
2. Similarly, `CKComponentAction.mm` uses `_debugResponderChain` within an assert as well.
3. And sure enough, `componentStateName` is used at several callsites, but all of them are within asserts.
4. In `CKComponentScopeFrame.mm`, `result` is used within... well, you get the idea. :wink:

Is it worth trying to silence these warnings?

**Comment by adamjernst** [comment]
Pushed.
