### ISSUE TITLE
Question about best practice when building multiple children

### ISSUE THREAD

**Issue by foulkesjohn** [facebook/componentkit#38]
I have a component which will be used in a collectionview. This component in turn can be built up with many other components so I have a CKStackLayoutComponent which I want to insert multiple children. The number of children will be dynamic (in reality no more than 4), what is the best way to build these up and pass to the children of a CKStackLayoutComponent?

**Comment by natansh** [comment]
The best way to add a dynamic number of children is to build up a `std::vector` of `CKStackLayoutComponentChild` using methods like `push_back`.

```objc++
std::vector<CKStackLayoutComponentChild> children = {};
for (ModelType *model in models) {
  // Create component from model, let's say the name of the component you create is childComponent.
  children.push_back(childComponent);
}
```
 
And then you can pass in the children directly to `CKStackLayoutComponent`.

If you already know the exact number beforehand, I would suggest you just create the children inline with `CKStackLayoutComponent`.

**Comment by ocrickard** [comment]
If your children are **truly** dynamic then you can do push_back, but as Natansh hints at: it's rare that's the case.

Check out http://componentkit.org/docs/avoid-push-back.html

**Comment by adamjernst** [comment]
One last tip: `FB::map` is a great helper. See `ComponentUtilities.h`.

**Comment by foulkesjohn** [comment]
Thanks, this is exactly what I was after.
