### ISSUE TITLE
UICollectionView orientation change - the behavior of the UICollectionViewFlowLayout is not defined

### ISSUE THREAD

**Issue by leoschweizer** [facebook/componentkit#385]
I have a UICollectionView which should respond to device orientation changes, so in the absence of a better solution I do the following:

```
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator {
    [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
    // to call invalidateLayout was a proposed workaround for the issue, but it doesn't really help
    [self.collectionView.collectionViewLayout invalidateLayout];
    [coordinator animateAlongsideTransition:nil completion:^(id<UIViewControllerTransitionCoordinatorContext> context) {
        [self enqueueUpdateAll];
    }];
}
```

whereby `enqueueUpdateAll` basically enqueues a changeset with an update for each item in the collection view.

Now the problem is: when rotating from landscape to portrait, I get the following console output on iOS 8 and 9:

```
the behavior of the UICollectionViewFlowLayout is not defined because:
2015-09-24 14:01:29.845 the item width must be less than the width of the UICollectionView 
minus the section insets left and right values, minus the content insets left and right values.
...
```

I've double-checked all insets (section and content) and item sizes - everything is correct. The item size I enqueue for the changeset is correct. Still, I get this annoying warnings.

I'm not sure if this is a bug in ComponentKit. Has anyone encountered this problem, and how can I fix it?

**Comment by adamjernst** [comment]
Yup I'm hitting this too. Investigating.

**Comment by bartl-git** [comment]
Have the same issue. Did anyone find a solution? Thanks.

**Comment by ocrickard** [comment]
In the interests of cleaning up old tasks, I'm going through and closing anything that I think is low priority.

This task seems to be something that's been open for a long time that hasn't gotten a lot of traction. I'm closing it, but if anyone wants to take this, then feel free to re-open or open a new issue.
