### ISSUE TITLE
Questions about CKNetworkImageDownloading implementation

### ISSUE THREAD

**Issue by allurco** [facebook/componentkit#393]
Hi,

I have a couple of questions about CKNetworkImageDownloading delegate, I have created my class and added the required methods. But I am not sure what to do with:
```-(id) downloadImageWithURL:(NSURL *)URL scenePath:(id)scenePath caller:(id)caller callbackQueue:(dispatch_queue_t)callbackQueue downloadProgressBlock:(void (^)(CGFloat))downloadProgressBlock completion:(void (^)(CGImageRef, NSError *))completion ```

Does it take care of the downloading process or do I have to download the image myself?
What is the scenePath? Is it the context?

I am really trying to learn this and all the help would be great!
Thanks

**Comment by adamjernst** [comment]
You have to take care of downloading the image yourself (e.g. via `NSURLSession`). Scene path is an arbitrary object you can pass into the `CKNetworkImageComponent`; at Facebook we use it for request prioritization, you can feel free to ignore it and pass nil.

**Comment by allurco** [comment]
Thanks!
