### ISSUE TITLE
Overlapping components in a CKStackLayoutDirectionVertical

### ISSUE THREAD

**Issue by JoseBluenet** [facebook/componentkit#399]
I'm trying to setup a simple case of multiple images stacked in a CKStackLayoutDirectionVertical.

I've been trying many possible combinations but still I'm not able to see one image after the other. In the current code one image is overlapping the next image.

I tried even adding an additional component with .flexGrow before and after the image but nothing. 

Not sure what I'm missing. Can somebody point me in the right direction?
(This should be a simple question for somebody experience in componentkit)

##### Overlapping CKImageComponent components
<img width="378" alt="issue-componentkit" src="https://cloud.githubusercontent.com/assets/13038624/10380849/b76d2ebe-6e16-11e5-8d6c-3eaace3c5d96.png">

##### UICollectionViewController enqueue changeset:
```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];
    ...
}

- (void)_enqueuePage:(TestPage *) testPage
{
	...
    _sizeRangeProvider = [CKComponentFlexibleSizeRangeProvider providerWithFlexibility:CKComponentSizeRangeFlexibleHeight];
    
     [_dataSource enqueueChangeset:{{}, items}
                  constrainedSize:[_sizeRangeProvider sizeRangeForBoundingSize:self.collectionView.bounds.size]];
}

#pragma mark - CKComponentProvider

+ (CKComponent *)componentForModel:(TestModel *)testObject context:(TestContext *)context
{
    return [TestComponent newWithObject:testObject context:context];
}
```
##### TestComponent Code
```objective-c
@implementation TestComponent

+ (instancetype)newWithObject:(TestModel *)testObject
                    context:(TestContext *)context
{

    return [super
            newWithComponent:
            [CKStackLayoutComponent
             newWithView:{}
             size:{
             }
             style:{
                 .direction = CKStackLayoutDirectionVertical,
                 .alignItems = CKStackLayoutAlignItemsCenter
             }
             children:{
                 {
                     [CKComponent new],
                     .flexGrow = YES,
                 },
                 {
                     [CKImageComponent newWithImage:[UIImage imageNamed:@"test-image"]],
                     .alignSelf = CKStackLayoutAlignSelfStretch,
                     .flexGrow = YES,
                     //.flexShrink = YES,
                     //.flexBasis = CKRelativeDimension::Auto()
                 },
                 {
                     [CKComponent new],
                     .flexGrow = YES,
                 }
             }]];
}
            
@end
```

**Comment by adamjernst** [comment]
Good question. I'd breakpoint in `computeLayoutThatFits:` and report back the size ranges that are being passed to each component. I'd especially be interested in the size ranges the image components receive.

Could you do that and reopen?

**Comment by JoseBluenet** [comment]
Hi Adam,

If you look at the current picture from the Debug, the one that is giving the high for the cell is CKCollectionViewDataSourceCell. The other children (UIView and CKComponentRootView) are taking the same size as the parent.

The CKCollectionViewDataSourceCell is for some reason not resizing itself by the UIImageView child.

How can I make the CKCollectionViewDataSourceCell to resize properly or to put fix high?

<img width="702" alt="screenshot-issue" src="https://cloud.githubusercontent.com/assets/13038624/10406988/47108f10-6ee5-11e5-94ad-6acf0ca7bd0e.png">

<img width="305" alt="screenshot-issue2" src="https://cloud.githubusercontent.com/assets/13038624/10407028/fa5d176e-6ee5-11e5-98a7-addd952d3cf6.png">

Thanks,
Jose

**Comment by JoseBluenet** [comment]
Hi Adam,
It seems that I cannot re-open the issue as it was closed by a repository contributor.
I have created issue 403 with additional information.
https://github.com/facebook/componentkit/issues/403

Thanks,
Jose

**Comment by ocrickard** [comment]
Seems this was answered in #403
