### ISSUE TITLE
Conceptual - ComponentKit for general use?

### ISSUE THREAD

**Issue by mrjjwright** [facebook/componentkit#4]
There is this section in the docs:

`Interfaces that aren't lists or tables aren't ideally suited to ComponentKit since it is optimized to work well with a UICollectionView.`

That was a bit surprising and I guess it means that ComponentKit was designed for the NewsFeed and other feeds within Facebook.  That being said, does that mean you all use the normal imperative, mutative iOS APIs for other parts of the FB app or some other technology that isn't open sourced?  Is ComponentKit not suited for just laying out a simple UIView e.g.?

**Comment by natansh** [comment]
@mrjjwright Check out `CKComponentHostingView` to use it in a standalone context. The point is that the framework is *optimized* for a `UICollectionView`, but it still can be used in other contexts.

**Comment by mrjjwright** [comment]
Thanks, that part all makes sense now after a little more time with the framework.
