### ISSUE TITLE
CKNetworkImageComponentOptions Documentation

### ISSUE THREAD

**Issue by allurco** [facebook/componentkit#401]
Hi,

Is there any documentation on CKNetworkImageComponentOptions? I could not find it.

**Comment by adamjernst** [comment]
Each option within the struct has documentation:

https://github.com/facebook/componentkit/blob/42e7edb7fa1afb9ac951d97786c1d52f64b337b0/ComponentKit/Components/CKNetworkImageComponent.h#L14

**Comment by allurco** [comment]
Thank you for point that out.
