### ISSUE TITLE
CKCollectionViewDataSourceCell is not calculating the high of the children (CKImageComponent)

### ISSUE THREAD

**Issue by JoseBluenet** [facebook/componentkit#403]
I'm trying to setup a simple case of multiple images stacked in a CKStackLayoutDirectionVertical.

I've been trying many possible combinations but still I'm not able to see one image after the other. In the current code one image is overlapping the next image.

If you look at the current picture from the Debug, the one that is giving the high for the cell is CKCollectionViewDataSourceCell. The other children (UIView and CKComponentRootView) are taking the same size as the parent.

The CKCollectionViewDataSourceCell is for some reason not resizing itself by the UIImageView child.

How can I make the CKCollectionViewDataSourceCell to resize properly or to put fix high?

Not sure what I'm missing. Can somebody point me in the right direction?
(This should be a simple question for somebody experience in componentkit)

##### Overlapping CKImageComponent components
<img width="702" alt="screenshot-issue" src="https://cloud.githubusercontent.com/assets/13038624/10406988/47108f10-6ee5-11e5-94ad-6acf0ca7bd0e.png">
##### Overlapping CKImageComponent components (even adding CKLabelComponent on top of the CKImageComponent)
<img width="563" alt="screenshot-issue3" src="https://cloud.githubusercontent.com/assets/13038624/10407254/c20d5a88-6ee8-11e5-816b-54cc995e4964.png">

##### Overlapping CKImageComponent components
<img width="378" alt="issue-componentkit" src="https://cloud.githubusercontent.com/assets/13038624/10380849/b76d2ebe-6e16-11e5-8d6c-3eaace3c5d96.png">

##### UICollectionViewController enqueue changeset:
```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];
    ...
}

- (void)_enqueuePage:(TestPage *) testPage
{
	...
    _sizeRangeProvider = [CKComponentFlexibleSizeRangeProvider providerWithFlexibility:CKComponentSizeRangeFlexibleHeight];
    
     [_dataSource enqueueChangeset:{{}, items}
                  constrainedSize:[_sizeRangeProvider sizeRangeForBoundingSize:self.collectionView.bounds.size]];
}

#pragma mark - CKComponentProvider

+ (CKComponent *)componentForModel:(TestModel *)testObject context:(TestContext *)context
{
    return [TestComponent newWithObject:testObject context:context];
}
```
##### TestComponent Code
```objective-c
@implementation TestComponent

+ (instancetype)newWithObject:(TestModel *)testObject
                    context:(TestContext *)context
{

    return [super
            newWithComponent:
            [CKStackLayoutComponent
             newWithView:{}
             size:{
             }
             style:{
                 .direction = CKStackLayoutDirectionVertical,
                 .alignItems = CKStackLayoutAlignItemsCenter
             }
             children:{
                 {
                     [CKComponent new],
                     .flexGrow = YES,
                 },
                 {
                     [CKImageComponent newWithImage:[UIImage imageNamed:@"test-image"]],
                     .alignSelf = CKStackLayoutAlignSelfStretch,
                     .flexGrow = YES,
                     //.flexShrink = YES,
                     //.flexBasis = CKRelativeDimension::Auto()
                 },
                 {
                     [CKComponent new],
                     .flexGrow = YES,
                 }
             }]];
}
            
@end
```

**Comment by adamjernst** [comment]
You don't want `sizeRangeForBoundingSize:self.collectionView.bounds.size`. That will limit the height of each cell to the height of the collection view, which I think is not what you want. Use a size range with an infinite potential height.
