### ISSUE TITLE
Question: Multiple CKComponentGestureAttribute

### ISSUE THREAD

**Issue by andiradulescu** [facebook/componentkit#407]
I need to add 2 tap gesture recognizers to a CKComponent:
- one with numberOfTapsRequired = 1 (tap)
- one with numberOfTapsRequired = 2 (double tap)

I managed to do this with 2 CKComponentGestureAttribute and using the setupFunction to set the number of taps.

In order for the single tap to not be called twice when double tapping, I need to do this:
`[singleTap requireGestureRecognizerToFail:doubleTap]`

The problem that I have is that there is no way to get the gesture recognizers instances in order to do the above.
*Or at least I don't think it is, since I couldn't find a way.*

How can this be solved?

**Comment by adamjernst** [comment]
There's no easy way with `CKComponentGestureAttribute`. I might recommend using a `CKComponentController` instead—you can have it own the two gesture recognizers, then add them to the view in `componentDidAcquireView` and remove them in `componentWillRelinquishView`.

**Comment by andiradulescu** [comment]
Thanks, Adam! I will try your solution tonight.
