### ISSUE TITLE
Break potential cycle via CKComponentHostingView by clearing model and context

### ISSUE THREAD

**Issue by kastiglione** [facebook/componentkit#408]
`CKComponentHostingView` holds a strong reference to the model/context provided in calls to `update{Model,Context}:`, and this strong reference isn't released until the next call to `update{Model,Context}:`.

Should `_synchronouslyUpdateComponentIfNeeded` and `_scheduleAsynchronousUpdate` clear out the model and context after its done with them?

This came about when view `A` owned a `CKComponentHostingView`, and called `updateContext:self`.

**Comment by adamjernst** [comment]
I don't think so, because if a state update resulted after then how would it get a reference to the model again?

I might be missing something though…

**Comment by kastiglione** [comment]
I clearly didn't think that one through.

And I guess it can't be a weak reference right because in some cases code will hand off the model/context to the hosting view and expect it to own it?

**Comment by adamjernst** [comment]
Yep!
