### ISSUE TITLE
How to scroll when items size smaller than collection view bounds?

### ISSUE THREAD

**Issue by tranngoclinh88** [facebook/componentkit#412]
I have a full screen collection view (320x480) and some items.
Total items size height is 300 (smaller than 480) and can not scroll.
Please tell me how to make it scrollable.
Thanks.

**Comment by majak** [comment]
Did you set the `alwaysBounceVertical` property on your CV to `YES`?

**Comment by tranngoclinh88** [comment]
@majak : Thank you very much!
