### ISSUE TITLE
CKNetworkImageComponent rounded corners

### ISSUE THREAD

**Issue by topa51** [facebook/componentkit#415]
Is it possible to round corners of CKNetworkImageComponent.

This solution

https://github.com/facebook/componentkit/issues/101

seams not working for CKNetworkImageComponent

**Comment by adamjernst** [comment]
It's not a built-in functionality. You would want to fork it and add that functionality if desired.

**Comment by topa51** [comment]
Hi Adam, thank you.

Any clue, where exactly I should do this. I investigate source code, but I don't have any idea, why setCornerRadius not working correctly.

**Comment by grp** [comment]
You could use `cornerRadius` on a layer (see `CKComponentViewAttribute::LayerAttribute()`) along with `clipsToBounds`, or for a generally more performant solution you could modify the network image component to do the rounding in CoreGraphics after downloading it and before displaying it.
