### ISSUE TITLE
Use it with AsyncDisplayKit

### ISSUE THREAD

**Issue by debug29** [facebook/componentkit#42]
Is it possible to use it with node ? Maybe in future.

**Comment by adamjernst** [comment]
We don't have any plans for AsyncDisplayKit integration. They're pretty different philosophies, and ComponentKit has built-in async layout.

AsyncDisplayKit is great for gesture-driven, highly dynamic UIs like Paper. ComponentKit is great for interfaces closer to traditional News Feed.
