### ISSUE TITLE
How to align 2 buttons, one left and one right?

### ISSUE THREAD

**Issue by tranngoclinh88** [facebook/componentkit#420]
As my title, I want to ask you to support for alignment 2 button in a view.
They should be one on left and the other on the right.
Please help.

**Comment by adamjernst** [comment]
Use a `CKStackLayoutComponent` with direction `Horizontal`. Put a spacer element between them with `flexGrow = YES`:

```
{
  {leftButton},
  {[CKComponent new], .flexGrow = YES},
  {rightButton}
}
```

**Comment by tranngoclinh88** [comment]
Thank @adamjernst.
I tried this solution before but it did not work.
I've just try some code and now it work.
