### ISSUE TITLE
Disable initial fadeIn animation for CKCollectionView

### ISSUE THREAD

**Issue by MohsenElgendy** [facebook/componentkit#421]
I am using CKCollectionView and when the data is populated and cells appears they all appear with a fadeIn animation, I want to disable this fadeIn animation? Any Suggestions ?

**Comment by smalllixin** [comment]
What you need is copy a new CKCollectionViewDataSource.
Then replace performBatchUpdates to reload.

**Comment by MohsenElgendy** [comment]
How is that going to stop the fading effect ? is there another workaround this ?
