### ISSUE TITLE
Demo bug with UIActivityIndicator

### ISSUE THREAD

**Issue by tamnt2692** [facebook/componentkit#423]
Hi guy, 

I like very much when use ComponentKit. I have loading component like this:

![screen shot 2015-11-04 at 11 53 52 am](https://cloud.githubusercontent.com/assets/11673429/10929808/c995844a-82ea-11e5-9a61-887e0c788cf3.png)

when tap on InteractiveQuoteComponent, I push a simple UIViewController. Before push view, the component random show loading component like this:

![screen shot 2015-11-04 at 11 56 44 am](https://cloud.githubusercontent.com/assets/11673429/10929845/2aee3f3e-82eb-11e5-93b5-93818c17da5d.png)

![screen shot 2015-11-04 at 11 40 27 am](https://cloud.githubusercontent.com/assets/11673429/10929852/35b53e72-82eb-11e5-851e-cbb361118a46.png)

When I scroll error component (error cell) hide screen completion and scroll to show it again, activity indicator not show.

Can you help me fix it ? thanks guy !

**Comment by adamjernst** [comment]
Odd! It might be a problem with `UIActivityIndicatorView` as I know sometimes it stops animating if you hide and re-show it.

You might want to add a `CKComponentController` and call `[self.view startAnimating];` in `didMount`.

**Comment by tamnt2692** [comment]
Hi guy,

With demo, I enqueue 10 item quote in first time - section 0, second enqueue I add one activity indicator at {1, 0} - index section 1, item 0, ViewReusePool create new view for activity indicator (1 instance).

Next, I enqueue 10 item quote in section 0, and scroll to bottom, activity indicator show again, BUT ViewReusePool ALWAYS create new view for it (n instance) when scroll to bottom n times. WHY ? I need one instance for activity indicator for cell {1, 0}, not n instance.

![screen shot 2015-12-07 at 9 29 42 am](https://cloud.githubusercontent.com/assets/11673429/11617693/18572ee6-9cc5-11e5-9e61-a1c24b222990.png)

NOTE: activity indicator have selector for didEnterReusePool (stop animation) and willLeaveReusePool (start animation) to fix for this error

![35b53e72-82eb-11e5-851e-cbb361118a46](https://cloud.githubusercontent.com/assets/11673429/11617746/6f27c2b2-9cc5-11e5-90cf-8ca2be5b0981.png)

BUT ComponentKit always create new view for activity indicator while I need one activity indicator at cell {1, 0}

![screen shot 2015-12-07 at 9 28 11 am](https://cloud.githubusercontent.com/assets/11673429/11617792/cfe1be0a-9cc5-11e5-9db1-553d835d5409.png)

LOG:

![screen shot 2015-12-07 at 9 38 22 am](https://cloud.githubusercontent.com/assets/11673429/11617839/4bacc156-9cc6-11e5-8f6c-30f9ca6fa71b.png)

Thanks for read !
