### ISSUE TITLE
Component with immutable model - improved documentation

### ISSUE THREAD

**Issue by toddrick** [facebook/componentkit#425]
According to the docs, immutable models should be used when passing into components.  I'm trying to understand how to use immutable models with components that allow the user to mutate the state.

For example:

If we use component kit for the news feed in which each 'Post' component includes the 'Like', 'Comment', and 'Share' components.  For the like component, we want to immediately mark the Post as liked and in the background we send a network request.  To the user, the 'Like' action occurs simultaneously.  

If I understand the docs correctly, for our 'LIKE' Component (where all we do is change font color) we would do this:

```
+ (id)initialState {
   return @YES;
}

+ (instancetype)newWithPost:(FBPost *)post {

  CKComponentScope scope(self);
  NSNumber *state = scope.state();
  state = @(post.isLiked);
  return [super newWithComponent:
          [CKTextComponent
           newWithAttributes:{
             .textColor = [state boolValue] ? [UIColor blueColor] : [UIColor greyColor],
           }
           viewAttributes:{}
           accessibilityContext:{}]];
}

- (void)didTapLike {
    [self updateState:^(id oldState){ return @YES; }];
}
```
In this update state, it seems appropriate to modify Post.liked = 'YES' so that if the user takes an action that calls the collectionViews reloadData method, we do not lose this state.

**Comment by adamjernst** [comment]
Yes, in fact you probably shouldn't use local component state here at all. Instead you should trigger an update to the Post's liked state back at the top level, which should feed into the ComponentDataSource and re-render that component from the outside.

There is much better documentation about this for React, where it is called the Flux Application Architecture. See here:

https://facebook.github.io/react/docs/flux-overview.html

I'd love a pull request that adds a link to that page on our Immutable Models page!

**Comment by toddrick** [comment]
@adamjernst does that mean that, since the top level needs to pass in the selector into the component constructor, that every time we add a mutable action we need to modify every constructor to pass down that selector X number of levels?
