### ISSUE TITLE
Proper way of passing model

### ISSUE THREAD

**Issue by TheSooth** [facebook/componentkit#426]
Guys, please explain me how to do this thing in a 'proper way':

For ex. I have a footer component with 'Like' button,
When I tap on like button - I want to update my model and send some call to server.

This can be done in next ways: 
- Adding to my component property with model (When I will tap on button in ComponentController I will handle action with my component which my model)
- Passing some kind of Context to component which will be contain a delegate with some methods like didTapLikeComponent... bla.blabla
- Updating state of component, handling state change in controller.

But I always should know the modelID, or smth like this

It's a normal to have variable in Component or it's smells bad? In case of 'bad-style', please explain a better way to avoid this...

Thanks

**Comment by adamjernst** [comment]
The way we do it at Facebook is to apply the Flux application architecture:

https://facebook.github.io/flux/docs/overview.html

The idea is that you have top-level "stores" that contain immutable objects, and your components should communicate back to those stores via "actions" to trigger updates to the store. Check out that page for more!

**Comment by TheSooth** [comment]
@adamjernst  Thanks,but I meant how "store" will be know which model it should updates?
I should a pass some model ID to store, and store will update it, right?

**Comment by adamjernst** [comment]
Yes, exactly.

**Comment by TheSooth** [comment]
@adamjernst so It's a normal way to have a variable in component with modelID/'store', am I right?

and in this case, I can make for example a Controller for my component which will be handle all events from button components, after this controller can call some methods in store and do some magic, yep?

**Comment by adamjernst** [comment]
Yes, that sounds about right!

**Comment by TheSooth** [comment]
@adamjernst  Thanks dude, sorry for stupid questions. 
I just thinking that storing something in component it's not a good idea.

Thanks again!
