### ISSUE TITLE
Issue with animationsFromPreviousComponent

### ISSUE THREAD

**Issue by TheSooth** [facebook/componentkit#427]
I'm implemented a default dataSource for collectionView (CKCollectionViewDataSource), updating my model and pushing new changes to dataSource - new changes has appeared, but method animationsFromPreviousComponent: never called. 

If I am trying to set a new state to component - then animationsFromPreviousComponent method is called.
Also I am trying to implement new dataSource (CKCollectionViewTransactionalDataSource) and get the same result, animation method never called :(

This is how I'm updates TransactionalDataSource
```objective-c
NSIndexPath *path = [NSIndexPath indexPathForItem:modelIndex inSection:0];
CKTransactionalComponentDataSourceChangesetBuilder *builder = 
[[CKTransactionalComponentDataSourceChangesetBuilder alloc] withUpdatedItems:@{path : model}];
[_dataSource applyChangeset:[builder build] mode:CKUpdateModeSynchronous userInfo:nil];
```

and this how I updates via default DataSource
```objective-c
    items.update({0, modelIndex}, model);
    [_dataSource enqueueChangeset:{{}, items}
                  constrainedSize:[_sizeRangeProvider sizeRangeForBoundingSize:self.collectionView.bounds.size]];
```

**Comment by ocrickard** [comment]
This is really old now, sorry no one answered you. If anyone is still running into this, please re-file an issue with a minimal repro project.
