### ISSUE TITLE
Help using CKTextKitEntityAttribute

### ISSUE THREAD

**Issue by gudjao** [facebook/componentkit#428]
I'm using CKTextKitEnitityAttribute to make the link clickable. but the problem is that when using CKTextComponent, the app crashes when you click on a trancated link.

<img width="328" alt="screen shot 2015-11-20 at 12 24 47 pm" src="https://cloud.githubusercontent.com/assets/4822801/11291937/b6958c7a-8f81-11e5-965e-a55c49dec24b.png">

```objective-c
[attributedString addAttribute:CKTextKitEntityAttributeName value:[[CKTextKitEntityAttribute alloc] initWithEntity:URL] range:result.range];
```

```objective-c
                contentComponent = [CKTextComponent
                                    newWithTextAttributes:{
                                        .attributedString = [self checkURLString:content.content],
                                        .truncationAttributedString = continueReading(),
                                        .maximumNumberOfLines = 4,
                                        .lineBreakMode = NSLineBreakByWordWrapping
                                    }
                                    viewAttributes:{
                                        {@selector(setBackgroundColor:), [UIColor clearColor]},
                                        {@selector(setUserInteractionEnabled:), @YES},
                                        CKComponentActionAttribute(@selector(stringTapped:withEvent:), CKUIControlEventTextViewDidTapText)
                                    }
                                    accessibilityContext:{
                                    }];
```

**Comment by ocrickard** [comment]
Can you provide the exception and call stack please?

**Comment by gudjao** [comment]
@ocrickard here it is.

*** Assertion failure in __63-[CKTextKitRenderer(Tracking) rectsForTextRange:measureOption:]_block_invoke(), /.../Pods/ComponentKit/ComponentTextKit/TextKit/CKTextKitRenderer+Positioning.mm:31

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: ''
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c506f45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010bf7edeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c506daa +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x0000000108c9c6b2 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 169
	4   Petgago                             0x00000001078de4b6 __63-[CKTextKitRenderer(Tracking) rectsForTextRange:measureOption:]_block_invoke + 646
	5   Petgago                             0x00000001078dda60 -[CKTextKitContext performBlockWithLockedTextKitComponents:] + 160
	6   Petgago                             0x00000001078de08b -[CKTextKitRenderer(Tracking) rectsForTextRange:measureOption:] + 395
	7   Petgago                             0x00000001078da57a -[CKTextComponentLayerHighlighter setHighlightedRange:] + 1114
	8   Petgago                             0x00000001078dc529 -[CKTextComponentViewControlTracker beginTrackingForTextComponentView:withTouch:withEvent:] + 585
	9   Petgago                             0x00000001078db579 -[CKTextComponentView beginTrackingWithTouch:withEvent:] + 249
	10  UIKit                               0x0000000109bd836b -[UIControl touchesBegan:withEvent:] + 136
	11  UIKit                               0x0000000109f3f9ba _UIGestureRecognizerUpdate + 10279
	12  CoreFoundation                      0x000000010c432947 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	13  CoreFoundation                      0x000000010c4328b7 __CFRunLoopDoObservers + 391
	14  CoreFoundation                      0x000000010c42850b __CFRunLoopRun + 1147
	15  CoreFoundation                      0x000000010c427e08 CFRunLoopRunSpecific + 488
	16  GraphicsServices                    0x000000010ce97ad2 GSEventRunModal + 161
	17  UIKit                               0x0000000109a6c30d UIApplicationMain + 171
	18  Petgago                             0x000000010774ddff main + 111
	19  libdyld.dylib                       0x000000010c9f292d start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

<img width="380" alt="screen shot 2015-11-23 at 12 00 30 pm" src="https://cloud.githubusercontent.com/assets/4822801/11329645/d40f05ba-91d9-11e5-819b-60b3fbcf32f3.png">

**Comment by ocrickard** [comment]
Looks like a bug to me! I'll try and get it fixed ASAP.

**Comment by gudjao** [comment]
Thanks.

**Comment by ocrickard** [comment]
Should be fixed. Let me know if you find any other issues.

**Comment by gudjao** [comment]
Yup It's working. Nice fix. Thank you.
