### ISSUE TITLE
Question - How to use changeset API to reload data

### ISSUE THREAD

**Issue by toddrick** [facebook/componentkit#435]
Suppose we have loaded a list into our collection view. Then the user pulls to refresh, and our endpoint returns a new list of items to show (some may have been deleted, modified, or new). We want to just throw out the old list and use the new one. However, the changeset API makes this difficult to accomplish because we would need to either
A. Loop through and delete all existing items, then add the new ones
B. Calculate if the previous list is longer/shorter, call update on the intersection then add/remove on the remaining indexPaths

I'm guessing there is a better way to do this?

**Comment by adamjernst** [comment]
Actually no, there's not a better way right now. You could fork and add an option to just reload everything; it's not something I want in the core, but it definitely makes sense for use cases like yours!

**Comment by toddrick** [comment]
Can you elaborate as to why this shouldn't be "in the core?" I understand that Facebook's news feed API may use a database cursor to return change lists when refreshing data, but very few startups can afford to build APIs that way early on. In addition, if you're working with medical data, financial data, or anything where elements can be frequently changing outside of the users control, it's important to ensure data freshness.

As such, the ComponentKit API is a degradation since it removes the ability to blow away the data model. Based on my initial research, it's pretty complicated to implement this without understanding the code extremely well (especially if you want to optimize performance, so that you don't need to call delete on every existing item but instead just use [_sections removeAllObjects];

I do think a lot of developers will run into this particular issue, and I for one don't think I could convince my company to use this framework (which is otherwise extremely interesting) without a built-in reloadData (forking will be very unpopular as the reloadData will not necessary play well with future releases).

**Comment by fatalaa** [comment]
I am clearing the collectionview like this:
```
- (void)clear
{
    CKArrayControllerInputItems items;
    for (int i = 0; i < self.ads.count; i++) {
        items.remove([NSIndexPath indexPathForRow:i inSection:0]);
    }
    [self.dataSource enqueueChangeset:{{}, items}
                      constrainedSize:[self.sizeRangeProvider sizeRangeForBoundingSize:self.collectionView.bounds.size]];
    self.ads = nil;
}
```

Adding elements to the collectionview is like this:
```
- (void)renderAdListWithData:(NSArray<RegularAdViewModel *> *)ads
{
    if (!self.ads) {
        _ads = [NSMutableArray array];
    }
    CKArrayControllerInputItems items;
    for (RegularAdViewModel *model in ads) {
        [self.ads addObject:model];
        items.insert([NSIndexPath indexPathForRow:self.ads.count - 1 inSection:0], (id)model);
    }

    [self.dataSource enqueueChangeset:{{}, items}
                      constrainedSize:[self.sizeRangeProvider sizeRangeForBoundingSize:self.collectionView.bounds.size]
     ];
    [self.adListPresenter didPresentAdList];
}
```

**Comment by toddrick** [comment]
But this is 1. Way more code needed then the single line of [self.collectionView reloadData]; and 2. Specific to your data model that will have to be customized in every view controller. In addition, it will be expensive when you have loaded a lot of items into your model since you need to remove each individual item (while is a problem when you're dealing with large datasets, especially ones that have been incrementally loaded). I am arguing that this API change performs worse than the original Apple implementation and adds additional overhead, all for what reason? It is absolutely possible to add a "clear" function to CKComponentDataSource and CKCollectionViewDataSource, however if this function is not maintained in the master repository, it is easy for it to conflict with future changes to the repo.

If you want I can write the code and submit a pull request, but I do not want to do that when Facebook's engineers are saying it is inappropriate to include "in the core." I have yet to hear why this is.

**Comment by fatalaa** [comment]
My implementation is based on a somewhat naive approach, and it works well with more than 1k items in the datasource, but I agree with you because it's more difficult than just invoking a "clear" method.
