### ISSUE TITLE
How can I pass struct type for CKViewComponentAttributeValueMap

### ISSUE THREAD

**Issue by ryuheechul** [facebook/componentkit#436]
I want to do something like this
```Objective-c
{@selector(setTitleEdgeInsets:), UIEdgeInsetsMake(0, 10, 0, 10)},
```
but it won't accept struct type.

**Comment by vbadeasv** [comment]
You can use
{@selector(setTitleEdgeInsets:), [NSValue valueWithUIEdgeInsets:UIEdgeInsetsMake(0, 10, 0, 10)]}

ComponentKit will make sure to extract what's inside the NSValue and pass it to the setter (see performSetter(id object, SEL setter, id value) from CKComponentViewAttribute.mm)

**Comment by adamjernst** [comment]
Yep, wrap in NSValue.

**Comment by darknoon** [comment]
It might be worthwhile to define a c++ type as the argument that would auto-box known Apple c types into their correct equivalent.

**Comment by darknoon** [comment]
@adamjernst here's an idea: https://github.com/facebook/componentkit/pull/437

**Comment by ryuheechul** [comment]
Cool! Thanks guys!
