### ISSUE TITLE
Question for highlight and tap for attributed string in CKTextComponent

### ISSUE THREAD

**Issue by tonychan818** [facebook/componentkit#438]
Hi, 
I have read #246 and #74 about how to append the tap action to a textComponent, but still no luck. 
here is my code.

for creating the attributed string:
```
 NSMutableAttributedString* aStr = [[NSMutableAttributedString alloc] initWithString:strToUse];
    
    NSError* error = nil;

    NSDataDetector* dataDetector = [NSDataDetector dataDetectorWithTypes:NSTextCheckingTypePhoneNumber|NSTextCheckingTypeLink error:&error];
    [dataDetector enumerateMatchesInString:strToUse options:0 range:NSMakeRange(0, midStr.length) usingBlock:^(NSTextCheckingResult * _Nullable result, NSMatchingFlags flags, BOOL * _Nonnull stop) {
        NSRange matchRange = [result range];
        [aStr addAttribute:NSLinkAttributeName value:@"www.google.com" range:matchRange];
    }];

```

and the TextComponent
```
[CKTextComponent
                                                   newWithTextAttributes:{.attributedString = aStr}
                                                   viewAttributes:{
                                                       {@selector(setBackgroundColor:),[UIColor clearColor]},
                                                       {CKComponentActionAttribute(@selector(doSomething:),CKUIControlEventTextViewDidTapText)},
                                                       {@selector(setUserInteractionEnabled:),@YES}
                                                   }
                                                   accessibilityContext:{.isAccessibilityElement = @(YES)}]
```

and it becomes
<img width="302" alt="screen shot 2015-12-04 at 10 40 54 am" src="https://cloud.githubusercontent.com/assets/5890291/11580619/3550116e-9a74-11e5-9159-1b7b4091ad7f.png">

the link is highlighted, but when it is tapped, no highlight, and the function doSomething is not called.

**Comment by ocrickard** [comment]
Man, I really need to write some docs on this.  Hopefully soon!

The issue most likely is that you're using NSLinkAttributeName. We don't use that since Apple's code applies styling to the string when you set that attribute, and we didn't want to mess with our styling systems when we add links to ranges.

Instead of using NSLinkAttribute, you would use CKTextKitEntityAttribute:

https://github.com/facebook/componentkit/blob/master/ComponentTextKit/TextKit/CKTextKitEntityAttribute.h

and use this attribute name:

https://github.com/facebook/componentkit/blob/master/ComponentTextKit/TextKit/CKTextKitAttributes.h#L18

So your example code might look like:

```
 NSMutableAttributedString* aStr = [[NSMutableAttributedString alloc] initWithString:strToUse];

    NSError* error = nil;

    NSDataDetector* dataDetector = [NSDataDetector dataDetectorWithTypes:NSTextCheckingTypePhoneNumber|NSTextCheckingTypeLink error:&error];
    [dataDetector enumerateMatchesInString:strToUse options:0 range:NSMakeRange(0, midStr.length) usingBlock:^(NSTextCheckingResult * _Nullable result, NSMatchingFlags flags, BOOL * _Nonnull stop) {
        NSRange matchRange = [result range];
        [aStr addAttribute:CKTextKitEntityAttributeName value:[[CKTextKitEntityAttribute alloc] initWithEntity:@"http://www.google.com"] range:matchRange];
    }];
```

**Comment by ocrickard** [comment]
Oh, and you're going to need to apply your styles to the string in your enumerator block since we won't color your links blue for you.

**Comment by tonychan818** [comment]
ya! it works now, thanks so much!
