### ISSUE TITLE
Setting corner radius of uiimageview get error

### ISSUE THREAD

**Issue by tonychan818** [facebook/componentkit#439]
I have created a component extend from CKCompositeComponent and here is the new function:
```
+(instancetype)newWithTestData:(TestData*)testData{
    
    UIImage* imgAvatar = [UIImage imageNamed:@"contact_defaultAvatar"];
    
    return [super newWithComponent:
            [CKInsetComponent
             newWithInsets:k_AVATAR_INSET
             component:[CKComponent
                        newWithView:{
                            [UIImageView class],
                            {
                                {@selector(setImage:),imgAvatar},
//                                {@selector(setClipsToBounds:),@(YES)},
                                {@selector(setCornerRadius:),@(20)}
                            }
                        }
                        size:{.width = 40,.height = 40}]]];
}
```

then I got this error:
<img width="1419" alt="screen shot 2015-12-04 at 5 45 31 pm" src="https://cloud.githubusercontent.com/assets/5890291/11586588/1d431004-9aaf-11e5-9595-3b63642db559.png">

any idea?

**Comment by ocrickard** [comment]
You're using setCornerRadius directly on the view here. I believe that parameter is present on the view's layer right?

We do have a helper to apply configuration selectors to the view's later, but I can't find them right now since I'm on my phone. I bet you can find them by digging around the view attribute code in CK.

**Comment by adamjernst** [comment]
Yep, use `CKComponentViewAttribute::LayerAttribute(@selector(setCornerRadius:))`
