### ISSUE TITLE
Set correct public headers in cocoapod

### ISSUE THREAD

**Issue by dstnbrkr** [facebook/componentkit#44]
ComponentKit.podspec doesn't specify which headers are public, which causes all headers to be public.

**Comment by dstnbrkr** [comment]
Easy solution here is to move all private headers into a Private/ dir so we can simply glob Private/**.*.h in config files.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by adamjernst** [comment]
Gonna close this for now, although PRs would be welcome.
