### ISSUE TITLE
does componentkit support animationImages in UIImageView?

### ISSUE THREAD

**Issue by tonychan818** [facebook/componentkit#441]
as I know componentkit render a new component every time when the layout is modified.
so does this component valid?
```
        NSMutableArray* images = [[NSMutableArray alloc] init];
        for (int i = 1; i <= 4 ; i++) {
            UIImage* img = [UIImage imageNamed:[NSString stringWithFormat:@"voice_wave_%@_0%d",imgColor,i]];
            [images addObject:img];
            NSLog(@"img: %@",img);
        }
        imgSoundComponent = [CKComponent newWithView:{
            [UIImageView class],
            {
                {@selector(setImage:),images[0]},
                {@selector(setAnimationImages:),images},
                {@selector(setAnimationDuration:),@(1.6)},
                {@selector(setAnimationRepeatCount:),@(0)}
            }
        }
                                                size:{.width = 24, .height = 24}];
```
since it is not showing anything once I set the animationImages. So, is the best way to do this is to keep changing the state for every 1.6s in my case??

**Comment by adamjernst** [comment]
I would avoid changing the state every 1.6 seconds. I'm not sure why the animation images property isn't working right—I'd breakpoint after mounting and inspect the properties on the `UIImageView` in the debugger. Let me know what you find out!

**Comment by tonychan818** [comment]
got it, cause I am not calling the function in main thread.
so I did the following in the componentController

```
    UIImageView* imgView = [c.viewContext.view viewWithTag:1000];
    NSLog(@"imgView: %@, isMainThread: %d",imgView,[NSThread isMainThread]);
    [imgView startAnimating];
```
