### ISSUE TITLE
Why ViewReusePool create many instance of UIActivityIndicatorView ?

### ISSUE THREAD

**Issue by tamnt2692** [facebook/componentkit#442]
Hi guy,

With demo, I enqueue 10 item quote in first time - section 0, second enqueue I add one activity indicator at {1, 0} - index section 1, item 0, ViewReusePool create new view for activity indicator (1 instance).

Next, I enqueue 10 item quote in section 0, and scroll to bottom, activity indicator show again, BUT ViewReusePool ALWAYS create new view for it (n instance) when scroll to bottom n times. WHY ? I need one instance for activity indicator for cell {1, 0}, not n instance.

![screen shot 2015-12-07 at 9 29 42 am](https://cloud.githubusercontent.com/assets/11673429/11617693/18572ee6-9cc5-11e5-9e61-a1c24b222990.png)

NOTE: activity indicator have selector for didEnterReusePool (stop animation) and willLeaveReusePool (start animation) to fix for this error

![35b53e72-82eb-11e5-851e-cbb361118a46](https://cloud.githubusercontent.com/assets/11673429/11617746/6f27c2b2-9cc5-11e5-90cf-8ca2be5b0981.png)

BUT ComponentKit always create new view for activity indicator while I need one activity indicator at cell {1, 0}

![screen shot 2015-12-07 at 9 28 11 am](https://cloud.githubusercontent.com/assets/11673429/11617792/cfe1be0a-9cc5-11e5-9db1-553d835d5409.png)

LOG:

![screen shot 2015-12-07 at 9 38 22 am](https://cloud.githubusercontent.com/assets/11673429/11617839/4bacc156-9cc6-11e5-8f6c-30f9ca6fa71b.png)

Thanks for read !

**Comment by adamjernst** [comment]
ComponentKit doesn't apply different reuseIdentifiers to different cells or sections in the UICollectionView, so it's possible for any cell to be recycled to show something very different.

In this case, the cells are being recycled between showing quotes and showing the activity indicator. It is expected that many activity indicators will be created.

This can be suboptimal sometimes if a view is particularly expensive to create or if it has state (like animation state, in this case!) that needs to be maintained. Use StatefulViewComponent in this case and only one instance of the view will be created.
