### ISSUE TITLE
Can I find a component with scope??

### ISSUE THREAD

**Issue by tonychan818** [facebook/componentkit#443]
in a collectionview controller, suppose a component is delegate to the controller for requesting an image(for some reason, I can't use the NetworkImageComponent). When the image is loaded. How can the controller inform that component to update the image??

what I thought so far is to manually store the NSIndexPath of that component, when the image is done. do something like
```
    CKArrayControllerInputItems items;
items.update({indexPath,object};
self.dataSource enqueueChangeset...

```

is there any better way to do so?

**Comment by ocrickard** [comment]
I would avoid coupling your view controllers to your components. One potential solution: The component itself can interact with a scoped image downloader, and when the image arrives you can directly call [self updateState...], and store the image or an identifier as the state for the component.
