### ISSUE TITLE
CKLabelComponent with size?

### ISSUE THREAD

**Issue by esam091** [facebook/componentkit#444]
How do I get a label component with configurable size? something like
```
[CKLabelComponent
            newWithLabelAttributes:{
                .string = model
            }
            viewAttributes:{
                {@selector(setBackgroundColor:), [UIColor lightGrayColor]}
            }
            size:{.width = 100, .height = 20}]
```

I can achieve the similar using
```
[CKComponent
     newWithView:{
         [UILabel class],
         {
             {@selector(setText:), @"foo"}}
         }
     }
     size:{.width = 100, .height = 20}]
```

or I can make a composite component that does the same thing, but those feel like hacks to me. Any advice for this?

**Comment by ocrickard** [comment]
This was an oversight when I wrote the API, we should fix it by adding the size: parameter to the constructor, and threading it through both CKLabelComponent and CKTextComponent. Pull requests welcome!

In the meantime, you can probably use a static layout component to achieve the same effects: CKStaticLayoutComponent.
