### ISSUE TITLE
CKLabelComponent miscalculated the height.

### ISSUE THREAD

**Issue by mornirch** [facebook/componentkit#445]
[CKLabelComponent
     newWithLabelAttributes:{
         .string = @"你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界你好世界",
         .font = [UIFont systemFontOfSize:14],
         .maximumNumberOfLines = 3,
         .lineSpacing = 6,
         .alignment = NSTextAlignmentJustified,
         .truncationString = @"...",
     }
     viewAttributes:{}]

It is supposed to display three line, but displays only two lines:

<img width="513" alt="default" src="https://cloud.githubusercontent.com/assets/9624359/11910973/0900a9c8-a642-11e5-88a4-181c950561c0.png">

**Comment by adamjernst** [comment]
There are subtle bugs in Apple's text rendering code that often result in bugs like this. We've seen it frequently.

If you can track it down to a bug in ComponentKit, please comment on this task and point out the problem!

**Comment by mornirch** [comment]
Always use infinite height initialize NSTextContainer can avoid this problem.
_textContainer = [[NSTextContainer alloc] initWithSize:{constrainedSize.width, INFINITY}];

**Comment by matin0728** [comment]
@semiwhale using this got help，尤其是中英混排的时候会比较好，不知道你有没有更好的办法: 
.maximumNumberOfLines = lines,
.lineHeightMultiple = lineHeightMultiple,
.maximumLineHeight = ceilf((titleFont.pointSize + 1)*lineHeightMultiple),
