### ISSUE TITLE
to keep uiCollectionView on the same row even new row added.

### ISSUE THREAD

**Issue by tonychan818** [facebook/componentkit#448]
suppose now I have 10 rows
...
4
5
6
7
...
when the row 0 inserted in the top.
the collectionView is automatically scrolled to become
...
3
4
5
6
...
how can I keep it to the position to focus on (4) according to the above case?

**Comment by ocrickard** [comment]
This is more of a question for general UICollectionView, and not necessarily Components. You can solve this by recording and restoring scroll position relative to the elements in your list.
