### ISSUE TITLE
how to get component size on CKNetworkImageDownloading protocol?

### ISSUE THREAD

**Issue by mornirch** [facebook/componentkit#449]
I want download a image which is same size with component.

**Comment by adamjernst** [comment]
We don't want to support that in the core `CKNetworkImageComponent`. I would fork it and modify the protocol in your fork. From there it should be easy—the method is invoked from a `UIView` which has size information in its `frame`.

**Comment by mornirch** [comment]
frame is {0, 0, 0, 0} at first use.
