### ISSUE TITLE
Updating CKComponentHostingView synchronously and asynchronously eventually causes future asynchronous updates to never happen

### ISSUE THREAD

**Issue by nihalahmed** [facebook/componentkit#453]
I think the problem arises when the following code path gets executed:
https://github.com/facebook/componentkit/blob/master/ComponentKit/HostingView/CKComponentHostingView.mm#L199.

The code returns early but does not set `_scheduledAsynchronousComponentUpdate` to `NO` before returning.

**Comment by ocrickard** [comment]
Oh boy, that doesn't sound good. Can you provide a limited repro case?

**Comment by adamjernst** [comment]
Found the cause for this! PR coming.

**Comment by ocrickard** [comment]
@adamjernst I'm assuming that this was fixed in the refactor of the hosting view?
