### ISSUE TITLE
How to add header and footer views to uicollectionview ?

### ISSUE THREAD

**Issue by MohsenElgendy** [facebook/componentkit#454]
I am not using UICollectionView directly, i am subclassing CKCompositeComponent and inside that i am creating a uicollectionview, but the question is that whenever i try to add normal methods for creating a header to the section it gives an error related to animations.

How to add a footer view to UICollectionView directly within a CKCompositeComponent ?

Even using the simplest method which is "referenceSizeForFooterInSection" Causes this error "Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to create view animation for nil view'"

Thanks in advance.

**Comment by MohsenElgendy** [comment]
@adamjernst Can you offer any help ?

**Comment by fatalaa** [comment]
First, I think you should subclass UICollectionView, implement the 
```- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath``` method
For example:
```
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath
{
    UICollectionReusableView *reusableview = nil;
    if (kind == UICollectionElementKindSectionFooter) {
        //You should customize the cell at this point
        UICollectionReusableView *footerview = [collectionView dequeueReusableSupplementaryViewOfKind:UICollectionElementKindSectionFooter withReuseIdentifier:@"FooterView" forIndexPath:indexPath];

        reusableview = footerview;
    }
        
    return reusableview;
}
```

I suppose you should use a ComponentController to properly handle the state of your embedded ```UICollectionView```'s fetching.
