### ISSUE TITLE
CKComponentDataSourceDelegate Protocol Definition Not Found

### ISSUE THREAD

**Issue by Stunner** [facebook/componentkit#456]
Adding the following to my tableview file (with extension of .mm)
```
// ...
#import <ComponentKit/CKComponentProvider.h>
#import <ComponentKit/CKComponentDataSource.h>
#import <ComponentKit/CKComponentDataSourceOutputItem.h>
#import <ComponentKit/CKComponentConstantDecider.h>
#import <ComponentKit/CKDimension.h>
#import <ComponentKit/CKTextComponent.h>

@interface SimpleCalculateViewController () <UIGestureRecognizerDelegate, CKComponentProvider, CKComponentDataSourceDelegate>
// ...
```
Gives me a warning stating that `CKComponentDataSourceDelegate` protocol definition cannot be found.

This issue is not present in version 0.12.

**Comment by adamjernst** [comment]
Yes, it was moved to a new separate header that you'll have to import. (Or use the umbrella header; if it's not there already, issue a PR to add it.)

**Comment by Stunner** [comment]
I should clarify that I was following the ComponentKit guide found here: http://componentkit.org/docs/datasource-dive-deeper.html If you guys could update that when you get a chance to that would be really helpful.

**Comment by adamjernst** [comment]
Ah, sounds good!
