### ISSUE TITLE
Time for next release(0.14) for Cocoapods?

### ISSUE THREAD

**Issue by ryuheechul** [facebook/componentkit#457]
There is lots of bug fixes and improvements after 0.13

(you can check the changes via the link below.)
https://github.com/facebook/componentkit/compare/46141bbbe8146f4dde7dc14340db066b263676fa...master

It would be nice that the recent source code can be shipped via cocoapods for many.

**Comment by adamjernst** [comment]
Sure!

**Comment by dbworku** [comment]
+1

**Comment by Stunner** [comment]
:+1:

**Comment by seyfeddin** [comment]
+1

**Comment by adamjernst** [comment]
woo done
