### ISSUE TITLE
Create an umbrella header?

### ISSUE THREAD

**Issue by kastiglione** [facebook/componentkit#46]
Is the absence of an umbrella header an oversight, or part of the framework's opinions?

**Comment by adamjernst** [comment]
Opinions. I dislike umbrella headers generally. (Probably influenced by the fact that we dislike them at Facebook generally...)

**Comment by jlpiedrahita** [comment]
Most system frameworks and 3er party libraries/frameworks do it.

Can you expand on why you think this should not be done? Personally I find it annoying to have to know which file to include for each symbol I need, it's not always obvious.

**Comment by adamjernst** [comment]
Well, I wouldn't be opposed to a pull request I guess. We can always disallow its use internally.

(With the sheer amount of code we have, we find umbrella headers end up bloating compilation times and result in huge numbers of symbols available. But for most smaller projects it's not an issue at all.)

**Comment by kastiglione** [comment]
:+1: I like giving the option.

**Comment by kastiglione** [comment]
This relates to #44.
