### ISSUE TITLE
How to apply margin value to component?

### ISSUE THREAD

**Issue by vizlabxt** [facebook/componentkit#465]
hi, I've been playing around with ComponentKit for a few days. Is there any place to specify  "margin-left" or "margin-top" attribute to the component?

**Comment by vbadeasv** [comment]
You can wrap your component in a CKInsetComponent. For example:
[CKInsetComponent
 newWithInsets:{ .left = 10, .top = 10 }
 component:[CKLabelComponent
            newWithLabelAttributes:{
                .string = @"Foo"
            }
            viewAttributes:{}
            size: {}]];

**Comment by vizlabxt** [comment]
@vbadeasv thanks!
