### ISSUE TITLE
Is there any attribute equivalent to "flex-wrap" ?

### ISSUE THREAD

**Issue by vizlabxt** [facebook/componentkit#470]
Hi:

Does CKStackLayoutComponent support "image wrapping" ?
<img src="http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071006.png"/>

**Comment by adamjernst** [comment]
Nope! We decided not to implement it to keep the stack layout component simple. Pull requests welcome, but they'd have to keep the complexity very low and comply with flex-box's semantics.

**Comment by antigp** [comment]
@vizlabxt , Implemented in #479
