### ISSUE TITLE
[Question] Can we expose CKComponentSnapshotTestCase?

### ISSUE THREAD

**Issue by dbworku** [facebook/componentkit#483]
I'm creating snapshot tests for custom components in an app. Is there a better way to expose the `CKComponentSnapshotTestCase` class to a private repo than copying the files?

My suggestion is to make `CKComponentSnapshotTestCase` a subspec. Then we could add those files to any target with `pod 'ComponentKit/ComponentSnapshotTestCase'` .

**Comment by ocrickard** [comment]
Yeah, this is a good point, and sounds like copying the files atm is about the best you can do. TBH, we haven't really formed opinions on whether we should use subspecs or what... Would love to see a pull request showing what that looks like. Mind writing one?

**Comment by dbworku** [comment]
Absolutely, I'll work on a PR.
