### ISSUE TITLE
is there any layout fit this case??

### ISSUE THREAD

**Issue by tonychan818** [facebook/componentkit#487]
I wanna create a layout like CKTextComponent's behaviour, but using views instead of text.
I try to do this with a CKStackLayoutComponent with direction Horizontal and set the maxWidth.

What I suppose it looks like:
|-----------------------------|
[View1][View2][View3]
[View4][View5][View6]

but what it comes out
|-----------------------------|
[View1][View2][View3][View4][View5][View6]

since the width of the views are not constant. So it is hard to calculate this and using a mixture of Vertical and Horizontal Stack Layout.

any idea??
many thanks

**Comment by ocrickard** [comment]
You probably want something like a flex-wrap implementation. Sadly we don't support that standard yet. There was recently a PR that had an incomplete implementation that needs some work. If you'd like to pick it up that'd be awesome!

Alternatively it's not too bad to write a basic greedy wrapping component that may not fully respect the specification but would solve your case. You can create a new component that receives a vector of child components. In a custom layout function you can lay them out one after the other until you exceed the constraining max width and then break into another line.

**Comment by ocrickard** [comment]
Here's an implementation that I wrote for a side project a couple months ago that can kinda show you how to do this:

```
@implementation TagStackComponent
{
  TagStackComponent _style;
  std::vector<CKComponent *> _components;
}

+ (instancetype)newWithStyle:(const OOTagStackComponentStyle &)style
                  components:(const std::vector<CKComponent *> &)components;
{
  TagStackComponent *c = [super newWithView:{} size:{}];
  if (c) {
    c->_style = style;
    c->_components = components;
  }
  return c;
}

- (CKComponentLayout)computeLayoutThatFits:(CKSizeRange)constrainedSize
{
  CGRect bounds = CGRectZero;
  CGPoint currentPosition = CGPointZero;
  std::vector<CKComponentLayoutChild> children;
  for(CKComponent *child : _components) {
    CKComponentLayout childLayout = [child layoutThatFits:{ {}, constrainedSize.max }
                                               parentSize:kCKComponentParentSizeUndefined];
    CGRect childFrame;
    if (currentPosition.x + childLayout.size.width + _style.spacing > constrainedSize.max.width) {
      // We need to break onto a new line
      childFrame = {
        { 0, bounds.size.height + _style.spacing },
        childLayout.size
      };
    } else {
      // Keep going on the same line as before.
      childFrame = {
        currentPosition,
        childLayout.size
      };
    }
    
    currentPosition = { CGRectGetMaxX(childFrame) + _style.spacing, CGRectGetMinY(childFrame) };
    bounds = CGRectUnion(bounds, childFrame);
    children.push_back({
      .position = childFrame.origin,
      .layout = childLayout
    });
  }
  return CKComponentLayout(self, constrainedSize.clamp(bounds.size), children);
}

@end
```

**Comment by tonychan818** [comment]
awesome! thanks!
