### ISSUE TITLE
CKRecursiveComponentReflow doesn't work with Transactional Data Source

### ISSUE THREAD

**Issue by natansh** [facebook/componentkit#491]
The reflow mechanism doesn't handle the TDS case yet. I wonder if `rcomponents` is used that much. If not, we should consider removing that code, both here and in `chisel`.

**Comment by adamjernst** [comment]
`rcomponents` just needs to be mapped onto `reloadWithMode:userInfo:`.

**Comment by eczarny** [comment]
Fixed internally but the chisel changes need to be merged upstream (/cc @kastiglione). Closing this issue in the interim.
