### ISSUE TITLE
[Question] How to set adjustsFontSizeToFitWidth on CKLabelComponent?

### ISSUE THREAD

**Issue by mwfire** [facebook/componentkit#494]
Hey there!

Is it possible to use `setAdjustsFontSizeToFitWidth` with a `CKLabelComponent`, that is, passing it through to the underlying UILabel component? The following crashes:

```Objective-C
 CKLabelComponent *distanceLabel = [CKLabelComponent newWithLabelAttributes:{
                                                            .string = @"A string",
                                                            .maximumNumberOfLines = 1
                                                         } 
                                                         viewAttributes:{
                                                             { @selector(setAdjustsFontSizeToFitWidth:), YES }
                                                         } size:{}];
```

Thanks in advance, any help would be appreciated :)

**Comment by eczarny** [comment]
I don't believe `CKLabelComponent` is backed by a `UILabel`. I'm assuming you're seeing an `NSInvalidArgumentException` exception due to an unrecognized selector being sent?

**Comment by ocrickard** [comment]
@eczarny is correct, we don't implement variable font size. If you need it for this label you can use a component which directly configures a UILabel via a view configuration.

If you'd like to implement variable font sizing, we're open to Pull Requests! It'd be awesome if we could do it quickly. The algorithm is a little complex and results in frame drops when you use it with UILabel, but if we were able to do it as part of component layout then we can avoid the frame drops.

**Comment by mwfire** [comment]
@eczarny @ocrickard Thanks for your reply, makes sense. Just wanted to make sure that somewhere down the chain there isn't a label that would respond to that selector. Still have to dig a bit deeper to fully understand some of ComponentKits concepts, thanks for bearing with me. :)
