### ISSUE TITLE
How to make component with fixed position?

### ISSUE THREAD

**Issue by tranngoclinh88** [facebook/componentkit#501]
<img width="1020" alt="screen shot 2016-03-10 at 10 55 11 pm" src="https://cloud.githubusercontent.com/assets/1511264/13675270/64c03c12-e713-11e5-844b-190135e47e72.png">
Please help me to make component with fixed position like image above.

**Comment by adamjernst** [comment]
```
[CKOverlayLayoutComponent
 newWithComponent:
 [ArticlePreviewComponent
  newWithArticle:...]
 overlay:
 [CKInsetComponent
  newWithInsets:{.right = INFINITY, .bottom = INFINITY}
  component:
  [DateFlagComponent
   newWithDate:...]]]
```

`CKInsetComponent` will anchor the flag to the top left if you supply infinite bottom and right insets. Overlay will put it on top of the base article component.
