### ISSUE TITLE
Improve Component Controllers

### ISSUE THREAD

**Issue by adamjernst** [facebook/componentkit#504]
#### Summary

`CKComponentController.component` should never be nil and should always point to the latest component. There are two cases:

**Before First Mount**
Users frequently want to access the component from the controller before it is mounted for the first time. Currently the `component` property is modified as part of mounting, so it is nil until the first mount.

**While Unmounted**
Users expect the component to be the latest "version" of the component when it is updated while offscreen and unmounted. For example, imagine a state update that occurs while the component is far offscreen. It would be ideal to allow the controller's `willUpdateComponent`/`didUpdateComponent` methods to execute and to update the `component` property even though the component is unmounted.
#### Areas to Investigate

**Creating Controllers**: Controllers are currently created as components are created. It would be better to create them at some later point, after a complete `CKComponentLayout` has been created.

**Updating Controllers**: To fully fix this problem, we'd need to redefine how the controller's current component is determined to divorce it from the mounting process — but hopefully without breaking the invariant that the controller's component is always the currently mounted component.

**Comment by adamjernst** [comment]
One interesting challenge is that `CKComponentController.component` is currently `weak` to prevent a retain cycle. It should probably be `strong` instead (to strengthen the never-nil guarantee) and then we manually break the retain cycle at some later point (when removing the item from the data source, or destroying the component hosting view).

This would also neatly solve #429 by giving us an obvious point to implement a component controller "death" hook (when the `component` property is set to nil).

**Comment by adamjernst** [comment]
… which in turn allows fixing #406, since right now there's no obvious place to fix the leak of the context object.

**Comment by ocrickard** [comment]
So there are 3 clear parts here:

1. controller.component is nil before mount.
2. controller.component is nil after dealloc of component.
3. controller.component may not be the most recent component.

1 is resolved by my PR, but 2 & 3 remains. I'm targeting 0.15 for 1, 2 for 0.16, and 3 for 0.20

**Comment by fabiomassimo** [comment]
Since the last time this got updated the core team has been focused on different features that require this topic to be revisited once again. Closing this and following up on our roadmap.
