### ISSUE TITLE
When I new a controller in your demo and #import<ComponentKit/ComponentKit.h>

### ISSUE THREAD

**Issue by wy19901227** [facebook/componentkit#510]
![image](https://cloud.githubusercontent.com/assets/8086633/14013202/0242c626-f1e6-11e5-8b53-a90dfa8f1636.png)

**Comment by majak** [comment]
ComponentKit is written in ObjC++. That pretty much means your code using CK has to be compiled as ObjC++. You can fix it by renaming your file (that imports `ComponentKit.h`) from `.m` to `.mm`.
