### ISSUE TITLE
CKComponentAction doesn't follow nested hosting views

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#511]
I am getting an assertion error 

```
void CKComponentActionSend(CKComponentAction action, CKComponent *sender, id context, CKComponentActionSendBehavior behavior)  { ...CKCAssertNotNil(responder, @"Unhandled component action %@ following responder chain %@",
                  NSStringFromSelector(action), _debugResponderChain(sender));...}

```

I believe this stems because I have a collection view (horizontal scrolled) nested in a hosting view:

Conceptually the component hierarchy is:

```
CKComponentHostingView 
  |-CKMyCustomComponentWithAController // ActionShouldBeHandledHere
    |- CKStackLayoutComponent
       |- CKSomething....
       |- CKMyCustomComponentWithACollectionView
         |-CollectionView
           |-CKCollectionViewDataSource...
            |-CKAnotherCustomComponentWhichReceivesATap // Action is sent from here (and should propagate to CKMyCustomComponentWithAController)
    |- CK...


```

When the component sending the action is nested directly under the `"CKMyCustomComponentWithAController"` , the action is sent / received as expected.

When the component is moved , and becomes nested in the collection view, the action stops propagating as expected.

I assume that the responder chain bails when it reaches the collection view cell instead of continuing.

I also used 

```
pcomponents
```

and see that the hierarchy dump doesn't continue into the collection view portion :

```
<CKStaticLayoutComponent: 0x7f89eacf1dd0>, Position: {0, 0}, Size: {414, 736}
| <CKStackLayoutComponent: 0x7f89eacf1d10>, Position: {0, 0}, Size: {414, 736}
| | <IIOFormComponent: 0x7f89eace40d0>, Position: {0, 0}, Size: {414, 736} << a controller is attached to this component
| | | <CKInsetComponent: 0x7f89eada7740>, Position: {0, 6}, Size: {44, 32}
| | | | <IIOCKCloseButtonComponent: 0x7f89ead34d10>, Position: {6, 0}, Size: {32, 32}
| | | <IIOCKPagerLayoutComponent: 0x7f89eacf6d60>, Position: {0, 44}, Size: {414, 644}
| | | | <CKStackLayoutComponent: 0x7f89ec609970>, Position: {0, 0}, Size: {414, 644}
               >>>>> Collection view should have been printed here
               >>>>> There is a button here sending an action that should be handled by the FORM component controller
| | | <IIOCTAButtonComponent: 0x7f89ec62a6a0>, Position: {0, 688}, Size: {414, 32}

```

**Comment by darknoon** [comment]
I ran into something like this myself today—one of the strategies is to override `- (id)targetForAction:(SEL)action withSender:(id)sender` and try to redirect its recursion back onto the component hierarchy. @adamjernst could probably say something more interesting about this issue.

If you have a minimal test app, that would be helpful in fixing this.

**Comment by avnerbarr** [comment]
I'll work on creating one.

To reproduce, basically you can create a linear layout with a child component containing a collection view (or subview thereof). In the child component's view implement the collection view data source using the CKComponentDataSource. (This is to accomplish a horizontal collection view inside a vertical collection view)

Something like:

```
@interface HorizontalView : UIView
@property (nonatomic,strong) UICollectionView *collectionView 
...
@end

@implementation HorizontalView 
-(instancetype)init {
   ...
   _collectionView = [UICollectionView ...];
   _dataSource = [CKDataSource ...]
   ....
}

-(void)setHorizontalComponents:(NSArray <CKComponent *> *)children {
   ... apply change set 
}
@end
```

and in the vertical component 

```
@implementation VerticalComponentWhichContainsAHorizontalComponent
+(instancetype)newWithConfiguration: (...) configuration {
         // vertical layout stack containing the horizontal view 
   return [CKStackLayoutComponent .... children {                                                                        
  {
  .component = child1
  },
  {
  .component = [CKComponent newWithView:{
                                 [HorizontalView class],
                                 {
                                     {@selector(setHorizontalComponents:),horizontalComponents}
                                 }
                           } ...]
   } ...];
@end
```

**Comment by ocrickard** [comment]
This is a really interesting problem. I agree with @darknoon that you can probably re-target the responder chain, but that's not great.

If you have the minimal test app, then that would be greatly appreciated.

**Comment by ocrickard** [comment]
OK, I re-wrote CKComponentAction to provide a non-responder-chain based action. I recommend moving to this if you need to bridge gaps like this. We're trying to get away from the responder chain in general.
