### ISSUE TITLE
How to insert diffrent cell?

### ISSUE THREAD

**Issue by wy19901227** [facebook/componentkit#513]
In studying CK, In this method 
+ (CKComponent *)componentForModel:(Quote *)quote context:(QuoteContext *)context
{
 
 return [InteractiveQuoteComponent
          newWithQuote:quote
          context:context];

}

How can I get another component? because it's possible that the all cell is not same.

**Comment by wy19901227** [comment]
according to  the diffrent model?

**Comment by adamjernst** [comment]
Yep! Inspect the model.
