### ISSUE TITLE
@selector() can have two more parameter？

### ISSUE THREAD

**Issue by wy19901227** [facebook/componentkit#516]
![image](https://cloud.githubusercontent.com/assets/8086633/14100135/b34b3c2a-f5bd-11e5-8b0d-36029b4ad79a.png)
![image](https://cloud.githubusercontent.com/assets/8086633/14100182/1c545800-f5be-11e5-89fb-df13e78cda9f.png)

**Comment by wy19901227** [comment]
the method adjustLayoutWithType:midSpace:sizeToFit:  is my creat,It have three parameter, So,I set three value.

**Comment by wy19901227** [comment]
What I mean is , I use CKButtonComponent, and I set it's title and image,But I want to make make the titleLeft and ImageRight,So, I write a method to control this,But,How can I use this method?

**Comment by ocrickard** [comment]
Ok there are two parts to this question:

1. How can I create a CKComponentViewAttribute for a selector and more than one argument? The answer is to use our block API to call a custom applicator. You can read more here: http://componentkit.org/docs/advanced-views.html in the second sections on view attributes. 

2. In general you should probably not have a single view attribute method which sets three parameters at the same time. I would suggest pulling this selector apart and just using three different setters.

**Comment by wy19901227** [comment]
how to use the block ?
