### ISSUE TITLE
How can I create components with custom layout.

### ISSUE THREAD

**Issue by tranngoclinh88** [facebook/componentkit#517]
![img_2124](https://cloud.githubusercontent.com/assets/1511264/14101169/d76b64be-f5bc-11e5-8a8e-bd9efd5975a1.PNG)
I want to use component kit to build UI like this image. Please tell me how to make custom layout?

**Comment by ocrickard** [comment]
I would suggest that each of the above items be rendered using a separate cell. You should use a UICollectionViewFlowLayout to tile them as you have them here.

The only thing new about your layout that isn't covered in the example project is that your cells are only half-width.
