### ISSUE TITLE
About my CompositeComponent

### ISSUE THREAD

**Issue by wy19901227** [facebook/componentkit#519]
![image](https://cloud.githubusercontent.com/assets/8086633/14130002/e5a60674-f661-11e5-8e18-d3da69cfe52f.png)

**Comment by wy19901227** [comment]
![image](https://cloud.githubusercontent.com/assets/8086633/14130040/431f2a24-f662-11e5-913b-78d670656e4a.png)

**Comment by wy19901227** [comment]
I set my socialComponent have a edge,but ,the result it isn't right. I contract to your demo,but I cann't find  
what's wrong. If I set the postComponnet's size.width,It will be right. But,I think the postComponent's size.width should not to be set. can you point me what's wrong

**Comment by adamjernst** [comment]
Add flexShrink = YES to the child in the in the horizontal stack that contains the text. That instructs flexbox to shrink that child to fit the available width.

(I'd show you, but you posted a screenshot of code instead of text)
