### ISSUE TITLE
Assertion error in CKComponentController

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#520]
I'm getting an assertion error in componentWillUnmount

How should I debug this?

    - (void)componentWillUnmount:(CKComponent *)component {
        ...

    default:
      CKFailAssert(@"Unexpected state '%@' in %@ (%@)", componentStateName(_state), [self class],     _component);
    }

**Comment by darknoon** [comment]
1. What state name did it log?
2. What method of hosting components are you using?

**Comment by avnerbarr** [comment]
It was "unmounted"

using 

[hostingview updateModel:model mode:CKUpdateModeSynchronous];

**Comment by adamjernst** [comment]
Yikes, we've seen this a few times and haven't nailed it down. If you have an easy minimal repro, please let me know so I can investigate and fix.

**Comment by eczarny** [comment]
I believe #623 actually resolves this. Closing.
