### ISSUE TITLE
About CKStackLayoutComponent

### ISSUE THREAD

**Issue by wy19901227** [facebook/componentkit#521]
![image](https://cloud.githubusercontent.com/assets/8086633/14162908/e23f5c9e-f722-11e5-871b-1cdf2b8ec887.png)

**Comment by wy19901227** [comment]
In the picture,what I want is the time and phoneTag  are in the end of the horizontal stackView,zhe red view is a space view. so How can I set ?

**Comment by darknoon** [comment]
Setting the red layout child to `.flexGrow = true` will probably do what you need, but you can also set the last child to `.alignSelf = CKStackLayoutAlignSelfEnd` and it will align itself without the need to insert a view in the middle.

Please reopen with code defining your component if you're still stuck.

**Comment by wy19901227** [comment]
yeah, and must set the the horizontal stackView .alignSelf= CKStackLayoutAlignSelfStrech. the red layout child to .flexGrow = true.
