### ISSUE TITLE
Hi!,Have FlowLayout?

### ISSUE THREAD

**Issue by wy19901227** [facebook/componentkit#522]

**Comment by majak** [comment]
Hey @wy19901227, it's not entirely clear what you are asking about. Could you try to rephrase your question?

If you are asking whether CK can be used with UICollectionViewFlowLayout the answer is yes. The example app does it, check it out.

**Comment by wy19901227** [comment]
what I say is CK has CKstacklayoutComponent  CKIntetlayoutComponent..So,Can have CKFlowLayoutComoonent which layout flow

发自我的 iPhone

**Comment by majak** [comment]
I don't think we have such component yet. There was a pretty recent attempt at doing so here:
https://github.com/facebook/componentkit/pull/479
You could try asking its author whether he plans to work on it more. If not you could pick it up and drive it to finish.

In some cases you may not need this component and you could just let UICollectionViewFlowLayout do it for you, as suggested here:
https://github.com/facebook/componentkit/issues/517
