### ISSUE TITLE
[Question] - Is it acceptable to update a components state in its initialization method before the component is generated

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#525]
I need to generate an event "state changed" in one of my components. 
The global state of the "props" is handled outside the scope of the component itself (or its controller).

Conceptually the "state changed" is calculated between the props passed into the component and the saved state scope of the component. 
The "state change" in one component may mean that the current version of the component should be discarded and the full tree should be re-rendered.

For instance I might have something like:

```
+ (ComponentState *)initialState {
    return nil; // initially component state isn't set 
}
+(instancetype)newWithConfiguration:(Configuration *)passedInConfiguration {
   CKComponentScope scope(self, passedInConfiguration.id);
   id componentState = scope.state();
     

  CKComponent returnComponent = [CK ... new....];

// in some cases the props are different than the component state and I need to generate a "state change event" which may modify behavior of other components  
  if (diff(passedInConfiguration,componentState)) {

     // Global needs to know that something changed
     [Global stateChanged:....];
 
      // need to save the new local state before creating this component.
      // the global object may trigger a re-render of the root component before this component is even generated.
       // is it acceptable to trigger an updateState at this point?       
       [returnComponent updateState:^(id oldState) {
                                                                   return newState;
                                                           }];
  }

   return returnComponent;

}
```

**Comment by avnerbarr** [comment]
I see this guy http://componentkit.org/docs/no-side-effects.html

But I don't see a way around updating global state not from within the component. 

In order to do that I would need to duplicate the components internal state to another location and apply that before creating the component. Seems unnecessary and generates spaghetti,

**Comment by adamjernst** [comment]
No, unfortunately this isn't valid. Ideally we'd have a better way to handle this, but right now we don't. Sorry.
