### ISSUE TITLE
Could you guide me how to present a popover when user taps on a CKButtonComponent?

### ISSUE THREAD

**Issue by doanthehien1986** [facebook/componentkit#528]

**Comment by doanthehien1986** [comment]
it's like Facebook app when user taps on 'down arrow' button on a feed view and it presents a popover.

**Comment by adamjernst** [comment]
We usually use an "escape hatch" to present this with regular imperative (non-Component) code. You can use a `CKComponentController` to implement a `CKComponentAction` that will be called when the button is tapped, and from the component controller you can call `viewContext` on the `sender` parameter to the action to get the position to show the popover from.

The component controller gives you a convenient place to put ivars that manage the popover.

Let me know if you need further info.

**Comment by doanthehien1986** [comment]
@adamjernst  Your solution sounds great. Thanks so much for your valuable guide.
