### ISSUE TITLE
Question - Proper way to communicate between controllers

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#532]
In cases where no "reload" is required of the component tree (Not updating model), is there a way to pass information between controllers without going through the hoops of creating a new model with the necessary information?

For instance I have a "pager" component (contains a horizontal stack layout whose view a `UIScrollView`) which contains "pages". Each page takes the entire width, (the scrollview.frame.size.width). A PagerComponent only contains PageComponents by design.

The 'PagerComponentController' is set as the scroll view's delegate.

When the pager is built, the 'PagerComponentController' sets the scroll view content size according to pages.count * scrollview.width.

When the scroll view scrolls I need to notify the pages (rather the page's controller) that the page is visible (or was scrolled out of bounds etc.).

What is the suggested way to create the connection between the pager controller and the page controller? 

This seems analogous to a UITableview-UITableviewCell relation.

**Comment by eczarny** [comment]
Could you instead notify the `PageComponent`s themselves and forward these messages to their respective component controllers?

Once a `PageComponent` scrolls into and out of view you can send messages to it like `-[PageComponent pageBecameVisible]` and `-[PageComponent pageResignedVisible]`. In response to these messages your `PageComponent`s can access their component controllers via `-[CKComponent controller]` (refer to `CKComponentSubclass.h` for this method's declaration).
