### ISSUE TITLE
How could I scroll the collection view to bottom? I have tried to set the content offset to (0,MAX_FLOAT) or scrollToItemAtIndexPath:.... but it failed.

### ISSUE THREAD

**Issue by doanthehien1986** [facebook/componentkit#541]

**Comment by adamjernst** [comment]
Hm, this sounds like an iOS `UICollectionView` question. Not sure I can help with that.

**Comment by doanthehien1986** [comment]
it can be done easily with iOS collectionview. Cause my view is UICollectionView using componentkit to render UI. I'd like to learn how to archieve this with componentkit.
