### ISSUE TITLE
Question about CKCollectionViewDataSource

### ISSUE THREAD

**Issue by danibachar** [facebook/componentkit#551]
https://github.com/facebook/componentkit/blob/master/ComponentKit/DataSources/CKCollectionViewDataSource.h

Hey guys, i'm new to componentKit and I had a few wonderings on this file.
Why does the "CKCollectionViewDataSource" have a strong reference to the collectionView? if usually there is already a viewController or another object that has a strong reference to that collectionView?

`@property (readonly, nonatomic, strong) UICollectionView *collectionView;`

You can see it on the WildGuess example, where the "WildeGuessCollectionViewController", which inherits from "UICollectionViewController", which has a strong reference to its CollectionView.

`_dataSource = [[CKCollectionViewDataSource alloc] initWithCollectionView:self.collectionView
                                               supplementaryViewDataSource:nil                                                         
                                                         componentProvider:[self class]
                                                                   context:context
                                                 cellConfigurationFunction:nil];`
 
This will cause 2 objects to hold a strong reference to the same collectionView.

**Comment by ocrickard** [comment]
It's quite acceptable to have two objects have strong refs to the same object. What we would want to avoid is a *cycle* in the references, which could cause a leak.
