### ISSUE TITLE
collectionView Crash on enqueue (ComponentKit) dataSource

### ISSUE THREAD

**Issue by danibachar** [facebook/componentkit#555]
Hey,

I'm using ComponentKit abilities on a tableView Cell, which means:
I have a viewController, which is in-charge of a classic iOS table view.
Each cell of the tableView has a collectionView and a dataSource (CKCollectionViewDataSource) controlled by ComponentKit.
Now i know it breaks the MVC concept, but when i started to code i was not too familiar with ComponentKit, so now if i want all my infrastructure to be ComponentKit i will have to make a really big refactoring (which i will, eventually), so for now I'm wondering if the crash i get is because of the way i use ComponentKit, or it might be some bug.....

So, my TableViewCell has a collectionView and dataSource controlled by ComponentKit.
Every re-use of the tableViewCell i enqueue all the components and models i need.
The crash happens (some times, I couldn't put my finger on the exact reason, I'm still investigating) in this Method:
`- (void)componentDataSource:(CKComponentDataSource *)componentDataSource
          hasChangesOfTypes:(CKComponentDataSourceChangeType)changeTypes
        changesetApplicator:(ck_changeset_applicator_t)changesetApplicator
`

I used to get 2 kind of crashed crashes, so I added a "try and catch" (in the componentKit infrastructure), and the most common exception that I got was:

`"Fatal Exception: NSInternalInconsistencyException
request for index path for global index 3458764514182061700 when there are only 3 items in the collection view."`

Which was weird, because i followed the infrastructure and looked at the indexes i passed in every level and i could never see an index that was out of the range that i supplied.

After I added the "try and catch" the crashed dropped dramatically, but i still get one crash though:

Here is the backTrace:
`thread 1: tid = 0x6f37, 0x000000010a725a43 UIKit-[UICollectionViewData layoutAttributesForItemAtIndexPath:] + 248, queue = com.apple.main-thread, stop reason = EXC_BAD_ACCESS (code=1, address=0x7fd550bebe80) 

frame 0: 0x000000010a725a43 UIKit-[UICollectionViewData layoutAttributesForItemAtIndexPath:] + 248 

frame 1: 0x000000010a725c36 UIKit-[UICollectionViewData layoutAttributesForGlobalItemIndex:] + 57 

frame 2: 0x000000010a6e0ab5 UIKit-[UICollectionView _viewAnimationsForCurrentUpdate] + 5060

frame 3: 0x000000010a6e500c UIKit__62-[UICollectionView _updateWithItems:tentativelyForReordering:]_block_invoke1656 + 197

 frame 4: 0x0000000109f00680 UIKit+[UIView(Animation) performWithoutAnimation:] + 65 

frame 5: 0x000000010a6e43b7 UIKit-[UICollectionView _updateWithItems:tentativelyForReordering:] + 3241

 frame 6: 0x000000010a6df148 UIKit-[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:] + 15572 

frame 7: 0x000000010a6e6497 UIKit-[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 415

 frame 8: 0x000000010a6e62d5 UIKit-[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 74 

frame 9: 0x000000010a6e6278 UIKit-[UICollectionView performBatchUpdates:completion:] + 53

frame 10: 0x00000001077ee9e5 ComponentKit-[CKCollectionViewDataSource componentDataSource:hasChangesOfTypes:changesetApplicator:](self=0x00007fd8e2b3ed60, _cmd="componentDataSource:hasChangesOfTypes:changesetApplicator:", componentDataSource=0x00007fd8e2b40dc0, changeTypes=9, changesetApplicator=0x00007fff5a4b4f10) + 245 at CKCollectionViewDataSource.mm:180 

frame 11: 0x0000000107818364 ComponentKit-CKComponentDataSource _processChangeset: + 964 at CKComponentDataSource.mm:351 

frame 12: 0x0000000107817ec5 ComponentKit-[CKComponentDataSource _componentPreparationQueueDidPrepareBatch:sections:](self=0x00007fd8e2b40dc0, _cmd="_componentPreparationQueueDidPrepareBatch:sections:", batch=5 elements, sections=0x00007fd8e2b44320) + 2037 at CKComponentDataSource.mm:308 

frame 13: 0x00000001078174d3 ComponentKit43-[CKComponentDataSource _enqueueChangeset:]_block_invoke.127(.block_descriptor=, sections=0x00007fd8e2b44320, ID=12, outputBatch=5 elements, isContiguousTailInsertion=NO) + 595 at CKComponentDataSource.mm:252

frame 14: 0x000000010786129b ComponentKit__43-[CKComponentPreparationQueue 
_processJob:]_block_invoke.171(.block_descriptor=0x00007fd8e2b47860) + 267 at CKComponentPreparationQueue.mm:238 

frame 15: 0x000000010c6bed9d libdispatch.dylib_dispatch_call_block_and_release + 12 

frame 16: 0x000000010c6df3eb libdispatch.dylib_dispatch_client_callout + 8 

frame 17: 0x000000010c6c71ef libdispatch.dylib_dispatch_main_queue_callback_4CF + 1738 

frame 18: 0x0000000107e910f9 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 9 

frame 19: 0x0000000107e52b99 CoreFoundation__CFRunLoopRun + 2073 

frame 20: 0x0000000107e520f8 CoreFoundationCFRunLoopRunSpecific + 488 

frame 21: 0x000000010e552ad2 GraphicsServicesGSEventRunModal + 161 

frame 22: 0x0000000109e50f09 UIKitUIApplicationMain + 171

frame 23: 0x0000000105763865 Dondemain(argc=1, argv=0x00007fff5a4b6650) + 149 at main.m:30 

frame 24: 0x000000010c71392d libdyld.dylibstart + 1`

I'm still investigating why this happens, but maybe some here had already encounter such problem and have an idea on why it happens??

Could it be because the way I use ComponentKit? the combination of tableView cell (controller in the regular way - by an iOS dataSource), and inside of it a collectionView (controlled by ComponentKit DataSource)?

Is there a specific way to have nested collectionView with ComponentKit? i saw it on the Facebook app so I'm pretty sure its do-able.

Any help will be really appreciated, thanks!

**Comment by MDSilber** [comment]
@danibachar have you tried using CKCollectionViewTransactionalDataSource instead of CKComponentDataSource inside a UICollectionViewDataSource?

**Comment by danibachar** [comment]
Hey, @MDSilber , and thanks for the response.
I tried that today, with no success (still got the same crash) , is there a certain way to have a collectionView "hosted" on a CKCompositeComponent?(it is a view after all)

I tried to use a static function like suggested in this [link](http://componentkit.org/docs/advanced-views.html) 

Here is my code:

`static UICollectionView *innerCollectionView(void) {
    
    UICollectionViewFlowLayout *flowLayout = [[UICollectionViewFlowLayout alloc] init];
    [flowLayout setScrollDirection:UICollectionViewScrollDirectionHorizontal];
    
    UICollectionView *collectionView = [[UICollectionView alloc] initWithFrame:CGRectZero collectionViewLayout:flowLayout];
  
    collectionView.backgroundColor = [UIColor redColor];//whiteColor
    [collectionView setTag:12345];
    
    return collectionView;
}

static UIView *innerView(void) {
    UIView *v = (UIView *)innerCollectionView();
    return v;
}'`

But then is straggled with  delegating the collectionView (UICollectionVIewDelegate) to work (and sync)  properly with componentKit.

Is there a solution you guys use ? 

I'm also wondering if there is something I'm doing wrong? Am I suppose to have a "chain" of complex  CKCompositeComponent(s)?
Can a CKComponentController be a delegate of a UIViewController (created by a CKCompositeComponent) because it seem a bit tricky....

I'm sorry for all the question...but any help would be greatly appreciated.

**Comment by danibachar** [comment]
Hey again, I have another question come to mind while exploring this problem.

Is there a way to cancel an enqueueChangset/applyChangeset on one of the DataSources? (CKCollectionViewDataSource or CKCollectionViewTransactionalDataSource) or any way to sync between different dataSources?

In the case above I have several tableViewCells, which each one "holds" a collectionView (means, each collectionView is being "feed" from a different dataSource), I think that (although I remove each data source on the cell prepareForReuse method and configure a new one for each cell) there is an enqueueChangeset/applyChangeset still running while the cells was reuse

Thanks

**Comment by MDSilber** [comment]
Hey @danibachar sorry for the delayed response. As of now, there's no way to cancel an enqueued changeset in the transactional data source. However, if you want that feature, feel free to submit a pull request and we'd be happy to review it!

**Comment by ocrickard** [comment]
One thing that stands out to me is that if you're using collection views inside cells, then you may need to use https://github.com/facebook/componentkit/blob/master/ComponentKit/StatefulViews/CKStatefulViewComponentController.h to wrap your collection view. 

Since this issue is old I'm going to close out, please create a new issue if you're still hitting this.
