### ISSUE TITLE
Remove CKComponentDataSource

### ISSUE THREAD

**Issue by eczarny** [facebook/componentkit#558]
`CKComponentDataSource` has been replaced by `CKTransactionalComponentDataSource` and should be removed. Removing `CKCollectionViewDataSource` will likely require a few of steps:
- [x] Migrate the WildeGuess example app to `CKCollectionViewTransactionalDataSource`
- [x] Add `CKComponentDataSource` and friends into the internal repository so remaining migrations to `CKTransactionalComponentDataSource` can continue
- [x] Remove `CKComponentDataSource` and friends from the GitHub repository

**Comment by eczarny** [comment]
Working on a pull request that migrates WildeGuess to `CKCollectionViewTransactionalDataSource`.

**Comment by conradev** [comment]
🎉

**Comment by conradev** [comment]
What is the status of this?

**Comment by eczarny** [comment]
Still on the roadmap but not high priority. I'm hoping to getting around to wrapping this up over the coming weeks.

**Comment by conradev** [comment]
We should perhaps add a bullet point to update the documentation (because of #725, #726)

**Comment by eczarny** [comment]
@conradev our documentation is horribly outdated. I created #734 to track the relevant data source documentation updates.
