### ISSUE TITLE
Introduce CK::chain to help make combining two vectors more concise

### ISSUE THREAD

**Issue by eczarny** [facebook/componentkit#568]
Assuming `CK::chain` takes two vectors, A and B, B should appended to A iff A has children:

```
CK::chain({
  {[CKImageComponent...]},
  {[CKTextComponent...]},
}, {
  {{[CKImageComponent...]}},
});
```

Would result in:

```
{
  {[CKImageComponent...]},
  {[CKTextComponent...]},
  {[CKImageComponent...]},
}
```

However, in this case:

```
CK::chain({}, {
  {{[CKImageComponent...]}},
});
```

Would result in:

```
{}
```

**Comment by MDSilber** [comment]
@eczarny I can take a stab at this. Might be a useful way to try some easy-ish C++ stuff.

**Comment by MDSilber** [comment]
https://github.com/facebook/componentkit/pull/569

**Comment by adamjernst** [comment]
Hmm actually the behavior you describe is kinda confusing if we're going to use the name `chain`. For example, in Python `chain` just means `A + B` not `A ? (A + B) : {}`.

We should come up with another name for that behavior, perhaps.

**Comment by MDSilber** [comment]
That sounds good to me
