### ISSUE TITLE
is it suitable to control the component's state by the action passed by the parent component? 

### ISSUE THREAD

**Issue by andyqee** [facebook/componentkit#57]
Let me take the code snippet from componentKit org as example. But I found there is a little confusing, the **sender** is **CKButtonComponent**, not the **ChildComponent**. In that case the ParentComponent can not update the state of **ChildComponent**. <br> Is there any suggestion about how the update the **ChildComponent** by the **ParentComponent**
**
```
@implementation ParentComponent
+ (instancetype)new
{
  return [super newWithComponent:
          [ChildComponent
           newWithAction:@selector(someAction:)]];
}

- (void)someAction:(CKComponent *)sender
{
  // Do something
}
@end

@implementation ChildComponent
+ (instancetype)newWithAction:(CKComponentAction)action
{
  return [super newWithComponent:
          [CKButtonComponent
           newWithAction:action]];
}
@end
```

**Comment by andyqee** [comment]
I have got the the answer, but i don't know if it's the best practice.<br>
while the  **ParentComponent**  can reference the  **ChildComponent**  by the property **nextResponder** of **sender**. sender.nextResponder just point the  **ChildComponent** <br>
```
- (void)someAction:(CKComponent *)sender
{
  [sender.nextResponder updateState:^id(id) {
        return newState;
    }];
}
```

**Comment by adamjernst** [comment]
Use two different actions:

```
@implementation ParentComponent

+ (instancetype)new
{
  return [super newWithComponent:
          [ChildComponent
           newWithAction:@selector(someAction:)]];
}

- (void)someAction:(CKComponent *)sender
{
  // Do something
}

@end

@implementation ChildComponent
{
  CKComponentAction _action;
}

+ (instancetype)newWithAction:(CKComponentAction)action
{
  ChildComponent *c =
  [super newWithComponent:
   [CKButtonComponent
    newWithAction:@selector(buttonAction)]];
  if (c) {
    c->_action = action;
  }
  return c;
}

- (void)buttonAction
{
  CKComponentActionSend(_action, self);
}

@end
```

**Comment by leoschweizer** [comment]
Since I just spent some time figuring this out, I might as well share the insight: This only seems to work if the child component has a custom `ComponentController` implementation (which can be completely empty!). Otherwise, I get an exception:

```
'NSInternalInconsistencyException', reason: 'Unhandled component action myAction: following responder chain <MyComponent: 0x7feeab1e81e0> -> nil'
```

I can't judge if this is a bug or as designed ;)

**Comment by andyqee** [comment]
@leoschweizer It works ok for me . By the way do your child component hold it's own state?  if the component has no state, but you call the [childComponent updateState]. It will crash . You can review the doc http://componentkit.org/docs/state.html
