### ISSUE TITLE
WildeGuess runs on Simulator but crashes on a device

### ISSUE THREAD

**Issue by multinormal** [facebook/componentkit#574]
Hi. The WildeGuess project runs fine on the Simulator, but crashes with `dyld_fatal_error` when run on a device (tested on iPhone 6s and 5c running iOs 9.x). I am able to run developer builds of other apps on these devices. I checked out commit 4a353e49a6354937d3cb03846c634cceb131f08d.

Thanks.

**Comment by eczarny** [comment]
@multinormal Could you provide a bit more information regarding the crash? Do you have a backtrace available?

**Comment by multinormal** [comment]
Apologies — I deleted the directory some time ago now. If this is not trivially reproducible then I assume it was caused by some weirdness on my development machine, though as far as I recall it was a stock XCode release (not a beta).
