### ISSUE TITLE
About ComponentViewManager, memory management

### ISSUE THREAD

**Issue by tamnt2692** [facebook/componentkit#575]
Hi guy,
I have list view for 200 item, when i scroll from top to bottom, memory increase, add some view in reuse pool.

When i push new view controller, i want free some view in reuse pool.
Where I do that ?
Thanks

**Comment by adamjernst** [comment]
We actually don't have a mechanism for that yet! If you have any proposals, pull requests are welcome… but it's a really hard problem.

**Comment by bangquangvn** [comment]
Hi,
I'm not sure, But what happen if we iterate the 'pool' vector of all ViewReusePool instance (In ComponentViewManager.h), check whether it was unmounted or not (.ck_component == nil ?), then remove it from 'pool' if it was unmounted ?
I have tried that method in my application and it seems ok.
