### ISSUE TITLE
Animate frame size 

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#576]
I'm trying to animate a CKButton size but not getting the desired result.

Basically I have a bar containing navigation buttons (Next , Previous, Done). 

Initially I have 1 button which takes the full width of its container ("Next" button). 

I then swap it for 2 small buttons on navigation ("Previous" and "Next" buttons). 

Eventually I swap back to 1 wide button ("Done").

When the last swap occurs (from 2 buttons to 1 wide button) the UI "jumps".

I want the transition to appear much more gradual. ideally if a button is being "re-used" , its frame should animate. Ordinarily I would:

```
[UIView animateWithDuration:0.2 animations:^{
       view.frame = theFinalFrame;
}];

```

I took the example [code](http://componentkit.org/docs/animation.html) and tried to apply it (https://developer.apple.com/legacy/library/qa/qa1620/_index.html)

Sometimes the views animate , but they "start" from a (0,0) rect. 
Other times they don't animate at all.

Any example I could reference?

```
- (std::vector<CKComponentAnimation>)animationsFromPreviousComponent:(IIOCKCTAButtonComponent *)previousComponent
{
//    if ([self.configuration.id isEqual:previousComponent.configuration.id]) {
//        return {};
//    }
    NSLog(@"This component = %@, view = %@",self,self.viewContext.view);
    NSLog(@"Previous component = %@, view = %@",previousComponent,previousComponent.viewContext.view);
    
    return {{self,scaleToAppear(previousComponent.viewContext.view)}};
    //    if (previousComponent->_overlay == nil && _overlay != nil) {
    //        return { {_overlay, scaleToAppear()} }; // Scale the overlay in when it appears.
    //    } else {
    //        return {};
    //    }
}

static CAAnimation *scaleToAppear(UIView *view)
{
    CABasicAnimation *scale = [CABasicAnimation animationWithKeyPath:@"bounds"];
    scale.fromValue = [NSValue valueWithCGRect:view.bounds];
    scale.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseOut];
    scale.duration = 0.2;
//    scale.cumulative = YES;
    return scale;
}
```

**Comment by adamjernst** [comment]
Check out boundsAnimationFromPreviousComponent: — it's exactly what you're looking for!

**Comment by avnerbarr** [comment]
Thanks Adam,

I tried it as well but didn't add the testing code above since I'm not using a collection view.

From the documentation seems that it was geared towards collection views

Am wondering if several "re-mounts" occur in succession before the initial animation completed, could that be a reason for the animation not to appear or be created?


> boundsAnimationFromPreviousComponent:
> Override this method to specify how the top-level bounds of a component should animate inside a UICollectionView
