### ISSUE TITLE
Scroll the collection view

### ISSUE THREAD

**Issue by IrixVol** [facebook/componentkit#579]
Hi. Thanks for the nice product ComponentKit! 
1. How to scroll collection view to the certain IndexPath or bottom?
2. And how to stay on top when you add new records?

I tried:

```
for (int i=0; i< newObject.count; i++) {    
   MessageData* data = [[MessageData alloc] initWithMessage: newObject[i]];
   items.insert([NSIndexPath indexPathForRow: messCount inSection:0], data);
   messCount++;
}

[_dataSource enqueueChangeset:{{}, items} constrainedSize:[_sizeRangeProvider sizeRangeForBoundingSize:self.collectionView.bounds.size]];
[self.collectionView scrollToItemAtIndexPath:[NSIndexPath indexPathForRow:messCount-1 inSection:0] atScrollPosition:UICollectionViewScrollPositionBottom animated:NO];
```
and got error:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'attempt to scroll to invalid index path: <NSIndexPath: 0x7b808e80>

This occurs because "enqueueChangeset"  works asynchronously, and when "skrollToItemAtIndeksPath" is called not all items are added in datasource.

to solve this problem, I use the following trick:

```
- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath

{
          
    if ((indexPath.row == messCount-1) && (goToBottom) && (messCount>0)) {
       
        [self performSelectorOnMainThread:@selector(scrollToPos:) withObject:[NSNumber numberWithInteger:messCount-1] waitUntilDone:NO];
        goToBottom = NO;
    }
    return [_dataSource sizeForItemAtIndexPath:indexPath]; 
}

-(void) scrollToPos:(NSNumber*) number {

      [self.collectionView scrollToItemAtIndexPath:[NSIndexPath indexPathForRow:[number integerValue] inSection:0] atScrollPosition:UICollectionViewScrollPositionBottom animated:NO];
        
}
```
But this is probably not the best way to solve the problem.
And also I have not found the solve how to stay on top when you add new records.
Thank you in advance!

**Comment by adamjernst** [comment]
Look at `componentDataSource:hasChangesOfTypes:changesetApplicator:ticker:`. It's inside the component collection view data source you're using, and is responsible for actually updating the collection view. After those changes it's safe to actually scroll to the new index path.

You might want to fork the collection view data source, add a delegate, and call that delegate when that method is invoked on it.

**Comment by IrixVol** [comment]
Thanks Adam! I see with `componentDataSource:hasChangesOfTypes:changesetApplicator` I really can get the items insert completion. But when I create a class inherited from CKCollectionViewDataSource I get an error:

*** Terminating app due to uncaught exception `CKFinalClassViolationException, reason: CKCollectionViewDataSource is a final class and cannot be subclassed. MyCollectionViewDataSource`

It works if I comment line:
`CK_FINAL_CLASS([CKCollectionViewDataSource class]);`

Whether to do so?
