### ISSUE TITLE
Error in CKArrayControllerChangeset.h

### ISSUE THREAD

**Issue by alecsechechel** [facebook/componentkit#58]
Hello

I try use Example: Use it in your ViewController to power a UITableView in this link http://componentkit.org/docs/datasource-dive-deeper.html

But when I compile project I have error in CKArrayControllerChangeset.h -  'map' file not found.

How I can resolve this problem?

Thanks

**Comment by samurai91** [comment]
@alecsechechel Be sure to be using "Objective-C++" and not "Objective-C". In order to do this, you have to rename your ".m" file to a ".mm" extension.

**Comment by adamjernst** [comment]
Yep, that's the issue. Thanks @samurai91

**Comment by alecsechechel** [comment]
thanks
