### ISSUE TITLE
CKLabelComponent sometimes is shown with wrong backgroundColor 

### ISSUE THREAD

**Issue by IrixVol** [facebook/componentkit#583]
Good day!
Rarely I see small CKLabelComponent  is shown with wrong backgroundColor.

I tried to set explicitly background color for component and its parent,  but it doesn't work.
What be done to fix it?
Thank you in advance!

![likephoto](https://cloud.githubusercontent.com/assets/5245682/16412973/1db85308-3d40-11e6-80e6-56bc83681a62.png)
![likephotocode](https://cloud.githubusercontent.com/assets/5245682/16412974/1de2f1b2-3d40-11e6-9bb5-5562a443ff63.png)

**Comment by ocrickard** [comment]
Can you try to repro in an isolated test case please?

**Comment by ocrickard** [comment]
Open a new issue with an isolated test case if this is still happening!

**Comment by yupengyang** [comment]
I also run into this issue. But it's random, and cannot found an isolated test case

**Comment by pantuspavel** [comment]
Should be fixed with https://github.com/facebook/componentkit/commit/05a028f43af82f6f021c42f3ff10a741e57c7062
