### ISSUE TITLE
Question : How show UIAlertController from a CKComponentController ?

### ISSUE THREAD

**Issue by fabidona** [facebook/componentkit#586]
Hi!
I started to play with this fantastic framework, great work guys!
I cant't figure out how show an UIAlertController after a CKButtonComponent tap.
I create a subclass of CKComponentController as the guide says to coupling my CKComponent subclass, but the controller derive from NSObject and not from UIViewController so the message presentViewController... is not present.
I'm in the right way? 

In my BusinessComponent class implementation (derived from CKComponent):

```
[CKButtonComponent newWithTitles:{ {UIControlStateNormal, @"Sono un bottone"},{UIControlStateHighlighted, @"premuto"} }
                        titleColors:{ {UIControlStateNormal, [UIColor blackColor]},{UIControlStateHighlighted, [UIColor whiteColor]} }
                        images:{ }
                        backgroundImages:{ }
                        titleFont:[UIFont systemFontOfSize:18 weight:UIFontWeightMedium]
                        selected:NO
                        enabled:YES
                        action:@selector(btnBizTapped:)
                        size:{
                            .width = 200
                        }
                        attributes:{}
                        accessibilityConfiguration:{}
                        ]
```

In my BusinessComponentController implementation (derived from CKComponentController):

```
-(void)btnBizTapped:(id)sender {
    
    UIAlertController* alert = [UIAlertController alertControllerWithTitle:@"Sei sicuro ?" message:nil preferredStyle:UIAlertControllerStyleActionSheet];
    
    UIAlertAction* okAction = [UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
        
        [alert dismissViewControllerAnimated:YES completion:nil];
    }];
    
    [alert addAction:okAction];
    
    [self presentViewController...];
}
```

Moreover: How to declare the CKComponentScope in my BusinessComponent? Using a @property ?

thank you!

**EDIT:**
I figured out how to declare a scope in my Component, using 

> CKComponentScope scope(self);

 in my +new class method but the Assertion remains.

**Comment by adamjernst** [comment]
You'll need to pass the view controller into your component from above. Be sure to pass a weak reference, though (probably by sending it as a weak property on some object). Otherwise you'll set up a retain cycle.

**Comment by fabidona** [comment]
thank you Adam, I'll try soon
