### ISSUE TITLE
Accessibility Identifier should not be part of Accessibility Context

### ISSUE THREAD

**Issue by taiber** [facebook/componentkit#590]
Accessibility Identifier is, unlike its name, not an accessibility feature, but actually an automation feature used to identify elements on the screen. More context here: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIAccessibilityIdentification_Protocol/

Passing accessibilityIdentifier in as part of accessibilityContext is limiting as it only gets set if accessibility is turned on. This prevents UI tests (e.g. WebDriver) from finding elements on the screen when accessibility is off.
The correct way of passing an identifier to a component is just passing `{@selector(setAccessibilityIdentifier:), @"accessibilityId"}` in its attributes.
We have some workarounds in our library like CKButtonComponent manually setting it in its constructor but that's only more confusing as it only works sometimes and when remembering to set it (https://github.com/facebook/componentkit/blob/master/ComponentKit/Components/CKButtonComponent.mm#L149) 

We should remove accessibilityIdentifier from accessibilityContext to prevent people from making that mistake.

**Comment by ocrickard** [comment]
Sounds like this is resolved now?
