### ISSUE TITLE
Question - How to create equally sized components

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#597]
Question regarding stack layouts:

I need 2 buttons in a horizontal stack layout to have equal widths constrained to the the wider of the 2. 
In general. the width of a button is dictated by the text it contains and its attributes (font, padding, etc.). 
In a case where a button has short text the button is "narrow" , and in a case where the text is long the button be wide.

I would like the short button to "flexGrow" to equal the width of the wider button, but I don't want the wider button to grow. The wider of the 2 buttons should be pinned to its normal dimension (width). 

```
+---------------------------------------------------------------------------------+
|                                                                                 |
|                                                                                 |
|    +--------------------------------+       +-----------------------------+     |
|    |                                |       |                             |     |
|    |                                |       |                             |     |
|    |                                |       |                             |     |
|    |           Match widths         |       |         Match widths        |     |
|    |                                |       |                             |     |
|    |                                |       |                             |     |
|    |                                |       |                             |     |
|    +--------------------------------+       +-----------------------------+     |
|                                                                                 |
|                                                                                 |
+---------------------------------------------------------------------------------+

```

Can  I achieve this behavior through a CKStackComponent? ("flexGrow" the shorter button and limit its width according to a sibling?)

**Comment by adamjernst** [comment]
Good question! As far as I know, flexbox can't achieve this. (I guess I might want to ask in a flexbox expert forum to be sure — maybe there is a way?)

The good news: you can write your own layout component by overriding `computeLayoutThatFits:` and doing exactly what you want. Give it a try.
