### ISSUE TITLE
Best practices for large collection of objects in CKCollectionViewDataSource

### ISSUE THREAD

**Issue by siuying** [facebook/componentkit#60]
I have a very large collection of objects, kind of like Facebook feed, and would like to present it  with ``CKCollectionViewDataSource``. 

Typically I'd use ``NSFetchedResultsController`` where I can listen for changes on context for a  ``NSFetchRequest``. Do you have any recommendation to do it in ``ComponentKit`` with data backed by Core Data?

**Comment by qiaoyan** [comment]
Did you try "batchsize" in core data?

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by ocrickard** [comment]
This is not really componentkit-specific. You should handle the large number of items in the same way you would with any other collection view. Ensure batching of insertions, and you're probably going to be OK.
