### ISSUE TITLE
White flashing in Multi-Photo Detail ScrollView

### ISSUE THREAD

**Issue by mosesoak** [facebook/componentkit#608]
Seen in: FB  iOS App v62.0

Note: I've reported this through the app and received a "we are ignoring your request" type of form response. Posting my 2nd attempt here in hopes that the bug can be handled by this team, thanks!

Repro:

1. Navigate to News Feed
2. Locate a multi-photo mosaic post from a Facebook member - tap on first photo to enter detail view
2. Scroll down in detail view

Expected:

- Stable viewing experience 

Actual:

- Each photo plays a 'white flash' animation once as it becomes centered in the viewport
- specifically, when first entering the view the photo is fully visible, but then blanks out and fades in

Comments:

- it's unclear whether this effect is intentional. It feels like a bug, perhaps the photo was supposed to be white until in view and then fade up?
- if it is intentional, it's super annoying. After looking at a few pictures it becomes jarring to have each one 'flash' just as your eye is focusing on it.
- feels like a glaring UX problem that should have been fixed promptly, but has persisted for several versions

**Comment by ocrickard** [comment]
Thank you for reporting the issue, but this is not the place for product feedback on Facebook. If you believe a bug is due to the ComponentKit framework, please attempt to find a minimal repro with an example project and file an issue.
