### ISSUE TITLE
Stack layout may violate child layout constraints

### ISSUE THREAD

**Issue by ocrickard** [facebook/componentkit#619]
Here is a minimal test case:

```
- (void)testNestedStackLayoutStretchDoesNotViolateWidth
{
  CKStackLayoutComponent *c =
  [CKStackLayoutComponent
   newWithView:{}
   size:{}
   style:{
     .direction = CKStackLayoutDirectionVertical
   }
   children:{
     {
       [CKStackLayoutComponent
        newWithView:{
          [UIView class],
          {
            {@selector(setBackgroundColor:), [UIColor blueColor]}
          }
        }
        size:{
          .width = 100,
          .height = 100
        }
        style:{
          .direction = CKStackLayoutDirectionVertical,
          .alignItems = CKStackLayoutAlignItemsStretch
        }
        children:{
          {
            [CKComponent
             newWithView:{
               [UIView class],
               {
                 {@selector(setBackgroundColor:), [UIColor redColor]}
               }
             } size:{
               .width = 50,
               .height = 50
             }]
          }
        }]
     }
   }];
  static CKSizeRange kSize = {{300, 0}, {300, INFINITY}};
  CKSnapshotVerifyComponent(c, kSize, nil);
}
```

<img width="300" alt="testnestedstacklayoutstretchdoesnotviolatewidth 2x" src="https://cloud.githubusercontent.com/assets/857665/18004490/49b2a350-6b62-11e6-84a8-5b2680ecb661.png">

The problem here is that the stack layout is being told to stretch, and that means that it provides a layout constraint of min = 100 and max = 100 to its child. That child then clamps to that size, and uses it directly. The flexbox spec says that the flex container should attempt to stretch, while respecting the constraints of the children. We should inspect the child size in the flex process and likely provide a constraining size to the child that allows it to respect its own constraints. It's a bit ugly, but is truer to the spec.

**Comment by ocrickard** [comment]
https://github.com/facebook/componentkit/pull/620

**Comment by eczarny** [comment]
#620 has been merged. Closing this out.
