### ISSUE TITLE
Unmount doesn't call attribute unapplicator

### ISSUE THREAD

**Issue by jaltreuter** [facebook/componentkit#621]
We're not calling the unapplicator in `[CKComponent unmount]`, despite the [comment in CKComponentInternal which states that as its contract](https://github.com/facebook/componentkit/blob/master/ComponentKit/Core/CKComponentInternal.h#L48). The only time I can find us calling unapplicator() is actually when applying a new set of attributes.

**Comment by jaltreuter** [comment]
Here's a unit test that currently fails:

```
- (void)testThatUnmountingViewWithAttributeRequiringUnapplicationCallsUnapplicator
{
  NSMutableSet *appliedValues = [NSMutableSet set];
  NSMutableSet *unappliedValues = [NSMutableSet set];
  CKComponentViewAttribute attrWithUnapplicator("test", ^(id view, id val){
    [appliedValues addObject:val];
  }, ^(id view, id val){
    [unappliedValues addObject:val];
  });

  CKComponent *testComponent1 = [CKComponent newWithView:{[UIView class], {{attrWithUnapplicator, @1}}} size:{}];

  CKComponentLifecycleManager *m = [[CKComponentLifecycleManager alloc] init];
  [m updateWithState:{
    .layout = [testComponent1 layoutThatFits:{{0, 0}, {10, 10}} parentSize:kCKComponentParentSizeUndefined]
  }];

  UIView *container = [[UIView alloc] init];
  [m attachToView:container];

  XCTAssertEqualObjects(appliedValues, [NSSet setWithObject:@1], @"Expected @1 to be applied");
  XCTAssertEqualObjects(unappliedValues, [NSSet set], @"Expected nothing to be unapplied");

  [m detachFromView];

  XCTAssertEqualObjects(unappliedValues, [NSSet setWithObject:@1], @"Expected @1 to be unapplied");
}
```

**Comment by ocrickard** [comment]
Yep, so sadly it's the docs on that internal header that are incorrect:

https://github.com/facebook/componentkit/blob/master/ComponentKit/Core/CKComponentInternal.h#L48

It took me awhile to remember, but I realized today that the unapplicator is actually called only when the view leaves the reuse pool:

https://github.com/facebook/componentkit/blob/master/ComponentKit/Core/CKComponentViewAttribute.h#L29

I'm looking for an alternate solution to the long press gesture recognizer problem. It's clear that the recognizer attribute is flawed.

**Comment by jaltreuter** [comment]
I guess that makes sense from a performance perspective since unmount can get called frequently, although I'd be curious to see if there are other uses of the unapplicator block where it's expected to be called on unmount as opposed to on the destruction of the view.  I opened a [new issue for the specific case of gesture recognition](https://github.com/facebook/componentkit/issues/622) and would be happy to hear more of your thoughts on a solution.

**Comment by ocrickard** [comment]
@adamjernst I'd love to hear your thoughts on if it would be possible to run the unapplicator earlier. Have we conducted any tests to see what the perf implications would be?

**Comment by adamjernst** [comment]
As far as I know we don't have any explicit performance tests, no.

However note that view attributes have a lifetime that is very different than components...

**Comment by ocrickard** [comment]
Alright, I think we're just going to fix the gesture recognizer issue by not firing when a view doesn't have a component. It's not ideal, but I don't really want to add such complexity to the framework to fix a bug that's only hit us in a single callsite within the framework.

**Comment by ocrickard** [comment]
Ahh, that's right, this issue concerns the documentation. I'll try to fix this today.
