### ISSUE TITLE
Run Examples>WildeGuess fail

### ISSUE THREAD

**Issue by isRaining** [facebook/componentkit#639]
dyld: Library not loaded: /Library/Frameworks/ComponentKit.framework/ComponentKit
  Referenced from: /var/containers/Bundle/Application/56FC64CE-7F14-4BB0-B510-8C9B342049FE/WildeGuess.app/WildeGuess
  Reason: image not found

**Comment by eczarny** [comment]
@isRaining how are you building the example app? Are you opening the `WildeGuess.xcodeproj` Xcode project and running in an iPhone simulator?

**Comment by isRaining** [comment]
no iPhone simulator，run my real iPhone

**Comment by isRaining** [comment]
Use Xcode Version 7.3.1 (7D1014)

and open Examples/WildeGuess/WildeGuess.xcodeproj

![a](http://img.blog.csdn.net/20160907104745021)

**Comment by eczarny** [comment]
Does WildeGuess work in the simulator? Why do you need to run the example app on device?

**Comment by isRaining** [comment]
Thanks!

Run simulator success
