### ISSUE TITLE
CKComponentController::componentTreeWillAppear not called

### ISSUE THREAD

**Issue by myeyesareblind** [facebook/componentkit#65]
Those methods are not called on CKComponentSubclass:
- (void)componentDidAcquireView
- (void)componentWillRelinquishView
- (void)componentTreeWillAppear
- (void)componentTreeDidDisappear
Not sure if I am missing something

**Comment by adamjernst** [comment]
They're called on `CKComponentController`, not `CKComponent` instances.

**Comment by adamjernst** [comment]
Ah I see. Can you submit an example project?

**Comment by myeyesareblind** [comment]
This does happen in Example project, simply add InteractiveQuoteComponentController with those methods.
-(void).*mount methods are properly called, those 4 - not.

**Comment by adamjernst** [comment]
`componentDidAcquireView` and `componentWillRelinquishView` will not be called because `InteractiveQuoteComponent` itself does not have a view. (Only its sub-component `CKStackLayoutComponent` does.)

However `componentTreeWillAppear` and `componentTreeDidDisappear` should be called. That warrants further investigate.

**Comment by adamjernst** [comment]
Verified this is a bug. Assigning @benlodotcom to fix.

**Comment by adamjernst** [comment]
Actually I'll take it

**Comment by myeyesareblind** [comment]
It works, thank you.
There is another thing now.
Currently, if you ask dataSource for not existing indexPath, it will crash since there is direct access to NSArray[index].
What happens for me is that I delete a cell and receive didEndDisplayingCell, the app crashes on announceDidDisappearForItemAtIndexPath because the model was deleted.
It might be better to simply return nil I guess.
Minor thing since I can actually check in my model, but still...

**Comment by adamjernst** [comment]
That's bad — opened #129 to track.

**Comment by ThanhTurin** [comment]
@myeyesareblind Hi guy! Can you help me to submit your example project to me? Thank you very much!

**Comment by myeyesareblind** [comment]
@ThanhTurin what exact issue are you working on? componentTreeWillAppear is fixed now

**Comment by ThanhTurin** [comment]
@myeyesareblind : I'm sorry about my late reply! I had the same problem 3 days ago. But i already fixed it. Thank you for your listening :)
