### ISSUE TITLE
[Question] Creating Scrollable Component

### ISSUE THREAD

**Issue by esam091** [facebook/componentkit#651]
I'm considering making something like this:

``` ObjC
[HorizontalScrollingComponent
  newWithComponent:component];
```

The behavior I expect is the created UIScrollView will set the content width equal to the contained component's width. In order to achieve this, I resized the content view in the component's controller like this:

``` ObjC
@implementation HorizontalScrollComponentController

- (CKSizeRange)sizeRange {
        return CKSizeRange(
                           CGSizeMake(0, self.view.frame.size.height),
                           CGSizeMake(INFINITY, self.view.frame.size.height)
                           );
}

- (void)didMount {
    [super didMount];

    UIScrollView *scrollView = (UIScrollView *)self.view;

    HorizontalScrollComponent *component = (HorizontalScrollComponent *)self.component;
    CKComponent *content = component.content;

    scrollView.contentSize = [content layoutThatFits:[self sizeRange] parentSize:scrollView.frame.size].size;
}

@end
```

It works just as I expected for now, but I do have a few questions:
1. Is there anything wrong with using contained component's `layoutThatFits` to get the content size?
2. In order to use component controller, I have to set the component's scope, and since I can have multiple HorizontalScrollComponentControllers at a time, I have to set the scope using some random id, but I think it's weird to set the id in the component just for the sake of putting scope `[HorizontalScrollComponentController newWithScopeId:@"randomScopeId" component:component]`. Any better solution for this?

**Comment by ocrickard** [comment]
Ryan would you be interested in tackling this question?

**Comment by ryanrhee** [comment]
@esam091 sorry for the lack of communication, we promise we're not ignoring your question :) sit tight; we'll get you an answer soon!

**Comment by ryanrhee** [comment]
@esam091: Discussed this w/ @ocrickard a bit. I think your approach is pretty canonical for computations that aren't related to layout, but since your example is specifically about layout, we can do better.

ComponentKit already provides a way to do layout: you can enhancement-override `-computeLayoutThatFits:` and figure out your size in there. This is mentioned [in the docs](http://componentkit.org/docs/never-subclass-components.html)[1] and [in header comments](https://github.com/facebook/componentkit/blob/master/ComponentKit/Core/CKComponentSubclass.h#L39).

There's nothing **wrong**, per se, with using a contained component's `layoutThatFits` to get the content size, although [our recommendation](https://github.com/facebook/componentkit/blob/master/ComponentKit/Core/CKComponentSubclass.h#L40) is to use [CKComputeComponentLayout](https://github.com/facebook/componentkit/blob/master/ComponentKit/Core/CKComponentLayout.h#L77) instead.

By computing size in that particular method, you obviate the need for component controllers, so this is the "better solution" in response to your second question.

I'm going to close this; feel free to re-open if you think I haven't answered your question. Please open a new issue if you have specific feedback or questions about how to implement a container by subclassing `-computeLayoutThatFits:`.

HTH!

[1]: _See note starting with "If you need to perform advanced layout"_

**Comment by esam091** [comment]
Thanks a lot for answering @ryanrhee, but I'm encountering a problem right now. I can't find the parent size for the layout computation, because the horizontal scroll view's height depends on the parent, not explicitly defined. I've tried using the `CKComponentViewAttribute`'s applicator function, but it seems that the scroll view's size won't be defined until layout phase. That's the reason why I'm using the component controller.

**Comment by ryanrhee** [comment]
> the horizontal scroll view's height depends on the parent, not explicitly defined.

Can you explain in a bit more detail what you mean by that? In particular, what, exactly, is "not explicitly defined"?

**Comment by esam091** [comment]
I mean if the height is explicitly defined in points like this, the content size can be calculated using the size range from (0, height) to (infinity, height) like the sample code from the first post.
```ObjC
return [HorizontalScrollingComponent
            newWithComponent:childComponent
            size:{ .height = 100 }];
```

But what if the height is defined like this:
```ObjC
return [HorizontalScrollingComponent
            newWithComponent:childComponent
            size:{ .height = CKRelativeDimension::Percent(.5) }];

// or maybe this one
return [CKStackLayoutComponent
            newWithView:{}
            size:{ .height = 300 }
            style:{
                .direction = CKStackLayoutDirectionVertical,
                .alignItems = CKStackLayoutAlignItemsStretch
            }
            children:{
                {
                    [HorizontalScrollingComponent
                     newWithComponent:content1
                     size:{}],
                    .flexBasis = 0.3333
                },
                {
                    [HorizontalScrollingComponent
                     newWithComponent:content2
                     size:{}],
                    .flexBasis = 0.3333
                },
                {
                    [HorizontalScrollingComponent
                     newWithComponent:content3
                     size:{}],
                    .flexBasis = 0.3333
                },
            }];
```

I don't see how I can calculate the size range in the component creation phase.

**Comment by ryanrhee** [comment]
@esam091 I see.

Can you see if you can override 

```
- (CKComponentLayout)computeLayoutThatFits:(CKSizeRange)constrainedSize
                          restrictedToSize:(const CKComponentSize &)size
                      relativeToParentSize:(CGSize)parentSize;
```

instead and use those parameters to figure out the height there?

**Comment by esam091** [comment]
Haven't had the time to try for now, but looking at the `CKComponent`'s [implementation](https://github.com/facebook/componentkit/blob/a29b25e1d2cb234329ab1c4f13016f41da103eab/ComponentKit/Core/CKComponent.mm#L240-L243), I think it's possible to return an entirely new component with computed content size rather than the current one.

```ObjC
- (CKComponentLayout)computeLayoutThatFits:(CKSizeRange)constrainedSize
                          restrictedToSize:(const CKComponentSize &)size
                      relativeToParentSize:(CGSize)parentSize {
  CGSize computedContentSize = ...;

  return {[HorizontalScrollingComponent
    newWithViewAttributes: {
     {@selector(setContentSize:), computedContentSize}
    }], calculatedSize};
}
```

Seems like a hack to me, but if you think there'll be no problem, I'll be fine with that :)

**Comment by ocrickard** [comment]
Building a component within layout is not recommended since the scope tree is complete, and immutable at the point the layout is computed, so certain things just won't work if you take this approach. The sub-component needs to be created in the +new method.

**Comment by ocrickard** [comment]
I implemented a scroll component in https://github.com/facebook/componentkit/pull/772 Feel free to take a look there.
