### ISSUE TITLE
CKCompositeComponent returns nil with non-empty view configuration

### ISSUE THREAD

**Issue by ocrickard** [facebook/componentkit#655]
CKCompositeComponent can return nil with a nil component, even though a non-empty view configuration could be provided. In this case it feels like we should check if the view configuration is empty before returning nil. If you provide `{[UIView class], {{@selector(setBackgroundColor:), [UIColor redColor}}}`, then we shouldn't just return a nil component.

**Comment by adamjernst** [comment]
Maybe, I'm kinda iffy on the special-case-y-ness of that though.

¯\_(ツ)_/¯

Not sure what we *should* do!

**Comment by ocrickard** [comment]
Sure, though that solution I believe is the one that you proposed to me initially when we talked about this.

The alternative is to remove the early return. I would argue that is the most correct behavior, since it will allow creation of a component controller even if you have no child component. This has bitten us recently in at least 3 locations internally.

**Comment by adamjernst** [comment]
Oh definitely agree, I'm never consistent in my opinions though :P

**Comment by ocrickard** [comment]
I'm gonna close this. I think this should be a reason to subclass CKComponent itself. CKCompositeComponent has a simple contract that we don't need to complicate.
