### ISSUE TITLE
Using ComponentKit for the Whole Page

### ISSUE THREAD

**Issue by esam091** [facebook/componentkit#656]
From what I've seen so far, it seems that ComponentKit is only used for use cases similar to News Feed: an infinite list of items in which every cell has different layouts. Do you guys at Facebook use ComponentKit anywhere else in the app? As our app's design is getting more and more complex, using interface builder and auto layout is becoming more painful, so we're trying to find some alternatives. Is it recommended to use ComponentKit to layout the whole view controller's page?

**Comment by matin0728** [comment]
Try CKComponentHostingView, which can be used as collection view's header/footer view.

**Comment by ocrickard** [comment]
Yep, we actually use ComponentKit for many full-screen interfaces in the main FB app. It's absolutely possible to use ComponentKit to layout the whole view controller's page. We do need some more blog posts/documentation on how to do this though.

Hosting view is a good place to start.

Let me know if you have any more specific questions!

**Comment by esam091** [comment]
Thanks, now I have more confidence to do this approach.

One thing I'm curious about, is how do you guys iterate the UI development? On my code base, it took about 45 seconds from pressing run button until changes appear on screen, and pretty sure this could take much longer for you guys. The iteration time is much slower compared to React Native, and it can be painful to wait if you're building complex layout.

One way I could think of is using some [injection tools](https://github.com/johnno1962/injectionforxcode), but XCode 8 makes it very difficult to do injection.
