### ISSUE TITLE
animationsFromPreviousComponent is not called after update state

### ISSUE THREAD

**Issue by matin0728** [facebook/componentkit#668]
The "scaleToAppear" animation for popover view in demo application is not visible.

**Comment by ocrickard** [comment]
@eczarny is this due to moving the demo project to the transactional datasource? I remember hearing that we don't support animation transitions with this datasource.

**Comment by eczarny** [comment]
I'll check.

**Comment by eczarny** [comment]
#637 fixes this issue.
