### ISSUE TITLE
Potential race condition in function registerAnnounceableEventsForController of CKComponentScopeRoot ?

### ISSUE THREAD

**Issue by bigbangvn** [facebook/componentkit#669]
```
I have lots of crash on my Crashlytics in this function (registerAnnounceableEventsForController). I didn't override componentTreeWillAppear or componentTreeDidDisappear. I can't find any reason here, is it possible a race condition?
```

Top stack of my crash on Crashlytics:

"Crashed: org.componentkit.component-preparation-queue.concurrent
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000001a1b48af769  
-[CKComponentScopeRoot registerAnnounceableEventsForController:]  
+[CKComponentScopeFrame childPairForPair:newRoot:componentClass:identifier:initialStateCreator:stateUpdates:]  
CKComponentScope::CKComponentScope(objc_class_, objc_object_, objc_object\* () block_pointer) + 4308897044"

**Comment by ocrickard** [comment]
I assume your crash reporting system reports *all* threads? Can you please provide the raw crash stack? Alone this is difficult to debug. We are not seeing this crash internally.

**Comment by bigbangvn** [comment]
Hi !
Yes, i have all threads reports of the crash. But i still can't reproduce this problem.

[com.bangalo_issue_494326_crash_e70ea115db464021bb64d15162707820.txt](https://github.com/facebook/componentkit/files/561077/com.bangalo_issue_494326_crash_e70ea115db464021bb64d15162707820.txt)

**Comment by ocrickard** [comment]
It's not obvious to me where this crash is coming from, but you are using the old datasource, which had a number of races. Can you try updating to the new datasources and report back if the crash doesn't go away?
