### ISSUE TITLE
Question - Insetting a CKTextComponent text

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#673]
Is there a way to add content insets to a `CKTextComponent` (Without wrapping it with an inset component)?

I'm doing something similar to a `CKButtonComponent` by setting contentEdgeInsets in the attributes section of the button:
```
attributes: { 
...
{@selector(setContentEdgeInsets:),[NSValue valueWithUIEdgeInsets:configuration.viewPadding]},
...
}
```

**Comment by eczarny** [comment]
@avnerbarr any particular reason why you wouldn't want to wrap the text component in an inset component?

**Comment by avnerbarr** [comment]
Because I want to set background colors , border colors etc on the view and wouldn't be convenient to do on the inset component.

**Comment by ocrickard** [comment]
Yeah, sadly we don't expose a way to do this directly. We'd be open to a PR that adds lineFragmentPadding configuration to the options struct, though that's actually kind of different from your question here.

For now, you have to use an inset component.
