### ISSUE TITLE
How can I assign accessibility labels for the CKLabelComponent?

### ISSUE THREAD

**Issue by aorekhov** [facebook/componentkit#677]
Hello everyone

I have the following code fragment. But in app this element will have name equals to his label.

How can I assign accessibilityLabel for this kind of element?

> [CKLabelComponent
                            newWithLabelAttributes:{
                                .string = [status likeCounter],
                                .font = [UIFont slf_fontMuseoSansOfSize:12 weight:MuseoSansFontWeight300],
                                .lineBreakMode = NSLineBreakByTruncatingTail,
                                .color = [context.theme textBlackColor],
                                .alignment = NSTextAlignmentLeft
                            }
                            viewAttributes:{
                                {@selector(setBackgroundColor:), [UIColor clearColor]},
                                {@selector(setUserInteractionEnabled:), @NO},
                                {@selector(setAccessibilityLabel:), @"LikeCounter"}
                            }
                            size:{}]

**Comment by ocrickard** [comment]
So with CKLabelComponent we tried to keep the API surface-area to a minimum, so we default you to using the string in the label as the accessibility string. We'd be open to a PR if you'd like to add the accessibility label as a parameter in the options struct.

Alternatively you can always use CKTextComponent and set the accessibility context on its option struct.
