### ISSUE TITLE
CKComponentAction with parameters

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#716]
Is it possible to create a CKComponentAction (on a CKButtonComponent for instance) that will accept parameters. For instance if I want a lightweight component that can open a deeplink I don't need the overhead of creating a controller that will respond to the action and inturn open a deeplink.

An example could be
NSURL *deeplink = ....
CKButtonComponent *button  = [self makeButton.... deeplinkURL:deeplink];

- (CKButtonComponent *) makeButton ... deeplinkURL:(NSURL *)URL 
{
return [CKButtonComponent
          newWithTitles:titles
          titleColors:titleColors
          images:{}
          backgroundImages:{}
          titleFont:nil
          selected:NO
          enabled:YES
          action:{@selector(openURL:),URL}
          size:{}
          attributes:viewAttributes
          accessibilityConfiguration:{}];
}

**Comment by conradev** [comment]
Yes, you can trampoline the action on the component itself, with no need for a controller:

```objc
@implementation DeepLinkComponent {
    CKTypedComponentAction<NSURL *> _action;
    NSURL *_url;
}

+ (instancetype)newWithURL:(NSURL *)url
                    action:(CKTypedComponentAction<NSURL *>)action {
    CKComponentScope scope(self);
    DeepLinkComponent *c =
    [super newWithComponent:
     [CKButtonComponent
      newWithTitles:{{UIControlStateNormal, @"Open URL"}}
      titleColors:{}
      images:{}
      backgroundImages:{}
      titleFont:nil
      selected:NO
      enabled:YES
      action:{scope, @selector(buttonTapped:)}
      size:{}
      attributes:{}
      accessibilityConfiguration:{}]];
    
    if (c) {
        c->_action = action;
        c->_url = url;
    }
    
    return c;
}

- (void)buttonTapped:(CKButtonComponent *)sender {
    if (_action)
        _action.send(self, _url);
}

@end
```

```objc
DeepLinkComponent *c = [DeepLinkComponent newWithURL:[NSURL URLWithString:@"https://github.com/facebook/componentkit/issues/716"]
                                              action:{[UIApplication sharedApplication], @selector(openURL:)}];
```

Let me know if that answers your question!

**Comment by avnerbarr** [comment]
Thanks Conrad,

I've been using a very similar pattern,  but what I wanted is to eliminate the need for creating a wrapper component in the case where the only modification is to pass a parameter up the responder chain (automatically).


From my understanding, conceptually the responder chain for an action i.e. "openURL" is something like:

`action->component->componentController->componentViewInstance->superComponent->superComponentController->....->ViewController? (If it follows UIResponder?)->....->UIApplication`

As we know, UIApplication should respond to [UIApplication:openURL:] and would get the "URL" parameter forwarded to it.

BTW. CKTypedComponentAction doesn't seem to be part of the latest pod release 
pod 'ComponentKit'  is returning 0.15.0

Searching for CKTypedComponentAction doesn't yield any results. Is this part of an upcoming version?

**Comment by conradev** [comment]
`CKTypedComponentAction` landed in November, which doesn't put it in any current release yet. Not sure when the next one is! The new action API actually eliminates the need for the responder chain.

Even with the new API, It is not possible to configure a constant parameter (or capture any other context) when creating a `CKComponentAction`, like you would like to do.

**Comment by ocrickard** [comment]
Argh, we've been meaning to do a new version for months. I'll cut one this week. We use master internally.

Re capturing parameters: we don't allow strongly capturing vars, and sadly this is intentional. It disallows actions to form retain cycles since if we allowed capture, inevitably a parent would pass down something that would form a cycle.

There has been discussion of allowing blocks to be used as actions, and it would be trivial to implement, but has been found to be too error-prone at the moment.
