### ISSUE TITLE
ComponentKit.podspec lint failed

### ISSUE THREAD

**Issue by wuwen1030** [facebook/componentkit#722]
```shell
pod spec lint ComponentKit.podspec --verbose
```
![image](https://cloud.githubusercontent.com/assets/3377567/21920638/668adc82-d99d-11e6-8957-fcb310ad1ef4.png)

**Comment by ocrickard** [comment]
Ugh, more issues with cocoapods. @eczarny mind taking a look at this at some point?

**Comment by wuwen1030** [comment]
It turned out that this is an issue of cocoapods (>= 1.0.0).

**Comment by ocrickard** [comment]
OK, cool, I'll close this then.
