### ISSUE TITLE
Scroll annoying fade animation

### ISSUE THREAD

**Issue by razvanpaul** [facebook/componentkit#726]
I have a collection view and an infinity scroll implemented. Everything is well, but I encounter this issue: when new data is coming and I make some inserts, I see a fade/ crossfade animation which flickers the collection view for something like 0.5-1 seconds.

I've tried the solution proposed in #315 it does not work. Can you tell me what can I do please to disable the animation?

**Comment by razvanpaul** [comment]
UPDATE

[Here](https://www.dropbox.com/s/7o4mqkonfezq5ns/recording2.mov?dl=0) is a recording from the issue I encountered.

**Comment by conradev** [comment]
The proper solution proposed in #315 is to use `CKCollectionViewTransactionalDataSource`, have you tried that?

**Comment by razvanpaul** [comment]
@conradev Thanks for the tip, I will try to implement it and close the issue if it will be solved.

**Comment by conradev** [comment]
You can see how to do this best in the `WildeGuess` example code: https://github.com/facebook/componentkit/blob/4129a7efa77124a7a8704ebf5079c42917906659/Examples/WildeGuess/WildeGuess/WildeGuessCollectionViewController.mm#L99-L111

**Comment by razvanpaul** [comment]
@conradev I've tried to use exactly those methods, but they aren't defined in the `CKCollectionViewTransactionalDataSource`
I get the **No visible @interface for 'CKCollectionViewTransactionalDataSource' declares the selector 'announceWillDisplayCell:** error

I'm using the last version, 0.15.

**Comment by conradev** [comment]
Ah yes, those were introduced recently (after 0.15). You actually don't need to call those methods unless you rely on `-[CKComponentController componentTreeWillAppear]`/`-[CKComponentController componentTreeDidDisappear]`, so you should be fine without that code!

**Comment by razvanpaul** [comment]
Thank you very much, now it worked and I'm using `CKCollectionViewTransactionalDataSource ` . Unfortunately, neither this bug nor #725 it's resolved. I encounter the same annoying fade while scrolling and the video sibling component gets remounted when I call `updateState`.

**Comment by ocrickard** [comment]
If you're still seeing this issue with the transactional datasource, we need a repro case to continue. Please try to repro this in the WildeGuess example project and we can try to help you debug.

**Comment by ocrickard** [comment]
Closing, we need more information. If a failing test or repro in WildeGuess is submitted, will re-open.
