### ISSUE TITLE
CKStatefulViewComponentController AVPlayer KVO remove observer

### ISSUE THREAD

**Issue by razvanpaul** [facebook/componentkit#729]
Hello

I encounter a big issue using the `CKStatefulViewComponentController` in coalition with the AVPlayer class and the KVO system of iOS. Basically, the Component Kit does not allow me to remove the observer (which is the controller). I have the following function:

```
- (void) removePlayerStatusNotification {
    SCPostVideoPartStatefulComponent *component = (SCPostVideoPartStatefulComponent*) self.component;
    @try {
        [component.player removeObserver: self forKeyPath: @"status"];
        [component.player removeObserver: component.nextResponder forKeyPath: @"status"];
    }
    @catch (NSException *exception){
        NSLog(@"%@", exception.description);
    }
}
```
I'm using the above function before any `addObserver` call, in the `dealloc` function of both the component and the controller and also in the `willRelinquishStatefulView` method.

This is how I add the observer:

```
[component.player addObserver: component.nextResponder forKeyPath: @"status" options: 0 context: nil];
```

Observations:
- I get the **__cfnotificationcenter_is_calling_out_to_an_observer__** error.
- This only happens after I present another view controller and go back to the feed.

Can you please tell me what to do? I am stuck on this issue for a long time already.

**Comment by ryanrhee** [comment]
Hey @razvanpaul , thanks for reporting.

Did you verify that `component.nextResponder` when adding the observer and `self` in `-removePlayerStatusNotification` are the same object (i.e. have the same address)?

**Comment by razvanpaul** [comment]
They are the same object, but I put that there so I am sure that every possible observer is removed. Anyway, it's a catch clause, so the app won't crash here, but after something is deallocated by the ComponentKit and there is no callback about it.

Meanwhile, I've tried to move the property from the component to the stateful view, but the bug persists.

**Comment by razvanpaul** [comment]
UPDATE

I continued to debug the issue by enabling some NSZombies. Apparently, as far as I can see right now, there is a serious bug with the `CKCollectionViewTransactionalDataSource` (as a matter of fact, this bug appeared only after I started using it).
As I said in the initial post, this bug occurred only if I presented a view controller and went back. It seems that when I do the following (which is a function called when the presented view controller dismisses): 

```
        NSMutableDictionary <NSIndexPath*, SCRuntimePost*> *items = [NSMutableDictionary new];
        [items setObject: post forKey: indexPath];
        CKTransactionalComponentDataSourceChangeset *changeset = [[[CKTransactionalComponentDataSourceChangesetBuilder transactionalComponentDataSourceChangeset] withUpdatedItems: items] build];
        [self.dataSource applyChangeset:changeset mode: CKUpdateModeSynchronous userInfo:nil];
        [self.dataSource reloadWithMode: CKUpdateModeSynchronous userInfo: nil];
```

When these lines execute, it triggers the remounting of the component perhaps and when the `CKStatefulViewComponentController` tries to create the player by using `playerWithPlayerItem`, this is the moment when the KVO crash takes place. I've tried to place my `removePlayerStatusNotification` function before and after the creation of the video player (which is of course in a background thread), but my presumption is that the new `CKCollectionViewTransactionalDataSource` leaks the component somehow and does not call `dealloc` nor `willRelinquishStatefulView`.

Whoa, this was a long story. Hope I will come with a solution and, of course, that it helps someone around here.

**Comment by razvanpaul** [comment]
Furthermore, if I remove the following line:

```
[self.dataSource reloadWithMode: CKUpdateModeSynchronous userInfo: nil];
```

I don't encounter any bug anymore. Unfortunately, I have another bug now: the update changeset isn't working the first time I go the presented view controller, make some changes and dismiss. Really strange, only the first time.

**Comment by ryanrhee** [comment]
@razvanpaul hmm. can you create a failing test case in the `CKCollectionViewTransactionalDataSource` test suite? It'll make fixing the issue much easier.

**Comment by ocrickard** [comment]
Closing, we lack the information needed to help. Can re-open if a failing unit test is provided.
