### ISSUE TITLE
Lack of components corresponding to UIKit views

### ISSUE THREAD

**Issue by wuwen1030** [facebook/componentkit#730]
There's only few components such as `Button` `Text` `Image` .etc , wonder why there's no whole set of components corresponding to UIKit views.

**Comment by ryanrhee** [comment]
Which ones were you thinking of?

**Comment by ocrickard** [comment]
Yeah, we want to keep the core framework very small so it can be used in any context. We'd love to see people publish auxiliary libraries on top of ComponentKit, and would be happy to promote it on our site if anyone wants to take that on.
