### ISSUE TITLE
Add support for fallback cells to CKCollectionViewTransactionalDataSource

### ISSUE THREAD

**Issue by eczarny** [facebook/componentkit#733]
`CKComponentDataSource` allowed folks to mix component-backed cells with custom cells via the `CKComponentDeciding` API. `CKTransactionalComponentDataSource` purposely does not support this API as it was built under the opinion this functionality is better left as a responsibility of the layer above. Typically falling under the role of the `UICollectionView` (or `UITableView`) component data source.

As I mentioned in #712 our internal data sources mimic the decider functionality by providing a new API based on the concept of fallback cells. If no component is available at a given index path the component data source asks a fallback cell provider for a cell to use in its place. The concept itself is fairly simple and it would be helpful add support for fallback cells to `CKCollectionViewTransactionalDataSource`. That way it can either be used out-of-the-box or as an example for those rolling their own component data sources.

**Comment by ocrickard** [comment]
I feel like this got implemented at some point in the last year for integration in one of the internal apps. Is that the case?

**Comment by fabiomassimo** [comment]
We are currently not considering adding support for this although if you (author/reader) believe this might be helpful for your use case, please let us know by reopening the issue.
