### ISSUE TITLE
Missing documentation for basic components

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#76]
The online documentation is missing for some basic components like CKTextComponent, CKLabelComponent.

Wondering if there is a plan to update it?

I'm looking for how to set an action for attributed string being tapped

**Comment by ocrickard** [comment]
Yep I meant to write some public docs before open sourcing for the text
components but then got swamped doing other things. I can maybe get to them
this weekend.

**Comment by ocrickard** [comment]
I haven't heard too much more about this.  I don't have time right now to work on this, but pull requests are welcome!
