### ISSUE TITLE
crash in CKTextComponentKitLayer

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#761]
I'm getting a crash

[CKTextComponentLayer ck_currentAsyncLayerTransaction]: unrecognized selector sent to instance 0x170255870
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CKTextComponentLayer ck_currentAsyncLayerTransaction]: unrecognized selector sent to instance 0x170255870'

**Comment by avnerbarr** [comment]
I can't find where the getter/setters are actually implemented.
The property is declared in 

```

CKAsyncTransactionContainer+Private.h

@property (nonatomic, retain, setter = ck_setCurrentAsyncLayerTransaction:) CKAsyncTransaction *ck_currentAsyncLayerTransaction;

```
I see it declared as @dynamic in 2 places. Specifically:

```
CKAsyncTransactionContainer.m
@implementation CALayer (CKAsyncTransactionContainerTransactions)
@dynamic ck_asyncLayerTransactions;
@dynamic ck_currentAsyncLayerTransaction;

- (CKAsyncTransaction *)ck_asyncTransaction
{
  CKAsyncTransaction *transaction = self.ck_currentAsyncLayerTransaction; <<<<< crash
 ...
}
```

**Comment by ocrickard** [comment]
Wow yeah, that code for the async layer is super old. Can you switch it to synthesize and see if that works?

**Comment by ocrickard** [comment]
(This code predates my time at FB)

**Comment by avnerbarr** [comment]
its a property on a category so I won't be able to change it to synthesize and I don't understand where its underlying getter is :/ Whats going on here :)

**Comment by ocrickard** [comment]
Ahh, right. Just pulled and will do some snooping. Bizarre.

**Comment by ocrickard** [comment]
Here's the issue: https://github.com/facebook/componentkit/pull/392

Basically CALayer used to act as a full Key-Value store, and this code was depending on that behavior. We should switch over all this code to use assoc objects instead. Mind doing a PR?

**Comment by avnerbarr** [comment]
Sure. Should I do that against master?

**Comment by ocrickard** [comment]
Yep, against master.

**Comment by ocrickard** [comment]
Should be fixed now!
