### ISSUE TITLE
How to know when the truncated string is pressed

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#77]
I see that when I press the truncated string the area around it changes colors. 
How can I get the "tap" action and change the colors of that highlight?

Thanks,

**Comment by ocrickard** [comment]
As mentioned in other issues, CKTextComponentView is a subclass of UIControl.  Check out https://github.com/facebook/componentkit/blob/master/ComponentTextKit/TextKit/CKTextKitRenderer%2BTextChecking.h for the new events it adds.  You probably want to add a target/action for touch up on the truncation token.  I'm in the process of adding a convenience API for this to make it easier though.

**Comment by ocrickard** [comment]
Enabled by https://github.com/facebook/componentkit/pull/83 with a standard component action (though admittedly still not easy).  Working on getting the convenience API up.
