### ISSUE TITLE
Documentation mismatch between CKComponent and quick start guide

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#78]
In the documentation under "state"
http://componentkit.org/docs/state.html

The described method of changing state implies calling a method on CKComponent which isn't exposed in the .h file
```objective-c
@interface CKComponent
- (void)updateState:(id (^)(id))updateBlock; // not in .h file of CKComponent - compiler error . I manually added it to my class , get a "not implemented" warning but it works .
@end
```

The documentation should also explain adding the ```CKComponentActionAttribute``` or another method of getting the callback

**Comment by adamjernst** [comment]
`updateState:` is exposed in `CKComponentSubclass.h`.

Thanks for the feedback though — I agree it's not entirely clear. I'd love a pull request to fix it if you have the time!
