### ISSUE TITLE
No podspec file anymore

### ISSUE THREAD

**Issue by samiq** [facebook/componentkit#792]
Hi guys, is there any reason why from version 0.2 to 0.20 the support for cocoapods was dropped? 

podspec file is no longer available. 

thanks,

G.

**Comment by calimarkus** [comment]
https://github.com/facebook/componentkit/pull/777

**Comment by eczarny** [comment]
The reason is mentioned in the pull request @calimarkus mentions. Maintaining support for CocoaPods has involved a lot of overhead so we decided to drop it.

Moving forward folks should either use Carthage or pull in the source code and Xcode project directly.
