### ISSUE TITLE
How to overlay components on top of other components?

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/componentkit#80]
Hi I'm trying to create a interface where a UIImage is partly on top of a UIView and then another UIView is on top of it. How would I accomplish this?

What I want to implement:
![screen shot 2015-04-08 at 15 32 43](https://cloud.githubusercontent.com/assets/9281756/7047496/c8e214f4-de04-11e4-8cc5-ba7e51c3f414.png)

What I have: 
![ios simulator screen shot 8 apr 2015 15 34 57](https://cloud.githubusercontent.com/assets/9281756/7047520/e68e344c-de04-11e4-9b1e-3b5c19abf553.png)

Never mind the font differences

**Comment by benlodotcom** [comment]
Did you check out `CKOverlayLayoutComponent` ?

**Comment by aaronschubert0** [comment]
@benlodotcom Yeah I did, the problem is that it stretches the component out in top of it, unless I could specify 'blank space'?

**Comment by adamjernst** [comment]
Use `CKInsetComponent` with an infinite left/top inset to remove the stretching:

```
[CKOverlayLayoutComponent
 newWithComponent:component
 overlay:
 [CKInsetComponent
  newWithInsets:{.left = INFINITY, .top = INFINITY}
  component:overlayComponent]]
```

**Comment by aaronschubert0** [comment]
@adamjernst thanks, I'll give that a chance and report back.
