### ISSUE TITLE
Unnecessary Text Layout in CKTextKitRenderer

### ISSUE THREAD

**Issue by b3ll** [facebook/componentkit#809]
Currently CKTextKitRenderer uses the bounds of the text container to render the required glyphs, rather than the bounds passed in through `-drawInContext:bounds:`.

````objc
[_context performBlockWithLockedTextKitComponents:^(NSLayoutManager *layoutManager, NSTextStorage *textStorage, NSTextContainer *textContainer) {
    NSRange glyphRange = [layoutManager glyphRangeForTextContainer:textContainer];
    [layoutManager drawBackgroundForGlyphRange:glyphRange atPoint:shadowInsetBounds.origin];
    [layoutManager drawGlyphsForGlyphRange:glyphRange atPoint:shadowInsetBounds.origin];
}];
````

Is there any reason for this?

I'm currently laying out text in a `UIScrollView`, which can change dynamically, and I'd rather it not redraw the entire scrollview's `-contentSize` of glyphs, since that can be extremely expensive. For larger sets of text, it's actually impossible to draw the whole set since it ends up being so memory intensive.

**Comment by ocrickard** [comment]
Ahh, I think that sounds great, I can't think of a good reason not to use a passed-in rect! PR please.
