### ISSUE TITLE
Request to add minimum font size in Label

### ISSUE THREAD

**Issue by mechazod** [facebook/componentkit#836]
![screen shot 2017-06-23 at 10 55 42 am](https://user-images.githubusercontent.com/16739905/27464820-0dd587f2-5802-11e7-8669-6f1974f0e0ea.png)

**Comment by ryanrhee** [comment]
Thanks for the suggestion!

Happy to consider this feature given a pull request that implements it; otherwise, we likely won't be looking at it.

**Comment by mechazod** [comment]
Thanks @ryanrhee really appreciated. 👍
