### ISSUE TITLE
-Werror incorrectly specified in podspec

### ISSUE THREAD

**Issue by cfcommando** [facebook/componentkit#84]
Including `GCC_TREAT_WARNINGS_AS_ERRORS` in the podspec's xcconfig parameters doesn't mean that ComponentKit alone will be compiled with `-Werror`. Instead a line will be added to `Pods/Target\ Support\ Files/Pods/Pods.*.xcconfig`, against which project and pods code will be compiled.

While treating warnings as errors is a good policy, it's (unfortunately) not a reasonable constraint to impose on other projects. The flag should be removed. Fortunately, this should be equivalent and applicable more narrowly to ComponentKit specifically:
```diff
+  s.compiler_flags = '-Werror -Wall'
   s.xcconfig = {
     'CLANG_CXX_LANGUAGE_STANDARD' => 'c++11',
     'CLANG_CXX_LIBRARY' => 'libc++',
-    'GCC_TREAT_WARNINGS_AS_ERRORS' => 'YES'
```

**Comment by dstnbrkr** [comment]
Thanks. It's unexpected that this flag leaks out to all pods.

**Comment by cfcommando** [comment]
This is basically a build-break. @ocrickard do you think you could get it in before tagging the next release, please?

**Comment by ocrickard** [comment]
@dstnbrkr is the one who's the tagging master.

**Comment by ocrickard** [comment]
https://github.com/facebook/componentkit/pull/91

**Comment by dstnbrkr** [comment]
Fixed in master, will be included in next pod release
