### ISSUE TITLE
Don't synchronously unmount components after -updateState

### ISSUE THREAD

**Issue by cfcommando** [facebook/componentkit#87]
`CKComponentActionSend` can crash if called after `updateState` because updating state may unmount the component synchronously. 

See: #86 

@adamjernst says:
> This is really a bug with updateState that we plan to address shortly. It shouldn't synchronously unmount; instead that should be deferred to the end of the run loop.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by adamjernst** [comment]
This is fixed with the transactional data source!
