### ISSUE TITLE
Layout error with CKFlexboxDirectionVerticalReverse or CKFlexboxDirectionHorizontalReverse

### ISSUE THREAD

**Issue by zhfeng20108** [facebook/componentkit#870]
[
<img width="765" alt="2017-09-21 5 00 23" src="https://user-images.githubusercontent.com/5362172/30687646-92cb2e52-9eee-11e7-8fdd-7c7a9a604e26.png">
](url)

**Comment by gkassabli** [comment]
@zhfeng20108 This seems to work correctly. Vertical reverse forces elements to be placed from the bottom to top, so line compoment is below label component as expected

**Comment by zhfeng20108** [comment]
but, the space between label and  line compoment should be 50

**Comment by gkassabli** [comment]
Okay, I see the issue, thanks for reporting! I'll follow up with fix soon

**Comment by gkassabli** [comment]
Should already be fixed
