### ISSUE TITLE
Xcode9 error:No matching constructor for initialization of 'const CKButtonComponentOptions &'

### ISSUE THREAD

**Issue by zhfeng20108** [facebook/componentkit#871]
<img width="706" alt="2017-09-22 2 42 34" src="https://user-images.githubusercontent.com/5362172/30732292-718928f4-9f37-11e7-90fd-a253f0e56528.png">

**Comment by gkassabli** [comment]
This was the issue recently, but should already be fixed, please pull to the latest version and check if it is working

**Comment by zhfeng20108** [comment]
I had  pull to the latest version, but  the issue already exist on Xcode8 and Xcode9

**Comment by zhfeng20108** [comment]
@gkassabli

**Comment by asimiftikhar** [comment]
@zhfeng20108  is this issue resolved?
