### ISSUE TITLE
Can not add stroke to the word

### ISSUE THREAD

**Issue by zhfeng20108** [facebook/componentkit#872]
To add stroke to the word，we need settings:
NSStrokeColorAttributeName:[UIColor blackColor],
NSStrokeWidthAttributeName:@(-1)
but, The above two lines are not supported in CKLabelAttributes.

**Comment by gkassabli** [comment]
CKLabelComponent is a simplified version of CKTextComponent. Attributes you've mentioned are supported in NSAttributedString. You should use CKTextComponent if you want to use NSAttributedString.
