### ISSUE TITLE
Not find imageAlignment in CKButtonComponentOptions 

### ISSUE THREAD

**Issue by zhfeng20108** [facebook/componentkit#873]
In Arabic, we need to reverse,  like this
typedef NS_ENUM(NSInteger, ASButtonNodeImageAlignment) {
  /** Places the image before the text. */
  ASButtonNodeImageAlignmentBeginning,
  /** Places the image after the text. */
  ASButtonNodeImageAlignmentEnd
};

**Comment by gkassabli** [comment]
We rely on internal UIButton logic for this and because it's not supported there, we don't have a reasonable way to support it in CKButtonComponent. You can use imageEdgeInsets to control that however
