### ISSUE TITLE
CKStaticLayoutComponent and CKButtonComponent not work

### ISSUE THREAD

**Issue by zhfeng20108** [facebook/componentkit#874]
<img width="1021" alt="2017-09-27 1 45 32" src="https://user-images.githubusercontent.com/5362172/30897710-4dbf44be-a31d-11e7-8013-648a497e01da.png">

**Comment by dshahidehpour** [comment]
@zhfeng20108 I just rebased and ran WildeGuess, and I'm not seeing build errors. Please rebase :)
