### ISSUE TITLE
Example app 'WildeGuess' does not compile

### ISSUE THREAD

**Issue by thurn** [facebook/componentkit#888]
Following the instructions in the 'Getting Started' guide, I get this error when I attempt to compile the WildeGuess app:

    No such file or directory: '<...>/componentkit/Carthage/Checkouts/yoga/yoga/Yoga.c'

Using Xcode 9.0.1.

**Comment by dshahidehpour** [comment]
Looks like you need to run `carthage bootstrap`

**Comment by vividcode** [comment]
You need to run following command fter carthage bootstrap in order for the whole thing to work out of XCode:

`bash build.sh ci-componentkit-ios`


I have already [updated readme.md with pull request.](https://github.com/facebook/componentkit/pull/891)

**Comment by gkassabli** [comment]
This should be corrected with https://github.com/facebook/componentkit/commit/405bcc8404ef5c9703e7c152fd0ff27230ecc821
