### ISSUE TITLE
Question - Is it possible to have half screen width UICollectionViewCells with ComponentsKit?

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/componentkit#89]
Currently I'm trying to create a half screen width component so that in theory I could have two cells side by side.

This is the code I've got and my expectation is that it would fill only half the width of the screen but it fills the whole screen width instead:
```
    return [super newWithComponent:
            [CKComponent
             newWithView:{
                 [UIView class],
                 {
                     {@selector(setBackgroundColor:),[UIColor redColor]}
                 }
             }
             size:{
                 .width = CKRelativeDimension::Percent(0.5),.height = 120
             }]];
```

**Comment by smiLLe** [comment]
You could try to set the constrained size to the half width of your CollectionView?!

```
[_dataSource
        enqueueChangeset:{listSctions, listItems}
        constrainedSize:[_sizeRangeProvider
          sizeRangeForBoundingSize:CGSizeMake(CGRectGetWidth(self.collectionView.bounds) / 2.0f, CGRectGetHeight(self.collectionView.bounds))
        ]
      ];
```

**Comment by aaronschubert0** [comment]
But of course!! Just a heads up for anyone else trying this, you need to enqueue this on a separate CKArrayControllerInputItems otherwise, all the previous items are affected (obviously)
