### ISSUE TITLE
error with carthage update --platform iOS

### ISSUE THREAD

**Issue by zhfeng20108** [facebook/componentkit#893]
The latest code error
*** Checking out ComponentKit at "91b93bbd763ef9afe6553f28d2977113ca02b6f4"
*** xcodebuild output can be found in /var/folders/gf/lxnp2cg115zcqkb7y7ngc3880000gn/T/carthage-xcodebuild.LaPjRL.log
*** Building scheme "ComponentKit" in ComponentKit.xcodeproj
Build Failed
	Task failed with exit code 65:

**Comment by gkassabli** [comment]
Could you please provide some context on when this error is happening

**Comment by zhfeng20108** [comment]
I create a new project 'TestYYY', then create file Cartfile, execute 'carthage update --platform iOS'

**Comment by zhfeng20108** [comment]
The Cartfile's content is "github "facebook/ComponentKit" "91b93bbd763ef9afe6553f28d2977113ca02b6f4""

**Comment by gkassabli** [comment]
Thanks for the report!
This should be fixed on latest commit.
