### ISSUE TITLE
Conversion to Swift 

### ISSUE THREAD

**Issue by GodsEye-07** [facebook/componentkit#899]
please convert the code to the swift language for much easy and no headers to be included in between as people may then import only the part that is necessary for them.

**Comment by ocrickard** [comment]
I wrote a Swift version of CK here, it's a WIP, not sure when I'll have time to finish it. If anyone wants to take any parts of it for any integration work, please do!

http://theodolite.org

**Comment by fabiomassimo** [comment]
Conversion to Swift is not currently a high priority in our roadmap but thanks for sharing interest such that we can better understand the external demand for it.
