### ISSUE TITLE
After updating Xcode to 6.3 - Xcode displays an error for an internal file.

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/componentkit#90]
Xcode is displaying an error for line 69 in CKTextKitRendererCache.h : 
```
        const Key(CKTextKitAttributes a, CGSize cs);
```

The error is : Constructor cannot have a return type.

Not sure if this is specific to me or widespread.

**Comment by aaronschubert0** [comment]
When I reference the pod directly like so, pod 'ComponentKit', :git => 'https://github.com/facebook/componentkit.git'

Then the error is fixed...

**Comment by ocrickard** [comment]
Hmm, that should have been fixed in https://github.com/facebook/componentkit/pull/7 . Maybe we need to update the pod setting or something (I know nothing about cocoapods :P ).

**Comment by dstnbrkr** [comment]
Yep, we can tag a new release that includes the fix

**Comment by dstnbrkr** [comment]
ComponentKit pod updated to 0.10

**Comment by aaronschubert0** [comment]
Awesome, thanks guys!
