### ISSUE TITLE
Fatal Exception: std::__1::system_error: mutex lock failed: Invalid argument

### ISSUE THREAD

**Issue by zhfeng20108** [facebook/componentkit#905]
<img width="1131" alt="2018-04-12 10 27 34" src="https://user-images.githubusercontent.com/5362172/38653455-6edf9ea8-3e3d-11e8-88f4-02cd39c7110b.png">
[issue_4372_crash.txt](https://github.com/facebook/componentkit/files/1901142/issue_4372_crash.txt)

This crash happened too much when app in background. Is there a way to avoid it?

**Comment by ocrickard** [comment]
Same fix in https://github.com/facebook/componentkit/pull/906

**Comment by ocrickard** [comment]
@zhfeng20108 would you mind patching the change in #906 to your local branch and verifying if it fixes the reported crash in your app? Since you're the only reporting user, it'll be hard for the folks at FB to merge until they get confirmation that it fixes your problem.

**Comment by alickbass** [comment]
@ocrickard thanks for taking care of it! I will close the issue
