### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ishall1** [facebook/componentkit#908]
Skipped building yoga due to the error:
Dependency "yoga" has no shared framework schemes for any of the platforms: iOS

**Comment by alickbass** [comment]
Hi! Are you using `carthage checkout` command?

**Comment by ishall1** [comment]
@alickbass Thanks for your reply. I used 'carthage update' command. Is there a way to fix it?

**Comment by alickbass** [comment]
Yes :) please use `checkout` instead

**Comment by ishall1** [comment]
@alickbass Thank you very much. It works.
