### ISSUE TITLE
Public roadmap

### ISSUE THREAD

**Issue by ocrickard** [facebook/componentkit#909]
Is it possible to publish the roadmap for CK publicly?

I use CK in a number of personal projects, and want to understand where it's headed.

**Comment by ocrickard** [comment]
Ping, it's been a few weeks. Anyone there?

**Comment by conradev** [comment]
I would also love to see this!

**Comment by ocrickard** [comment]
Any update here?

**Comment by fabiomassimo** [comment]
We are considering the demand for a public roadmap, thanks for showing your interest. The future of ComponentKit is very bright (trust me 😉) although sharing a roadmap currently is something we only manage to do internally. We will reconsider this once again and keep this space updated.
