### ISSUE TITLE
ComponenKit should depend on Yoga 1.6 instead of 1.6.0

### ISSUE THREAD

**Issue by pkrmf** [facebook/componentkit#913]
We should try to avoid setting a dependency on a patch version. Imagine the following situation:

Application pulls 2 Frameworks as dependencies, **Framework A** and **ComponentKit**.
- **Framework A** has a dependency on **Yoga ~>1.8**
- **ComponentKit(master)** has a dependency on **Yoga ~>1.6.0**

Cocoapods won't allow the consuming application to pod install, since it will treat **1.6.0 to 1.8 as a major version change**, even though its not and there should be no breaking API changes.

**The correct approach here should be that ComponentKit has a dependency on Yoga ~>1.6 instead of 1.6.0**, this way, the application will be able to install Framework A, ComponentKit and Yoga 1.8.x

Let me know if you guys are ok with me updating the podspec!

**Comment by madcato** [comment]
This issue is causing me this problem:

ComponentKit uses the identifier **YGJustifySpaceEvenly** defined in Yoga version **1.7** . But Cocoapods don't let me update Yoga to that version, because **yoga ~>1.6.0** configuration.

**Comment by alickbass** [comment]
Seems fair, @pkrmf. Do you want to submit a PR?

**Comment by pkrmf** [comment]
@alickbass Sure!

**Comment by pkrmf** [comment]
@alickbass [PR](https://github.com/facebook/componentkit/pull/914) 

We should be looking to publishing the podspec to cocoapods master repo

**Comment by pkrmf** [comment]
@alickbass just a reminder about publishing the new podspec to cocoapods. Is there any way I could help on that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alickbass** [comment]
@pkrmf I have just pushed to trunk! Thanks for your contribution and please let me know if everything is working for you!

**Comment by pkrmf** [comment]
@alickbass you are the man! Thank you so much!

**Comment by alickbass** [comment]
I am gonna close this issue. Feel free to reopen it in case something is not working
