### ISSUE TITLE
how can I create scrollview component

### ISSUE THREAD

**Issue by nicreals** [facebook/componentkit#924]
https://github.com/facebook/componentkit/issues/651 
this issue mentioned that we can impletation a scrollalbe componnet with CKStackLayoutComponent,
but CKStackLayoutComponent is deleted in the latest release.

is there any way we can add a scrollable view within Componetkit?

**Comment by aCorrado** [comment]
You could use [CKFlexboxComponent](https://github.com/facebook/componentkit/blob/master/ComponentKit/LayoutComponents/CKFlexboxComponent.h) instead of CKStackLayoutComponent, and then follow the suggestions in the thread
