### ISSUE TITLE
[Documentation] Views path is not render

### ISSUE THREAD

**Issue by fanny** [facebook/componentkit#951]
## 🐛 Bug Report

(A clear and concise description of what the bug is)
When we are navigating to Views page of the reference docs, the page is not found

### Have you read the [Contributing Guidelines on issues]
yes

## To Reproduce
![image](https://user-images.githubusercontent.com/14113480/83336180-b63da780-a287-11ea-85f0-3d67107a276a.png)
Click on views in the sidebar

## Expected behavior
it render the view page

## Actual Behavior

![image](https://user-images.githubusercontent.com/14113480/83336150-6fe84880-a287-11ea-89b5-90f07c7f2598.png)

**Comment by fanny** [comment]
I didn't found the location of the docusaurus setup, if you guys need help I can do a PR.

**Comment by fanny** [comment]
The same happens for a bunch of other paths like: `docs/identation`, `avoid-single-use-constants`, `component-context`,

**Comment by fabiomassimo** [comment]
Sorry for the disruption this should be solved now.

Please open a new issue if it's still not working for you.
