### ISSUE TITLE
Xcode not building ComponentKit checked out via cocoapods

### ISSUE THREAD

**Issue by carolinea87** [facebook/componentkit#957]
I used cocoapods to add componentkit as a dependency. When I try to build the project I get build error:

`"Could not build module ComponentKit"`

Here is my podfile
<img width="901" alt="Screen Shot 2020-10-17 at 11 52 21 PM" src="https://user-images.githubusercontent.com/34731962/96360664-e4574300-10d3-11eb-9891-5d23f0da81ba.png">

```
platform :ios, '13.0'
use_frameworks!

project 'XYZ/XYZ.xcodeproj'

target 'XYZ' do
  pod 'ComponentKit', '~> 0.30'
  pod 'Protobuf', '~> 3.13'
end
```

**Comment by carolinea87** [comment]
Can anyone help? Now importing ComponentKit/ComponentKit.h works by I am unable to import CKCollectionViewDataSource.h. I am planning to ditch ComponentKit if I keep getting these issues. It is so painful to use a library which is not maintained well.

**Comment by aCorrado** [comment]
If you try to rename your file from "ViewController.m" to "ViewController.mm" it should work.

ComponentKit is an ObjectiveC++ library and this means that the files that import CK should use the ".mm" extension
