### ISSUE TITLE
Build Error with "RenderCoreLayoutCaching"

### ISSUE THREAD

**Issue by megha1208** [facebook/componentkit#961]
I am getting the following build error when I tried to run the sample project for the first time:

<img width="1392" alt="Screen Shot 2021-04-15 at 10 08 21 AM" src="https://user-images.githubusercontent.com/33864211/114814766-83829c00-9dd2-11eb-87ab-f5813ff6c108.png">

Is there any workaround to this issue as RenderCoreLayoutCaching is not included in the componentKit?

**Comment by cuva** [comment]
Hey @megha1208 this should be fixed on `master`, although we recommend using the released pod.

Closing.
